create table if not exists public.tenants (
  tenant_id integer generated by default as identity primary key,

  brand_name text not null,
  owner_name text not null,

  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.website_settings
add column if not exists tenant_id integer;

alter table public.website_settings
add constraint website_settings_tenant_id_unique unique (tenant_id);

alter table public.website_settings
add constraint website_settings_tenant_id_fkey
foreign key (tenant_id)
references public.tenants(tenant_id)
on delete set null;