-- Restore the database foundation used by the original /auth/signup route.
-- This is intentionally idempotent so it can be uploaded to Supabase even when
-- some of these objects already exist.

begin;

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create table if not exists public.tenants (
  tenant_id integer generated by default as identity primary key,
  brand_name text not null default '',
  owner_name text not null default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.tenants
add column if not exists brand_name text not null default '';

alter table public.tenants
add column if not exists owner_name text not null default '';

alter table public.tenants
add column if not exists created_at timestamp with time zone default now();

alter table public.tenants
add column if not exists updated_at timestamp with time zone default now();

drop trigger if exists set_tenants_updated_at on public.tenants;

create trigger set_tenants_updated_at
before update on public.tenants
for each row
execute function public.set_updated_at();

alter table public.users
add column if not exists tenant_id integer;

alter table public.users
drop constraint if exists users_tenant_id_unique;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'users_tenant_id_fkey'
      and conrelid = 'public.users'::regclass
  ) then
    alter table public.users
    add constraint users_tenant_id_fkey
    foreign key (tenant_id)
    references public.tenants(tenant_id)
    on delete set null
    not valid;
  end if;
end $$;

create table if not exists public.tenant_memberships (
  id bigint generated by default as identity primary key,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  auth_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member',
  status text not null default 'active',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint tenant_memberships_role_check
    check (role in ('owner', 'admin', 'member')),
  constraint tenant_memberships_status_check
    check (status in ('active', 'invited', 'disabled')),
  constraint tenant_memberships_user_tenant_unique
    unique (user_id, tenant_id),
  constraint tenant_memberships_auth_tenant_unique
    unique (auth_id, tenant_id)
);

alter table public.tenant_memberships
add column if not exists tenant_id integer;

alter table public.tenant_memberships
add column if not exists user_id integer;

alter table public.tenant_memberships
add column if not exists auth_id uuid;

alter table public.tenant_memberships
add column if not exists role text not null default 'member';

alter table public.tenant_memberships
add column if not exists status text not null default 'active';

alter table public.tenant_memberships
add column if not exists created_at timestamp with time zone default now();

alter table public.tenant_memberships
add column if not exists updated_at timestamp with time zone default now();

drop trigger if exists set_tenant_memberships_updated_at on public.tenant_memberships;

create trigger set_tenant_memberships_updated_at
before update on public.tenant_memberships
for each row
execute function public.set_updated_at();

insert into public.tenant_memberships (tenant_id, user_id, auth_id, role, status)
select u.tenant_id, u.id, u.auth_id, 'owner', 'active'
from public.users u
where u.tenant_id is not null
  and u.auth_id is not null
  and not exists (
    select 1
    from public.tenant_memberships tm
    where tm.user_id = u.id
      and tm.tenant_id = u.tenant_id
  );

create index if not exists tenant_memberships_tenant_id_idx
on public.tenant_memberships (tenant_id);

create index if not exists tenant_memberships_auth_id_idx
on public.tenant_memberships (auth_id);

grant select, insert, update, delete on table public.tenants to service_role;
grant select, insert, update, delete on table public.users to service_role;
grant select, insert, update, delete on table public.tenant_memberships to service_role;

do $$
begin
  if to_regclass('public.tenants_tenant_id_seq') is not null then
    grant usage, select on sequence public.tenants_tenant_id_seq to service_role;
  end if;

  if to_regclass('public.tenant_memberships_id_seq') is not null then
    grant usage, select on sequence public.tenant_memberships_id_seq to service_role;
  end if;

  if to_regclass('public.users_id_seq') is not null then
    grant usage, select on sequence public.users_id_seq to service_role;
  end if;
end $$;

grant select on table public.tenants to authenticated;
grant select on table public.tenant_memberships to authenticated;

alter table public.tenants enable row level security;
alter table public.tenant_memberships enable row level security;

drop policy if exists tenants_select_member on public.tenants;
drop policy if exists tenant_memberships_select_same_tenant on public.tenant_memberships;

create policy tenants_select_member
on public.tenants
for select
to authenticated
using (
  exists (
    select 1
    from public.tenant_memberships tm
    where tm.tenant_id = tenants.tenant_id
      and tm.auth_id = auth.uid()
      and tm.status = 'active'
  )
);

create policy tenant_memberships_select_same_tenant
on public.tenant_memberships
for select
to authenticated
using (auth_id = auth.uid());

notify pgrst, 'reload schema';

commit;
