-- ============================================================
-- AI chatbot daily usage counters
-- ============================================================

begin;

create table if not exists public.ai_usage_daily (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  tenant_id integer references public.tenants(tenant_id) on delete cascade,
  usage_date date not null default current_date,
  message_count integer not null default 0,
  code_generation_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_usage_daily_message_count_nonnegative check (message_count >= 0),
  constraint ai_usage_daily_code_generation_count_nonnegative check (code_generation_count >= 0),
  constraint ai_usage_daily_user_date_unique unique (user_id, usage_date)
);

create index if not exists ai_usage_daily_tenant_date_idx
on public.ai_usage_daily (tenant_id, usage_date);

create or replace function public.touch_ai_usage_daily_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_ai_usage_daily_updated_at on public.ai_usage_daily;

create trigger touch_ai_usage_daily_updated_at
before update on public.ai_usage_daily
for each row
execute function public.touch_ai_usage_daily_updated_at();

create or replace function public.increment_ai_usage_daily(
  p_user_id integer,
  p_tenant_id integer default null,
  p_usage_date date default current_date,
  p_message_delta integer default 1,
  p_code_generation_delta integer default 0
)
returns table (
  message_count integer,
  code_generation_count integer
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  insert into public.ai_usage_daily (
    user_id,
    tenant_id,
    usage_date,
    message_count,
    code_generation_count
  )
  values (
    p_user_id,
    p_tenant_id,
    coalesce(p_usage_date, current_date),
    greatest(coalesce(p_message_delta, 0), 0),
    greatest(coalesce(p_code_generation_delta, 0), 0)
  )
  on conflict (user_id, usage_date)
  do update set
    tenant_id = coalesce(excluded.tenant_id, public.ai_usage_daily.tenant_id),
    message_count = public.ai_usage_daily.message_count + greatest(coalesce(p_message_delta, 0), 0),
    code_generation_count = public.ai_usage_daily.code_generation_count + greatest(coalesce(p_code_generation_delta, 0), 0)
  returning
    public.ai_usage_daily.message_count,
    public.ai_usage_daily.code_generation_count;
end;
$$;

alter table public.ai_usage_daily enable row level security;

revoke all on table public.ai_usage_daily from anon;
revoke all on table public.ai_usage_daily from authenticated;

grant select, insert, update, delete
on table public.ai_usage_daily
to service_role;

revoke all on function public.increment_ai_usage_daily(integer, integer, date, integer, integer) from anon;
revoke all on function public.increment_ai_usage_daily(integer, integer, date, integer, integer) from authenticated;
grant execute on function public.increment_ai_usage_daily(integer, integer, date, integer, integer) to service_role;

notify pgrst, 'reload schema';

commit;
