create table if not exists public.tenant_site_memberships (
  id bigint generated by default as identity primary key,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  auth_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'customer',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_site_memberships_role_check check (role in ('customer')),
  constraint tenant_site_memberships_status_check check (status in ('active', 'disabled')),
  constraint tenant_site_memberships_user_tenant_unique unique (tenant_id, user_id),
  constraint tenant_site_memberships_auth_tenant_unique unique (tenant_id, auth_id)
);

drop trigger if exists set_tenant_site_memberships_updated_at on public.tenant_site_memberships;
create trigger set_tenant_site_memberships_updated_at
before update on public.tenant_site_memberships
for each row execute function public.set_updated_at();

create index if not exists tenant_site_memberships_tenant_status_idx
  on public.tenant_site_memberships (tenant_id, status);

alter table public.tenant_site_memberships enable row level security;
revoke all on table public.tenant_site_memberships from anon, authenticated;
grant all on table public.tenant_site_memberships to service_role;
grant usage, select on sequence public.tenant_site_memberships_id_seq to service_role;
