export const userManagementLabels = {
  en: {
    kicker: "Admin",
    title: "User Management",
    subtitle: "Review accounts, roles, tenant plans, and payment status from one workspace.",
    search: "Search users",
    refresh: "Refresh",
    totalUsers: "Total users",
    admins: "Admins",
    activePlans: "Active plans",
    page: "Page",
    previous: "Previous",
    next: "Next",
    shownUsers: "All users",
    usersPerPage: "Users per page",
    role: "Role",
    plan: "Plan",
    status: "Status",
    builder: "Builder",
    tenant: "Tenant",
    user: "User",
    admin: "Admin",
    saveRole: "Save role",
    applyPlan: "Apply plan",
    deleteUser: "Delete",
    deleteTitle: "Delete this user?",
    deleteMessage: "This user account and its access will be removed. This cannot be undone.",
    confirmDelete: "Confirm delete",
    deletingUser: "Deleting...",
    cancelDelete: "Keep user",
    noUsers: "No users found.",
    loading: "Loading users",
    forbidden: "Only admins can manage users.",
    loadError: "Could not load users.",
    saved: "Changes saved.",
    deleted: "User deleted.",
    fullPlatform: "Full platform",
    individualBuilder: "Individual builder",
    none: "None",
    fallbackUser: "Madar User",
  },
  ar: {
    kicker: "مسؤول",
    title: "إدارة المستخدمين",
    subtitle: "راجع الحسابات والأدوار وخطط المستأجرين وحالة الدفع من مساحة واحدة.",
    search: "ابحث عن مستخدمين",
    refresh: "تحديث",
    totalUsers: "إجمالي المستخدمين",
    admins: "المسؤولون",
    activePlans: "الخطط النشطة",
    page: "الصفحة",
    previous: "السابق",
    next: "التالي",
    shownUsers: "المستخدمون المعروضون",
    usersPerPage: "عدد المستخدمين في الصفحة",
    role: "الدور",
    plan: "الخطة",
    status: "الحالة",
    builder: "المنشئ",
    tenant: "المستأجر",
    user: "مستخدم",
    admin: "مسؤول",
    saveRole: "حفظ الدور",
    applyPlan: "تطبيق الخطة",
    deleteUser: "ط­ط°ظپ",
    confirmDelete: "تأكيد الحذف",
    deletingUser: "جاري الحذف...",
    cancelDelete: "إلغاء",
    noUsers: "لا يوجد مستخدمون.",
    loading: "جاري تحميل المستخدمين",
    forbidden: "يمكن للمسؤولين فقط إدارة المستخدمين.",
    loadError: "تعذر تحميل المستخدمين.",
    saved: "تم حفظ التغييرات.",
    deleted: "تم حذف المستخدم.",
    fullPlatform: "المنصة الكاملة",
    individualBuilder: "منشئ فردي",
    none: "لا يوجد",
    fallbackUser: "Madar User",
  },
};

export const platformPlans = ["starter", "pro", "business"];
export const builderPlans = ["basic", "premium"];
export const builderTypes = ["website", "forms", "quiz", "reservation", "reports", "data"];
export const paymentStatuses = ["pending", "active", "past_due", "canceled"];

export const userManagementLabelOverrides = {
  ar: {
    shownUsers: "كل المستخدمين",
    deleteTitle: "حذف هذا المستخدم؟",
    deleteMessage: "سيتم حذف حساب المستخدم وصلاحيات الوصول الخاصة به. لا يمكن التراجع عن هذا الإجراء.",
    confirmDelete: "تأكيد الحذف",
    deletingUser: "جاري الحذف...",
    cancelDelete: "إبقاء المستخدم",
  },
};

export const userManagementFriendlyLabels = {
  en: {
    subscription_type: {
      full_platform: "Full platform",
      individual_builder: "Single builder",
    },
    plan: {
      starter: "Starter",
      pro: "Pro",
      business: "Business",
      basic: "Basic",
      premium: "Premium",
    },
    builder_type: {
      website: "Website",
      forms: "Forms",
      quiz: "Quiz",
      reservation: "Reservation",
      reports: "Reports",
      data: "Data analysis",
    },
    payment_status: {
      pending: "Pending setup",
      pending_review: "Pending review",
      active: "Active",
      scheduled_change: "Scheduled change",
      past_due: "Payment issue",
      suspended: "Suspended",
      canceled: "Canceled",
      expired: "Expired",
      review_required: "Review required",
    },
  },
  ar: {
    subscription_type: {
      full_platform: "المنصة الكاملة",
      individual_builder: "منشئ واحد",
    },
    plan: {
      starter: "المبتدئ",
      pro: "الاحترافي",
      business: "الأعمال",
      basic: "أساسي",
      premium: "مميز",
    },
    builder_type: {
      website: "الموقع",
      forms: "النماذج",
      quiz: "الاختبارات",
      reservation: "الحجوزات",
      reports: "التقارير",
      data: "تحليل البيانات",
    },
    payment_status: {
      pending: "بانتظار الإعداد",
      pending_review: "بانتظار المراجعة",
      active: "نشطة",
      scheduled_change: "تغيير مجدول",
      past_due: "مشكلة دفع",
      suspended: "معلقة",
      canceled: "ملغاة",
      expired: "منتهية",
      review_required: "تتطلب مراجعة",
    },
  },
};


export const getUserManagementLabels = (lang = "en") => ({
  ...(userManagementLabels[lang === "ar" ? "ar" : "en"] || userManagementLabels.en),
  ...(userManagementLabelOverrides[lang === "ar" ? "ar" : "en"] || {}),
});

export const getUserManagementFriendlyLabels = (lang = "en") =>
  userManagementFriendlyLabels[lang === "ar" ? "ar" : "en"] || userManagementFriendlyLabels.en;
