export const myPlanContent = {
  en: {
    kicker: "Plan",
    title: "My Plan",
    subtitle:
      "Manage your Madar subscription, enabled builders, usage, and upgrade options.",
    currentPlan: "Current plan",
    billing: "Billing",
    monthly: "Monthly",
    status: "Active",
    renews: "Renews",
    upgrade: "Upgrade plan",
    manageBilling: "Manage billing",
    includedBuilders: "Included builders",
    availableBuilders: "Available add-ons",
    usageTitle: "Usage overview",
    limitsTitle: "Plan limits",
    active: "Active",
    locked: "Locked",
    included: "Included",
    add: "Add builder",
    perMonth: "/ month",
    planName: "Pro",
    planPrice: "$29",
    planDescription:
      "Build operational workflows with forms, quizzes, reports, reservations, and data analysis.",
    renewalDate: "June 28, 2026",
    usage: [
      { label: "Projects", value: 1, max: 5 },
      { label: "Users", value: 3, max: 10 },
      { label: "Responses", value: 128, max: 1000 },
      { label: "Storage", value: 2.4, max: 10, suffix: "GB" },
    ],
    builders: [
      {
        id: "website",
        icon: "●",
        name: "Website Builder",
        price: "$15",
        desc: "Responsive pages, sections, templates, branded sites, and publishing.",
        enabled: true,
      },
      {
        id: "forms",
        icon: "▣",
        name: "Form Builder",
        price: "$9",
        desc: "Forms, fields, submissions, exports, and response dashboards.",
        enabled: true,
      },
      {
        id: "quiz",
        icon: "✓",
        name: "Quiz Builder",
        price: "$9",
        desc: "Scoring, answer keys, timers, pass/fail results, and review modes.",
        enabled: true,
      },
      {
        id: "reservation",
        icon: "◇",
        name: "Reservation Builder",
        price: "$9",
        desc: "Appointments, services, date/time fields, guests, and requests.",
        enabled: true,
      },
      {
        id: "reports",
        icon: "□",
        name: "Report Builder",
        price: "$19",
        desc: "Finance, operations, monitoring, and custom report templates.",
        enabled: true,
      },
      {
        id: "data",
        icon: "◉",
        name: "Data Workspace",
        price: "$29",
        desc: "CSV/XLS uploads, API imports, cleaning, inspection, and analysis.",
        enabled: true,
      },
    ],
  },

  ar: {
    kicker: "الخطة",
    title: "خطتي",
    subtitle:
      "أدر اشتراكك في مدار، والمنشئات المفعلة، والاستخدام، وخيارات الترقية.",
    currentPlan: "الخطة الحالية",
    billing: "الفوترة",
    monthly: "شهرياً",
    status: "نشطة",
    renews: "تتجدد في",
    upgrade: "ترقية الخطة",
    manageBilling: "إدارة الفوترة",
    includedBuilders: "المنشئات المشمولة",
    availableBuilders: "إضافات متاحة",
    usageTitle: "نظرة على الاستخدام",
    limitsTitle: "حدود الخطة",
    active: "مفعّل",
    locked: "مقفل",
    included: "مشمول",
    add: "إضافة منشئ",
    perMonth: "/ شهر",
    planName: "الاحترافية",
    planPrice: "$29",
    planDescription:
      "أنشئ تدفقات عمل تشغيلية مع النماذج والاختبارات والتقارير والحجوزات وتحليل البيانات.",
    renewalDate: "28 يونيو 2026",
    usage: [
      { label: "المشاريع", value: 1, max: 5 },
      { label: "المستخدمون", value: 3, max: 10 },
      { label: "الردود", value: 128, max: 1000 },
      { label: "التخزين", value: 2.4, max: 10, suffix: "GB" },
    ],
    builders: [
      {
        id: "website",
        icon: "●",
        name: "منشئ المواقع",
        price: "$15",
        desc: "صفحات متجاوبة، وأقسام، وقوالب، ومواقع بعلامتك التجارية مع النشر.",
        enabled: true,
      },
      {
        id: "forms",
        icon: "▣",
        name: "منشئ النماذج",
        price: "$9",
        desc: "نماذج، وحقول، وردود، وتصدير، ولوحات متابعة للنتائج.",
        enabled: true,
      },
      {
        id: "quiz",
        icon: "✓",
        name: "منشئ الاختبارات",
        price: "$9",
        desc: "تصحيح، ومفاتيح إجابات، ومؤقتات، ونتائج نجاح وفشل، ومراجعة.",
        enabled: true,
      },
      {
        id: "reservation",
        icon: "◇",
        name: "منشئ الحجوزات",
        price: "$9",
        desc: "مواعيد، وخدمات، وحقول تاريخ ووقت، وعدد ضيوف، وطلبات.",
        enabled: true,
      },
      {
        id: "reports",
        icon: "□",
        name: "منشئ التقارير",
        price: "$19",
        desc: "تقارير مالية وتشغيلية ومتابعة وقوالب تقارير مخصصة.",
        enabled: true,
      },
      {
        id: "data",
        icon: "◉",
        name: "مساحة البيانات",
        price: "$29",
        desc: "رفع CSV/XLS، واستيراد API، وتنظيف البيانات ومراجعتها وتحليلها.",
        enabled: true,
      },
    ],
  },
};

export const getMyPlanContent = (lang = "en") =>
  myPlanContent[lang === "ar" ? "ar" : "en"];
