export const pricingContent = {
  en: {
    header: "Flexible pricing for every builder",
    subheader:
      "Choose the full Madar platform, or subscribe only to the builder you need.",
    platformTab: "Full platform plans",
    buildersTab: "Individual builders",
    popular: "Most popular",
    perMonth: "/ month",
    getStarted: "Get started",
    chooseBuilder: "Choose builder",
    galleryHint: "Tap a builder to preview its plan",
    previous: "Previous",
    next: "Next",
    saving: "Saving...",
    success: "Checkout request saved. Payment setup is not connected yet.",
    loginRequired: "Please log in before choosing a plan.",
    failed: "Could not start checkout.",
    serverError: "Could not connect to server.",
    plans: [
      {
        id: "starter",
        name: "Starter",
        price: "$9",
        desc: "Launch a simple website, collect form data, and manage basic reservations.",
        badge: "Website + forms",
        features: [
          { text: "1 website project", included: true },
          { text: "Page builder", included: true },
          { text: "Basic form builder", included: true },
          { text: "Reservation block", included: true },
          { text: "Responses dashboard", included: true },
          { text: "Up to 3 users", included: true },
          { text: "Data workspace", included: false },
          { text: "Advanced reports", included: false },
          { text: "API integrations", included: false },
        ],
      },
      {
        id: "pro",
        name: "Pro",
        price: "$29",
        desc: "Build operational workflows with forms, quizzes, reports, and analysis.",
        badge: "Best value",
        features: [
          { text: "Everything in Starter", included: true },
          { text: "Advanced form builder", included: true },
          { text: "Quiz builder", included: true },
          { text: "Reservation management", included: true },
          { text: "Data workspace", included: true },
          { text: "Spreadsheet upload", included: true },
          { text: "Report builder", included: true },
          { text: "Roles and permissions", included: true },
          { text: "API access", included: true },
        ],
        popular: true,
      },
      {
        id: "business",
        name: "Business",
        price: "$79",
        desc: "For teams that need higher limits, permissions, workflows, and integrations.",
        badge: "For teams",
        features: [
          { text: "Everything in Pro", included: true },
          { text: "Unlimited users", included: true },
          { text: "Advanced workflows", included: true },
          { text: "Advanced analytics", included: true },
          { text: "Custom reports", included: true },
          { text: "Custom domain", included: true },
          { text: "White-label option", included: true },
          { text: "Priority support", included: true },
          { text: "Custom integrations", included: true },
        ],
      },
    ],
    builders: [
      {
        id: "website",
        icon: "●",
        name: "Website Builder",
        price: "$15",
        desc: "Build responsive pages, sections, elements, templates, and branded sites.",
        badge: "Pages",
        features: [
          { text: "Page builder", included: true },
          { text: "Sections and layouts", included: true },
          { text: "Elements and carousels", included: true },
          { text: "Header and footer editor", included: true },
          { text: "Responsive preview", included: true },
          { text: "Forms and data tools", included: false },
        ],
      },
      {
        id: "forms",
        icon: "▣",
        name: "Form Builder",
        price: "$9",
        desc: "Create forms, collect submissions, and review responses from one workspace.",
        badge: "Forms",
        features: [
          { text: "Unlimited forms", included: true },
          { text: "Field builder", included: true },
          { text: "Required fields", included: true },
          { text: "Responses dashboard", included: true },
          { text: "Export results", included: true },
          { text: "Advanced analysis", included: false },
        ],
      },
      {
        id: "quiz",
        icon: "✓",
        name: "Quiz Builder",
        price: "$9",
        desc: "Create quizzes with scoring, answer keys, timers, and pass/fail results.",
        badge: "Quizzes",
        features: [
          { text: "Question builder", included: true },
          { text: "Correct answer keys", included: true },
          { text: "Automatic scoring", included: true },
          { text: "Manual review mode", included: true },
          { text: "Timers and retakes", included: true },
          { text: "Advanced reports", included: false },
        ],
        popular: true,
      },
      {
        id: "reservation",
        icon: "◇",
        name: "Reservation Builder",
        price: "$9",
        desc: "Accept appointment, service, consultation, or table reservation requests.",
        badge: "Bookings",
        features: [
          { text: "Service selector", included: true },
          { text: "Date and time fields", included: true },
          { text: "Guest count", included: true },
          { text: "Notes and requests", included: true },
          { text: "Reservation submissions", included: true },
          { text: "Advanced workflows", included: false },
        ],
      },
      {
        id: "reports",
        icon: "□",
        name: "Report Builder",
        price: "$19",
        desc: "Generate finance, operations, and monitoring reports from your data.",
        badge: "Reports",
        features: [
          { text: "Report templates", included: true },
          { text: "Finance reports", included: true },
          { text: "Operations reports", included: true },
          { text: "NGO / MEAL reports", included: true },
          { text: "Data preview", included: true },
          { text: "API integrations", included: false },
        ],
      },
      {
        id: "data",
        icon: "◉",
        name: "Data Workspace",
        price: "$29",
        desc: "Import, clean, inspect, and analyze data from forms, spreadsheets, and APIs.",
        badge: "Analysis",
        features: [
          { text: "Website form data import", included: true },
          { text: "CSV / XLS / XLSX upload", included: true },
          { text: "External link / API import", included: true },
          { text: "Data cleaning", included: true },
          { text: "Backend analysis", included: true },
          { text: "Custom integrations", included: false },
        ],
      },
    ],
  },

  ar: {
    header: "تسعير مرن لكل منشئ",
    subheader:
      "اختر منصة مدار الكاملة، أو اشترك فقط في المنشئ الذي تحتاجه.",
    platformTab: "خطط المنصة الكاملة",
    buildersTab: "المنشئات الفردية",
    popular: "الأكثر شيوعاً",
    perMonth: "/ شهر",
    getStarted: "ابدأ الآن",
    chooseBuilder: "اختر المنشئ",
    galleryHint: "اضغط على منشئ لمعاينة خطته",
    previous: "السابق",
    next: "التالي",
    saving: "جارٍ الحفظ...",
    success: "تم حفظ طلب الدفع. إعداد الدفع غير متصل بعد.",
    loginRequired: "يرجى تسجيل الدخول قبل اختيار خطة.",
    failed: "تعذر بدء الدفع.",
    serverError: "تعذر الاتصال بالخادم.",
    plans: [
      {
        id: "starter",
        name: "المبتدئ",
        price: "$9",
        desc: "أطلق موقعاً بسيطاً، واجمع بيانات النماذج، وأدر الحجوزات الأساسية.",
        badge: "موقع + نماذج",
        features: [
          { text: "مشروع موقع واحد", included: true },
          { text: "منشئ صفحات", included: true },
          { text: "منشئ نماذج أساسي", included: true },
          { text: "كتلة حجوزات", included: true },
          { text: "لوحة الردود", included: true },
          { text: "حتى 3 مستخدمين", included: true },
          { text: "مساحة البيانات", included: false },
          { text: "تقارير متقدمة", included: false },
          { text: "تكاملات API", included: false },
        ],
      },
      {
        id: "pro",
        name: "الاحترافية",
        price: "$29",
        desc: "ابنِ تدفقات عمل تشغيلية مع النماذج والاختبارات والتقارير والتحليل.",
        badge: "أفضل قيمة",
        features: [
          { text: "كل ميزات المبتدئ", included: true },
          { text: "منشئ نماذج متقدم", included: true },
          { text: "منشئ اختبارات", included: true },
          { text: "إدارة الحجوزات", included: true },
          { text: "مساحة البيانات", included: true },
          { text: "رفع الجداول", included: true },
          { text: "منشئ التقارير", included: true },
          { text: "الأدوار والصلاحيات", included: true },
          { text: "وصول API", included: true },
        ],
        popular: true,
      },
      {
        id: "business",
        name: "الأعمال",
        price: "$79",
        desc: "للفرق التي تحتاج حدوداً أعلى وصلاحيات وتدفقات عمل وتكاملات.",
        badge: "للفرق",
        features: [
          { text: "كل ميزات الاحترافية", included: true },
          { text: "مستخدمون غير محدودين", included: true },
          { text: "تدفقات عمل متقدمة", included: true },
          { text: "تحليلات متقدمة", included: true },
          { text: "تقارير مخصصة", included: true },
          { text: "نطاق مخصص", included: true },
          { text: "خيار العلامة البيضاء", included: true },
          { text: "دعم بأولوية", included: true },
          { text: "تكاملات مخصصة", included: true },
        ],
      },
    ],
    builders: [
      {
        id: "website",
        icon: "●",
        name: "منشئ المواقع",
        price: "$15",
        desc: "أنشئ صفحات متجاوبة، وأقساماً، وعناصر، وقوالب، ومواقع بعلامتك التجارية.",
        badge: "صفحات",
        features: [
          { text: "منشئ صفحات", included: true },
          { text: "أقسام وتخطيطات", included: true },
          { text: "عناصر وشرائح", included: true },
          { text: "محرر الرأس والتذييل", included: true },
          { text: "معاينة متجاوبة", included: true },
          { text: "النماذج وأدوات البيانات", included: false },
        ],
      },
      {
        id: "forms",
        icon: "▣",
        name: "منشئ النماذج",
        price: "$9",
        desc: "أنشئ نماذج، واجمع الردود، وراجع النتائج من مساحة واحدة.",
        badge: "نماذج",
        features: [
          { text: "نماذج غير محدودة", included: true },
          { text: "منشئ الحقول", included: true },
          { text: "حقول مطلوبة", included: true },
          { text: "لوحة الردود", included: true },
          { text: "تصدير النتائج", included: true },
          { text: "تحليل متقدم", included: false },
        ],
      },
      {
        id: "quiz",
        icon: "✓",
        name: "منشئ الاختبارات",
        price: "$9",
        desc: "أنشئ اختبارات مع التصحيح، ومفاتيح الإجابة، والمؤقتات، ونتائج النجاح والفشل.",
        badge: "اختبارات",
        features: [
          { text: "منشئ أسئلة", included: true },
          { text: "مفاتيح الإجابات", included: true },
          { text: "تصحيح تلقائي", included: true },
          { text: "مراجعة يدوية", included: true },
          { text: "مؤقتات وإعادة محاولات", included: true },
          { text: "تقارير متقدمة", included: false },
        ],
        popular: true,
      },
      {
        id: "reservation",
        icon: "◇",
        name: "منشئ الحجوزات",
        price: "$9",
        desc: "استقبل طلبات المواعيد أو الخدمات أو الاستشارات أو حجوزات الطاولات.",
        badge: "حجوزات",
        features: [
          { text: "اختيار الخدمة", included: true },
          { text: "حقول التاريخ والوقت", included: true },
          { text: "عدد الضيوف", included: true },
          { text: "ملاحظات وطلبات", included: true },
          { text: "ردود الحجوزات", included: true },
          { text: "تدفقات عمل متقدمة", included: false },
        ],
      },
      {
        id: "reports",
        icon: "□",
        name: "منشئ التقارير",
        price: "$19",
        desc: "أنشئ تقارير مالية وتشغيلية وتقارير متابعة من بياناتك.",
        badge: "تقارير",
        features: [
          { text: "قوالب تقارير", included: true },
          { text: "تقارير مالية", included: true },
          { text: "تقارير تشغيلية", included: true },
          { text: "تقارير متابعة وتقييم", included: true },
          { text: "معاينة البيانات", included: true },
          { text: "تكاملات API", included: false },
        ],
      },
      {
        id: "data",
        icon: "◉",
        name: "مساحة البيانات",
        price: "$29",
        desc: "استورد ونظف وراجع وحلل البيانات من النماذج والجداول وواجهات API.",
        badge: "تحليل",
        features: [
          { text: "استيراد بيانات النماذج", included: true },
          { text: "رفع CSV / XLS / XLSX", included: true },
          { text: "استيراد من رابط أو API", included: true },
          { text: "تنظيف البيانات", included: true },
          { text: "تحليل عبر الخادم", included: true },
          { text: "تكاملات مخصصة", included: false },
        ],
      },
    ],
  },
};

export const getPricingContent = (lang = "en") =>
  pricingContent[lang === "ar" ? "ar" : "en"];
