export const pricingContent = {
  en: {
    eyebrow: "Plans and pricing",
    title: "Choose the Madar plan that fits your work",
    subtitle: "Forms, websites, data tools, and reservations with clear monthly pricing.",
    manualActivation: "Plans are manually reviewed and activated. Requesting a plan does not charge you.",
    loading: "Loading current plans...",
    catalogError: "Current pricing is temporarily unavailable.",
    requestError: "Could not save your plan request.",
    requestSaved: "Your plan request was saved for manual review. No payment was taken.",
    requestPlan: "Request this plan",
    saving: "Saving...",
    perMonth: "/month",
    hostedStorage: "Madar-hosted storage",
    oneOperator: "1 workspace operator",
    addonsTitle: "Optional add-ons",
    comingSoon: "Coming soon",
    back: "Back",
    fairUse: "Forms, submissions, and reservation requests are not billed by count. Fair-use, anti-abuse, security, payload, rate, and platform-stability controls still apply.",
    addressNote: "Website plans include one standard madarportal.com/site/business-name address. A branded business-name.madarportal.com subdomain is $5/month.",
    exclusions: "Customer-owned custom domains and hosted business email are not currently available. AI analytics is an optional token-based add-on.",
    plans: {
      forms: {
        name: "Forms",
        summary: "For public forms, responses, and standard data analysis.",
      },
      website: {
        name: "Website",
        summary: "For a visual website with forms and image uploads.",
      },
      business: {
        name: "Business",
        summary: "For a website with expanded data tools.",
      },
      business_plus: {
        name: "Business Plus",
        summary: "For service businesses managing reservations and schedules.",
      },
    },
    featureLabels: {
      unlimited_forms_submissions: "Unlimited forms and submissions",
      hosted_public_form_links: "Hosted public form links",
      response_management_overview: "Response management and overview",
      data_import_standard_analysis: "Data import and standard analysis",
      visual_page_builder: "Visual page builder",
      one_published_website: "1 published website",
      standard_hosted_address: "Standard hosted address",
      image_uploads_response_management: "Image uploads and response management",
      everything_website: "Everything in Website",
      expanded_analytics: "Expanded analytics tools",
      data_cleaning: "Data cleaning",
      charts_data_exports: "Charts and data exports",
      everything_business: "Everything in Business",
      unlimited_reservation_requests: "Unlimited reservation requests",
      reservation_management_analytics: "Reservation management and analytics",
      internal_calendar: "Internal calendar",
      priority_support: "Priority support designation",
    },
    addons: {},
  },
  ar: {
    eyebrow: "الخطط والأسعار",
    title: "اختر خطة مدار المناسبة لعملك",
    subtitle: "نماذج ومواقع وأدوات بيانات وحجوزات بأسعار شهرية واضحة.",
    manualActivation: "تتم مراجعة الخطط وتفعيلها يدوياً. طلب الخطة لا يؤدي إلى تحصيل أي مبلغ.",
    loading: "جارٍ تحميل الخطط الحالية...",
    catalogError: "الأسعار الحالية غير متاحة مؤقتاً.",
    requestError: "تعذر حفظ طلب الخطة.",
    requestSaved: "تم حفظ طلب خطتك للمراجعة اليدوية. لم يتم تحصيل أي مبلغ.",
    requestPlan: "طلب هذه الخطة",
    saving: "جارٍ الحفظ...",
    perMonth: "/شهرياً",
    hostedStorage: "تخزين مستضاف لدى مدار",
    oneOperator: "مشغّل واحد لمساحة العمل",
    addonsTitle: "إضافات اختيارية",
    comingSoon: "قريباً",
    back: "رجوع",
    fairUse: "لا تتم محاسبة النماذج أو الردود أو طلبات الحجز حسب العدد. تبقى ضوابط الاستخدام العادل ومكافحة الإساءة والأمان ومعدلات الطلبات سارية.",
    addressNote: "تشمل خطط المواقع عنواناً قياسياً على madarportal.com/site/business-name. النطاق الفرعي business-name.madarportal.com متاح مقابل 5 دولارات شهرياً.",
    exclusions: "النطاقات المملوكة للعملاء والبريد التجاري المستضاف غير متاحة حالياً. تحليلات الذكاء الاصطناعي إضافة اختيارية تعتمد على الرموز.",
    plans: {
      forms: {
        name: "النماذج",
        summary: "للنماذج العامة وإدارة الردود وتحليل البيانات القياسي.",
      },
      website: {
        name: "الموقع",
        summary: "لموقع مرئي مع النماذج ورفع الصور.",
      },
      business: {
        name: "الأعمال",
        summary: "لموقع مع أدوات بيانات موسعة.",
      },
      business_plus: {
        name: "الأعمال بلس",
        summary: "للأعمال الخدمية التي تدير الحجوزات والجداول.",
      },
    },
    featureLabels: {
      unlimited_forms_submissions: "نماذج وردود غير محدودة",
      hosted_public_form_links: "روابط نماذج عامة مستضافة",
      response_management_overview: "إدارة الردود ونظرة عامة",
      data_import_standard_analysis: "استيراد البيانات والتحليل القياسي",
      visual_page_builder: "منشئ صفحات مرئي",
      one_published_website: "موقع منشور واحد",
      standard_hosted_address: "عنوان استضافة قياسي",
      image_uploads_response_management: "رفع الصور وإدارة الردود",
      everything_website: "كل ما في خطة الموقع",
      expanded_analytics: "أدوات تحليل موسعة",
      data_cleaning: "تنظيف البيانات",
      charts_data_exports: "رسوم بيانية وتصدير البيانات",
      everything_business: "كل ما في خطة الأعمال",
      unlimited_reservation_requests: "طلبات حجز غير محدودة",
      reservation_management_analytics: "إدارة وتحليل الحجوزات",
      internal_calendar: "تقويم داخلي",
      priority_support: "تصنيف دعم ذو أولوية",
    },
    addons: {},
  },
};

export const getPricingContent = (lang = "en") =>
  pricingContent[lang === "ar" ? "ar" : "en"];
