#!/usr/bin/env python3
"""Start and verify isolated Supabase; never link, push or reset a hosted database."""

import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
from urllib.parse import urlencode, urlsplit
from urllib.request import Request, urlopen

WEB_ROOT = Path(__file__).resolve().parents[1]
CLI_VERSION = "2.119.0"


def run(command, *, capture=False):
    return subprocess.run(command, cwd=WEB_ROOT, check=True, text=True,
                          stdout=subprocess.PIPE if capture else None).stdout


def require_loopback(value, name):
    if urlsplit(value).hostname not in {"localhost", "127.0.0.1", "::1"}:
        raise RuntimeError(f"Refusing non-local {name}")
    return value


def verify_database(api_url, service_key, target):
    def read(resource, query):
        request = Request(f"{api_url.rstrip('/')}/rest/v1/{resource}?{urlencode(query)}",
                          headers={"apikey": service_key, "Authorization": f"Bearer {service_key}"})
        with urlopen(request, timeout=15) as response:
            return json.load(response)

    rows = read("application_schema_state", {"select": "schema_version", "contract_key": "eq.core"})
    if rows != [{"schema_version": target}]:
        raise RuntimeError(f"Local schema does not match target {target}; configuration was not written")
    for table in ("elearning_settings", "elearning_courses", "elearning_groups", "elearning_instructors", "elearning_sections", "elearning_lessons", "elearning_learners", "elearning_enrollments", "elearning_lesson_completions"):
        read(table, {"select": "tenant_id", "limit": "1"})


def write_environment(status):
    api_url = require_loopback(status["API_URL"], "API URL")
    db_url = require_loopback(status["DB_URL"], "database URL")
    anon_key, service_key = status["ANON_KEY"], status["SERVICE_ROLE_KEY"]
    if not anon_key or not service_key or anon_key == service_key:
        raise RuntimeError("Local Supabase keys are missing or identical")
    target = json.loads((WEB_ROOT / "deployment/releases/release.json").read_text())["schema"]["target"]
    verify_database(api_url, service_key, target)
    values = {
        "APP_ENV": "development", "MADAR_ENV_OVERRIDE": "false",
        "SUPABASE_URL": api_url, "SUPABASE_DB_URL": db_url,
        "SUPABASE_ANON_KEY": anon_key, "SUPABASE_SERVICE_KEY": service_key,
        "FRONTEND_URLS": "http://localhost:5173,http://127.0.0.1:5173,http://localhost:3001,http://127.0.0.1:3001",
        "FRONTEND_PRIMARY_URL": "http://127.0.0.1:5173", "PUBLIC_API_URL": "http://127.0.0.1:8000",
        "COOKIE_SECURE": "false", "COOKIE_SAMESITE": "lax",
        "RATE_LIMIT_ENABLED": "true", "RATE_LIMIT_FAIL_OPEN": "true",
    }
    destination = WEB_ROOT / ".env.database.local"
    # Retain explicitly configured local test-account settings across restarts.
    if destination.is_file():
        for line in destination.read_text().splitlines():
            key, separator, value = line.partition("=")
            if separator and key in {"MADAR_TEST_EMAIL", "MADAR_TEST_PASSWORD", "MADAR_TEST_AUTO_LOGIN"}:
                values[key] = json.loads(value)
    # The generated file contains only local settings and local Supabase keys.
    # Never copy hosted credentials from web/.env.
    with tempfile.NamedTemporaryFile(mode="w", dir=WEB_ROOT, delete=False) as temporary:
        temporary.write("# Generated by scripts/start_local_database.py; local development only.\n")
        for key, value in values.items():
            temporary.write(f"{key}={json.dumps(value)}\n")
        temporary_path = Path(temporary.name)
    try:
        temporary_path.chmod(0o600)
        temporary_path.replace(destination)
    finally:
        temporary_path.unlink(missing_ok=True)
    print(f"Local schema {target} and E-Learning tables verified. Wrote {destination.name} (mode 0600).")


def main():
    if not shutil.which("docker"):
        raise RuntimeError("Docker is missing. Install Docker Engine, then rerun this command.")
    endpoint = os.getenv("DOCKER_HOST") or run(
        ["docker", "context", "inspect", "--format", "{{.Endpoints.docker.Host}}"], capture=True).strip()
    if not endpoint.startswith("unix://"):
        raise RuntimeError("A local Unix-socket Docker engine is required; remote Docker is refused")
    run(["docker", "info", "--format", "{{.ServerVersion}}"], capture=True)
    if not shutil.which("npx"):
        raise RuntimeError("Node.js/npx is required for the pinned Supabase CLI")
    for check in ("check_dependency_locks.py", "check_migrations.py", "check_migration_transitions.py", "check_forward_release.py", "check_secret_hygiene.py"):
        run([sys.executable, str(WEB_ROOT / "scripts" / check)])
    cli = ["npx", "--yes", f"supabase@{CLI_VERSION}", "--workdir", str(WEB_ROOT)]
    # Capture CLI output: start/status can display database passwords and keys.
    run(cli + ["start"], capture=True)
    # --local is explicit, even if this checkout has a linked hosted project.
    # Existing data is retained and only pending migrations are applied.
    run(cli + ["migration", "up", "--local"])
    status = json.loads(run(cli + ["status", "--output", "json"], capture=True))
    write_environment(status)
    print("Start the API: cd web/backend && python run_local.py --local-db")
    print("Create a separate local account through the app; production users/data are not copied.")


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, KeyError, ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f"Local database setup failed: {type(error).__name__}: {error}", file=sys.stderr)
        sys.exit(1)
