// Local-only API --local-db --local-commerce, existing test account, Chrome and Vite.
const {chromium,expect}=require('../frontend/node_modules/@playwright/test');
const fs=require('node:fs');
const origin='http://127.0.0.1:5173',out='docs/verification/elearning-credentials';
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();
 const fixture={tenant_id:3,user_id:1,courses:[],templates:[],plans:[],checkouts:[],credentials:[]};let settings,profile;const errors=[];
 const manifest=()=>fs.writeFileSync('/tmp/madar-credential-browser-fixtures.json',JSON.stringify(fixture,null,2));
 page.on('pageerror',error=>errors.push(error.message));await page.addInitScript(()=>{if(!localStorage.getItem('madar.language'))localStorage.setItem('madar.language','en');});
 async function raw(path,data,method='GET'){const cookies=await context.cookies();return context.request.fetch(origin+'/api'+path,{method,headers:{Origin:origin,'X-CSRF-Token':cookies.find(c=>c.name==='madar_csrf_token')?.value||''},...(data?{data}:{})});}
 async function api(path,data,method='GET'){const response=await raw(path,data,method);if(!response.ok())throw Error(method+' '+path+' '+response.status()+' '+await response.text());return response.json();}
 try{
 await page.goto(origin+'/dashboard');await expect(page.getByRole('button',{name:'E-Learning',exact:true})).toBeVisible();
 settings=(await api('/elearning/settings')).settings;await api('/elearning/settings',{...settings,enabled:true,sequential_progression:false},'PUT');
 const user=(await api('/users/1/info'));profile=user.user||user;fixture.profile={first_name:profile.first_name,last_name:profile.last_name};manifest();
 const course=(await api('/elearning/courses',{name:'Credential Verification '+Date.now(),description:'Local credential verification',status:'published',access_type:'paid'},'POST')).course;fixture.courses.push(course.id);manifest();
 let structure=await api(`/elearning/courses/${course.id}/structure/commands`,{action:'create_section',expected_revision:1,payload:{name:'First section',status:'published'}},'POST');
 structure=await api(`/elearning/courses/${course.id}/structure/commands`,{action:'create_lesson',expected_revision:structure.revision,payload:{section_id:structure.sections[0].id,name:'Credential lesson',status:'published'}},'POST');const lesson=structure.sections[0].lessons[0];
 await api(`/elearning/courses/${course.id}/lessons/${lesson.id}/content/commands`,{action:'create',expected_revision:1,payload:{type:'text',content:{version:1,body:'Complete this lesson and the required final assessment to earn a certificate.'}}},'POST');
 await api(`/elearning/courses/${course.id}/enrollments/users`,{user_ids:[1],access_source:'manual'},'POST');
 await page.getByRole('button',{name:'E-Learning',exact:true}).click();await page.locator('#dashboard-sidebar-elearning').getByRole('link',{name:'Courses',exact:true}).click();
 await page.locator('.elearning-course-card').filter({has:page.getByRole('heading',{name:course.name,exact:true})}).getByRole('link',{name:'Manage',exact:true}).click();await page.getByRole('link',{name:'Certificate',exact:true}).click();
 await page.getByRole('button',{name:'+ Create Template',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('Template name',{exact:true}).fill('Credential Test '+Date.now());await dialog.getByLabel('Issuer / organization name',{exact:true}).fill('Test Academy');await dialog.getByLabel('Body text',{exact:true}).fill('{{learner_name}} has successfully completed {{course_name}}.');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 let config=await api(`/elearning/courses/${course.id}/certificate`);const template=config.templates[0];fixture.templates.push(template.id);manifest();await page.getByLabel('Issue certificate',{exact:true}).check();await page.getByRole('combobox',{name:'Certificate template',exact:true}).selectOption(template.id);await page.getByRole('button',{name:'Save',exact:true}).click();await expect.poll(async()=> (await api(`/elearning/courses/${course.id}/certificate`)).configuration.enabled).toBe(true);console.log('Admin certificate route:',page.url());await page.screenshot({path:out+'/admin-config.png',fullPage:true});
 await page.getByRole('link',{name:'Assessments',exact:true}).click();await page.getByRole('button',{name:'+ Add Assessment',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByLabel('Assessment Title',{exact:true}).fill('Required Final Check');await dialog.getByLabel(/Required for .* Completion/).check();await dialog.getByRole('button',{name:'True / False',exact:true}).click();await dialog.getByLabel('Question',{exact:true}).fill('This statement is true.');await dialog.getByRole('button',{name:'Save',exact:true}).click();await dialog.getByRole('combobox',{name:'Status',exact:true}).selectOption('published');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await page.locator('#dashboard-sidebar-elearning').getByRole('link',{name:'My Learning',exact:true}).click();await page.locator('.elearning-course-card').filter({has:page.getByRole('heading',{name:course.name,exact:true})}).getByRole('link',{name:'Continue Learning',exact:true}).click();await page.getByRole('button',{name:'Mark Complete',exact:true}).click();await expect(page.locator('.elearning-player-progress')).toContainText('100%');await expect(page.getByText('Course Not Completed',{exact:true})).toBeVisible();expect((await api('/elearning/my-certificates')).credentials.filter(row=>row.course_id===course.id)).toHaveLength(0);await page.screenshot({path:out+'/100-percent-no-certificate.png',fullPage:true});
 await page.getByRole('link',{name:'Required Final Check',exact:true}).click();await page.getByRole('button',{name:'Start Assessment',exact:true}).click();await page.getByLabel('True',{exact:true}).check();await page.getByRole('button',{name:'Submit Assessment',exact:true}).click();await expect(page.getByText(/^Course Completed/)).toBeVisible();await expect(page.getByRole('link',{name:'View Certificate',exact:true})).toBeVisible();let rows=(await api('/elearning/my-certificates')).credentials.filter(row=>row.course_id===course.id);expect(rows).toHaveLength(1);const credential=rows[0];fixture.credentials.push(credential.id);manifest();const original=await api('/elearning/my-certificates/'+credential.id);const completedAt=(await api(`/elearning/my-learning/courses/${course.id}`)).progress.completed_at;
 await page.reload();await expect(page.getByRole('link',{name:'View Certificate',exact:true})).toBeVisible();expect((await api('/elearning/my-certificates')).credentials.filter(row=>row.course_id===course.id)).toHaveLength(1);await page.getByRole('link',{name:'View Certificate',exact:true}).click();await expect(page.locator('.elearning-certificate-document')).toContainText('Certificate of Completion');await expect(page.locator('.elearning-certificate-document')).toContainText(course.name);console.log('Learner certificate route:',page.url());await page.screenshot({path:out+'/learner-certificate.png',fullPage:true});
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download PDF',exact:true}).click();const download=await downloadPromise;await download.saveAs(out+'/certificate.pdf');expect(fs.readFileSync(out+'/certificate.pdf').subarray(0,4).toString()).toBe('%PDF');
 await page.locator('#dashboard-sidebar-elearning').getByRole('link',{name:'My Certificates',exact:true}).click();await expect(page.locator('.elearning-certificate-grid')).toContainText(course.name);console.log('My Certificates route:',page.url());await page.screenshot({path:out+'/my-certificates.png',fullPage:true});
 const publicContext=await browser.newContext({viewport:{width:1000,height:800}}),publicPage=await publicContext.newPage();await publicPage.addInitScript(()=>{if(!localStorage.getItem('madar.language'))localStorage.setItem('madar.language','en');});await publicPage.goto(original.verification_url);await expect(publicPage.getByRole('heading',{name:'Valid Credential',exact:true})).toBeVisible();expect(await publicContext.cookies()).not.toContainEqual(expect.objectContaining({name:'access_token'}));await expect(publicPage.getByRole('navigation')).toHaveCount(0);console.log('Public verification route:',publicPage.url());await publicPage.screenshot({path:out+'/public-valid.png',fullPage:true});
 const publicResponse=await publicContext.request.get(origin+'/api/verify/credential/'+original.verification_url.split('/').at(-1));expect(Object.keys((await publicResponse.json()).credential).sort()).toEqual(['completed_at','course_name','credential_number','issued_at','issuer_name','learner_name','status'].sort());await publicContext.clearCookies();expect((await publicContext.request.get(origin+'/api/elearning/my-certificates/'+credential.id+'?pdf=true')).status()).toBe(401);
 // Changes to live names/template cannot alter the issued snapshot.
 const latest=(await api('/elearning/courses/'+course.id)).course;await api('/elearning/courses/'+course.id,{name:'Renamed after issuance',description:latest.description,cover_asset:latest.cover_asset,status:'published',access_type:'paid',expected_revision:latest.revision},'PUT');await api('/users/1/profile',{first_name:'Changed',last_name:'After issuance'},'PUT');await api('/elearning/certificate-templates/'+template.id,{design:{...template.design,title:'Changed template title'},expected_revision:template.revision,status:'active'},'PUT');expect(await api('/elearning/my-certificates/'+credential.id)).toEqual(original);
 // Commerce uses the existing local adapter; earned history survives expiration/refund.
 const planPayload={name:'Credential temporary monthly access',description:'Local credential verification',status:'active',billing_type:'monthly',amount:'5.00',currency:'USD',access_scope:'single_course',course_ids:[course.id]};const plans=await api('/elearning/plans',planPayload,'POST');const plan=plans.saved_plan_id;fixture.plans.push(plan);manifest();const checkout=(await api('/elearning/checkout',{offering_id:plan,course_id:course.id,idempotency_key:require('node:crypto').randomUUID()},'POST')).checkout;fixture.checkouts.push(checkout.id);manifest();for(const state of ['paid','expired','refunded']){await api(`/elearning/checkout/${checkout.id}/local-event`,{state},'POST');expect((await api('/elearning/my-certificates/'+credential.id)).status).toBe('active');}
 const enrollment=(await api(`/elearning/my-learning/courses/${course.id}`)).progress.id;
 await api(`/elearning/courses/${course.id}/enrollments/${enrollment}/status`,{action:'suspend',expected_status:'active',confirmed:true},'POST');
 expect((await raw(`/elearning/my-learning/courses/${course.id}`)).status()).toBeGreaterThanOrEqual(400);expect((await api('/elearning/my-certificates/'+credential.id)).status).toBe('active');
 await api(`/elearning/courses/${course.id}/enrollments/${enrollment}/status`,{action:'reactivate',expected_status:'suspended'},'POST');
 await page.goto(origin+`/e-learning/courses/${course.id}/certificate`);await page.getByRole('button',{name:'Revoke',exact:true}).click();dialog=page.getByRole('dialog');await expect(dialog).toContainText('completion will remain intact');await dialog.getByLabel('Revocation reason',{exact:true}).fill('Local verification revocation');await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect((await api(`/elearning/my-learning/courses/${course.id}`)).progress.completed_at).toBe(completedAt);await publicPage.reload();await expect(publicPage.getByRole('heading',{name:'Credential Revoked',exact:true})).toBeVisible();await publicPage.screenshot({path:out+'/public-revoked.png',fullPage:true});await page.screenshot({path:out+'/admin-revoked.png',fullPage:true});
 const current=(await api('/elearning/courses/'+course.id)).course;await api(`/elearning/courses/${course.id}/archive`,{expected_revision:current.revision},'POST');expect((await api('/elearning/my-certificates/'+credential.id)).status).toBe('revoked');await publicPage.reload();await expect(publicPage.getByRole('heading',{name:'Credential Revoked',exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});await page.goto(origin+`/e-learning/courses/${course.id}/certificate`);await expect(page.getByRole('heading',{name:'Course Certificate',exact:true})).toBeVisible();expect(await page.locator('main.elearning-management').evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true);await page.screenshot({path:out+'/admin-mobile.png',fullPage:true});
 await page.evaluate(()=>localStorage.setItem('madar.language','ar'));await page.goto(origin+'/my-learning/certificates/'+credential.id);await expect(page.locator('main.elearning-player')).toHaveAttribute('dir','rtl');await expect(page.locator('.elearning-certificate-document')).toBeVisible();expect(await page.locator('main.elearning-player').evaluate(element=>element.scrollWidth<=element.clientWidth+1)).toBe(true);await page.screenshot({path:out+'/learner-rtl-mobile.png',fullPage:true});
 await publicPage.setViewportSize({width:390,height:844});await publicPage.getByRole('button',{name:'العربية / English'}).click();await expect(publicPage.getByRole('main')).toHaveAttribute('dir','rtl');await publicPage.screenshot({path:out+'/public-rtl-mobile.png',fullPage:true});await publicPage.goto(origin+'/verify/credential/'+'a'.repeat(64));await expect(publicPage.getByRole('heading',{name:'الشهادة غير موجودة',exact:true})).toBeVisible();await publicContext.close();
 // Arabic PDF renders through exactly the same private endpoint with template overrides.
 console.log('Browser assertions passed: formal event issuance, uniqueness, immutable snapshots, PDF, public verification/revocation, commerce independence, archive, mobile/RTL.');expect(errors).toEqual([]);
 fs.writeFileSync(out+'/browser-results.json',JSON.stringify({routes:{admin:`/e-learning/courses/${course.id}/certificate`,learner:`/my-learning/certificates/${credential.id}`,list:'/my-learning/certificates',public:new URL(original.verification_url).pathname},credential_number:credential.credential_number,completed_at:completedAt,errors},null,2));
 }finally{if(settings)await api('/elearning/settings',settings,'PUT');if(fixture.profile?.first_name!==undefined)await api('/users/1/profile',fixture.profile,'PUT');manifest();await browser.close();}
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
