const {chromium,expect}=require('../frontend/node_modules/@playwright/test');const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),origin='http://127.0.0.1:5173',out='docs/verification/elearning-credentials';const path='/tmp/madar-credential-browser-fixtures.json',fixture=JSON.parse(fs.readFileSync(path));let profile;
 const manifest=()=>fs.writeFileSync(path,JSON.stringify(fixture,null,2));await page.addInitScript(()=>localStorage.setItem('madar.language','ar'));
 async function api(path,data,method='GET'){const cookies=await context.cookies(),response=await context.request.fetch(origin+'/api'+path,{method,headers:{Origin:origin,'X-CSRF-Token':cookies.find(cookie=>cookie.name==='madar_csrf_token')?.value||''},...(data?{data}:{})});if(!response.ok())throw Error(method+' '+path+' '+response.status()+' '+await response.text());return response.json();}
 try{await page.goto(origin+'/dashboard');await expect(page.getByRole('button',{name:'التعلم الإلكتروني',exact:true})).toBeVisible();profile=(await api('/users/1/info')).user;await api('/users/1/profile',{first_name:'محمد',last_name:'أحمد'},'PUT');
 const course=(await api('/elearning/courses',{name:'دورة التعلم العربية',description:'Local credential verification',status:'published',access_type:'private'},'POST')).course;fixture.courses.push(course.id);fixture.arabic_course=course.id;manifest();let structure=await api(`/elearning/courses/${course.id}/structure/commands`,{action:'create_section',expected_revision:1,payload:{name:'المستوى الأول',status:'published'}},'POST');structure=await api(`/elearning/courses/${course.id}/structure/commands`,{action:'create_lesson',expected_revision:structure.revision,payload:{section_id:structure.sections[0].id,name:'الدرس الأول',status:'published'}},'POST');fixture.arabic_lesson=structure.sections[0].lessons[0].id;manifest();await api(`/elearning/courses/${course.id}/enrollments/users`,{user_ids:[1],access_source:'manual'},'POST');
 await page.goto(origin+`/e-learning/courses/${course.id}/certificate`);await page.getByRole('button',{name:'+ إنشاء قالب',exact:true}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('اسم القالب',{exact:true}).fill('Credential Test Arabic '+Date.now());await dialog.getByLabel('عنوان الشهادة',{exact:true}).fill('شهادة إتمام');await dialog.getByLabel('جهة الإصدار / اسم المؤسسة',{exact:true}).fill('أكاديمية الاختبار');await dialog.getByLabel('نص الشهادة',{exact:true}).fill('أتم المتعلم {{learner_name}} جميع متطلبات {{course_name}} بنجاح.');await dialog.getByLabel('اسم الموقّع (اختياري)',{exact:true}).fill('مدير الأكاديمية');await dialog.getByRole('button',{name:'حفظ',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);const data=await api(`/elearning/courses/${course.id}/certificate`),template=data.templates.find(t=>t.design.name.startsWith('Credential Test Arabic'));fixture.templates.push(template.id);manifest();await page.getByLabel('إصدار شهادة',{exact:true}).check();await page.getByRole('combobox',{name:'قالب الشهادة',exact:true}).selectOption(template.id);await page.getByRole('button',{name:'حفظ',exact:true}).click();await expect.poll(async()=> (await api(`/elearning/courses/${course.id}/certificate`)).configuration.enabled).toBe(true);await page.screenshot({path:out+'/admin-rtl-mobile.png',fullPage:true});
 await api(`/elearning/my-learning/courses/${course.id}/lessons/${fixture.arabic_lesson}/completion`,{},'POST');const credential=(await api('/elearning/my-certificates')).credentials.find(row=>row.course_id===course.id);expect(credential).toBeTruthy();fixture.credentials.push(credential.id);fixture.arabic_credential=credential.id;manifest();await page.goto(origin+'/my-learning/certificates/'+credential.id);await expect(page.locator('.elearning-certificate-document')).toContainText('محمد أحمد');await expect(page.locator('.elearning-certificate-document')).toContainText('شهادة إتمام');await expect(page.locator('main.elearning-player')).toHaveAttribute('dir','rtl');await page.screenshot({path:out+'/arabic-certificate-mobile.png',fullPage:true});const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'تنزيل PDF',exact:true}).click();await (await downloadPromise).saveAs(out+'/arabic-certificate.pdf');const snapshot=await api('/elearning/my-certificates/'+credential.id);fixture.arabic_verification_url=snapshot.verification_url;manifest();console.log('Arabic certificate rendered and downloaded:',page.url());
 }finally{if(profile)await api('/users/1/profile',{first_name:profile.first_name,last_name:profile.last_name},'PUT');manifest();await browser.close();}
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
