// Uses the exact temporary courses from verify_academy_ux_browser.cjs and the existing owner identity.
const {chromium,expect}=require('../frontend/node_modules/@playwright/test');
const fs=require('node:fs'),fixture=JSON.parse(fs.readFileSync('/tmp/madar-academy131-browser-fixtures.json'));
const origin='http://127.0.0.1:5173',out='docs/verification/academy-ux';
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{if(!localStorage.getItem('madar.language'))localStorage.setItem('madar.language','en');});
 async function raw(path,data,method='GET'){const cookies=await context.cookies();return context.request.fetch(origin+'/api'+path,{method,headers:{Origin:origin,'X-CSRF-Token':cookies.find(c=>c.name==='madar_csrf_token')?.value||''},...(data?{data}:{})});}
 async function api(path,data,method='GET'){const r=await raw(path,data,method);if(!r.ok())throw Error(method+' '+path+' '+r.status()+' '+await r.text());return r.json();}
 let settings;
 try{
  await page.goto(origin+'/e-learning/settings/academy');await expect(page.getByRole('link',{name:'Open Student Platform',exact:true})).toBeVisible();settings=(await api('/elearning/settings')).settings;
  await api('/elearning/settings',{...settings,enabled:true,academy_enabled:true,sequential_progression:true,assessments_enabled:true,section_label:'Level',lesson_label:'Topic'},'PUT');
  const c=fixture.named.paid,root=`/elearning/my-learning/courses/${c.id}`,admin=`/elearning/courses/${c.id}/assessments`;
  const structure=(await api(`/elearning/courses/${c.id}/structure`)),section=structure.sections[0],listing=await api(admin+`?section_id=${section.id}`);
  if(!listing.placements.some(p=>p.assessment.title==='Local Level Review'))await api(admin,{expected_revision:listing.revision,section_id:section.id,assessment:{title:'Local Level Review',status:'published',required_for_completion:false},questions:[{type:'true_false',prompt:'Learning can be resumed.',config:{correct_answer:true}}]},'POST');
  const placement=(await api(admin+`?section_id=${section.id}`)).placements.find(p=>p.assessment.title==='Local Level Review'),pid=placement.placement_id||placement.block_id||placement.id;
  await page.getByRole('link',{name:'Open Student Platform',exact:true}).click();await expect(page.locator('.learning-shell-sidebar')).toBeVisible();expect(await page.locator('.admin-sidebar').count()).toBe(0);
  await page.getByRole('link',{name:c.name,exact:true}).click();await expect(page.locator('.elearning-player-outline')).toBeVisible();await expect(page.locator('.elearning-player-outline')).toContainText('Local Level Review');
  expect((await raw(root+`/lessons/${c.lessons[1].id}`)).status()).toBe(403);await expect(page.locator('.elearning-player-outline').getByRole('link',{name:'Topic 2',exact:true})).toHaveCount(0);await page.screenshot({path:out+'/course-locked-assessment.png',fullPage:true});
  await page.locator('.elearning-player-outline').getByRole('link',{name:'Topic 1',exact:true}).click();await page.getByRole('button',{name:'Mark Complete',exact:true}).click();await expect(page.locator('.elearning-player-outline').getByRole('link',{name:'Topic 2',exact:true})).toBeVisible();await expect.poll(async()=>(await api(root)).progress.progress_percent).toBe(50);
  await page.locator('.elearning-player-outline').getByRole('link',{name:'Topic 2',exact:true}).click();await page.getByRole('button',{name:'Mark Complete',exact:true}).click();await expect(page.locator('.elearning-player-outline').getByRole('link',{name:'Local Level Review',exact:true}).first()).toBeVisible();await page.reload();await expect.poll(async()=>(await api(root)).progress.progress_percent).toBe(100);await page.locator('.elearning-player-outline').getByRole('link',{name:'Local Level Review',exact:true}).first().click();await expect(page.getByRole('button',{name:'Start Assessment',exact:true})).toBeVisible();await page.screenshot({path:out+'/course-unlocked-assessment.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>localStorage.setItem('madar.language','ar'));await page.goto(origin+`/my-learning/courses/${c.id}/assessments/${pid}`);await expect(page.locator('.learning-shell')).toHaveAttribute('dir','rtl');await page.locator('.elearning-outline-toggle').click();await expect(page.getByRole('dialog')).toBeVisible();expect(await page.getByRole('dialog').evaluate(e=>e.contains(document.activeElement))).toBe(true);await page.screenshot({path:out+'/course-rtl-mobile-outline.png',fullPage:true});await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await page.goto(origin+'/e-learning/settings/academy');await expect(page.locator('.academy-management-hub')).toHaveAttribute('dir','rtl');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:out+'/academy-hub-rtl-mobile.png',fullPage:true});expect(errors).toEqual([]);
  fs.writeFileSync(out+'/learning-results.json',JSON.stringify({course:c.id,assessment:pid,route:`/my-learning/courses/${c.id}/assessments/${pid}`,checks:'real owner identity; fixed learner shell; desktop outline; sequential URL lock enforced by backend; explicit completion unlocks next Topic and section assessment; 50%/100% progress persisted; Level/Topic terminology; assessment runtime; Arabic mobile outline focus/Escape; hub RTL/mobile without overflow',errors},null,2));console.log('Academy learning workspace browser verification passed.');
 }catch(e){await page.screenshot({path:out+'/learning-failure.png',fullPage:true});console.error(await page.locator('body').innerText());throw e;}finally{if(settings)await api('/elearning/settings',settings,'PUT');await browser.close();}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
