// Local-only: start the API with run_local.py --local-db and Vite on 127.0.0.1:5173.
// Media fixture JSON supplies user_id, tenant_id and authorized audio/video {id,url}.
const {chromium,expect}=require('../frontend/node_modules/@playwright/test');
const fixtures=require(process.env.MADAR_ASSESSMENT_MEDIA_FIXTURES || '/tmp/madar-player-media.json');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const errors=[];let settings,course,lessons=[],block;const origin='http://127.0.0.1:5173';
 page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('madar.language','en'));
 async function raw(path,data,method='GET'){const cookies=await context.cookies();return context.request.fetch(origin+'/api'+path,{method,headers:{Origin:origin,'X-CSRF-Token':cookies.find(c=>c.name==='madar_csrf_token')?.value||''},...(data?{data}:{})});}
 async function api(path,data,method='GET'){const r=await raw(path,data,method);if(!r.ok())throw Error(method+' '+path+' HTTP '+r.status()+' '+await r.text());return r.json();}
 const safe=data=>{const value=JSON.stringify(data);for(const key of ['correct_option_id','correct_answer','correct_pairs','admin_label','private_snapshot','HIDDEN AUDIO ANSWER'])expect(value).not.toContain(key);};
 try{
  await page.goto(origin+'/dashboard');await expect(page.getByRole('button',{name:'E-Learning',exact:true})).toBeVisible();
  settings=(await api('/elearning/settings')).settings;await api('/elearning/settings',{...settings,sequential_progression:true},'PUT');
  course=(await api('/elearning/courses',{name:'Assessment Verification '+Date.now(),status:'published',access_type:'private'},'POST')).course;
  let structure=await api(`/elearning/courses/${course.id}/structure/commands`,{action:'create_section',expected_revision:1,payload:{name:'Foundations',status:'published'}},'POST');
  for(const name of ['Assessment practice','Next lesson']) structure=await api(`/elearning/courses/${course.id}/structure/commands`,{action:'create_lesson',expected_revision:structure.revision,payload:{name,status:'published',section_id:structure.sections[0].id}},'POST');
  lessons=structure.sections[0].lessons;const content=`/elearning/courses/${course.id}/lessons/${lessons[0].id}/content`;const author=`/elearning/courses/${course.id}/lessons/${lessons[0].id}/assessments`;const learner=`/elearning/my-learning/courses/${course.id}/lessons/${lessons[0].id}`;
  let revision=1;for(const type of ['text','audio','video']){const payload=type==='text'?{type,title:'Welcome',content:{body:'Read, listen, practice, and watch.'}}:{type,title:type==='audio'?'Listen':'Watch',media_id:fixtures[type].id,content:{caption:'Learning example'}};revision=(await api(content+'/commands',{action:'create',expected_revision:revision,payload},'POST')).revision;}
  await api(`/elearning/courses/${course.id}/enrollments/users`,{user_ids:[fixtures.user_id],access_source:'manual'},'POST');
  await page.getByRole('button',{name:'E-Learning',exact:true}).click();await page.locator('#dashboard-sidebar-elearning').getByRole('link',{name:'Courses',exact:true}).click();
  await page.locator('.elearning-course-card').filter({has:page.getByRole('heading',{name:course.name,exact:true})}).getByRole('link',{name:'Manage',exact:true}).click();await page.getByRole('link',{name:'Structure',exact:true}).click();
  await page.getByRole('link',{name:'Assessment practice',exact:true}).click();await expect(page.getByRole('heading',{name:'Lesson Builder',exact:true})).toBeVisible();console.log('Admin route:',page.url());
  await page.getByRole('button',{name:'Add Block',exact:true}).click();await page.getByRole('button',{name:'Assessment',exact:true}).click();let dialog=page.getByRole('dialog');await expect(dialog.getByText('No questions yet. Add your first question.')).toBeVisible();
  await dialog.getByLabel('Assessment Title',{exact:true}).fill('Practice Check');await dialog.getByLabel('Maximum Attempts',{exact:true}).fill('3');await dialog.getByLabel(/Required for .* Completion/).check();
  for(const type of ['Multiple Choice','True / False','Matching','Listen & Match']){
   await dialog.getByRole('button',{name:type,exact:true}).click();await dialog.getByLabel('Question',{exact:true}).fill(type+' practice');
   if(type==='Multiple Choice'){await dialog.getByLabel('Option 1',{exact:true}).fill('Correct choice');await dialog.getByLabel('Option 2',{exact:true}).fill('Other choice');}
   if(type==='Matching'||type==='Listen & Match')for(let i=1;i<=2;i++){
    await dialog.getByLabel('Matching Target '+i,{exact:true}).fill('Target '+i);
    if(type==='Matching')await dialog.getByLabel('Left Item '+i,{exact:true}).fill('Left '+i);
    else{await dialog.getByRole('combobox',{name:new RegExp('^Audio '+i)}).selectOption(fixtures.audio.id);await dialog.getByLabel('Admin label (hidden from learners)',{exact:true}).nth(i-1).fill('HIDDEN AUDIO ANSWER '+i);}
   }
   await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(dialog.getByRole('heading',{name:new RegExp(type.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+' practice')})).toBeVisible();
  }
  // Move listening above matching, edit one question, duplicate then remove the extra.
  await dialog.locator('li').last().getByRole('button',{name:'Move Up',exact:true}).click();
  await dialog.locator('li').first().getByRole('button',{name:'Edit',exact:true}).click();await dialog.getByLabel('Question',{exact:true}).fill('Choose the correct answer');await dialog.getByRole('button',{name:'Save',exact:true}).click();
  await dialog.locator('li').first().getByRole('button',{name:'Duplicate',exact:true}).click();await expect(dialog.locator('li')).toHaveCount(5);await dialog.locator('li').nth(1).getByRole('button',{name:'Delete Permanently',exact:true}).click();await dialog.getByRole('button',{name:'Confirm',exact:true}).click();await expect(dialog.locator('li')).toHaveCount(4);
  await dialog.getByRole('combobox',{name:/^Status/}).selectOption('published');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
  let snapshot=await api(content);block=snapshot.blocks.find(b=>b.type==='assessment');expect(block).toBeTruthy();
  await api(content+'/commands',{action:'reorder',entity_id:block.id,expected_revision:snapshot.revision,payload:{direction:'up'}},'POST');await page.reload();await expect(page.locator('.elearning-block-card')).toHaveCount(4);
  await page.getByRole('button',{name:/^Preview /}).click();await expect(page.getByRole('dialog').getByText('Question 1: Choose the correct answer')).toBeVisible();await expect(page.getByRole('dialog').locator('audio')).toHaveCount(3);await page.screenshot({path:'/tmp/madar-assessment-admin-preview.png',fullPage:true});await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
  await page.locator('#dashboard-sidebar-elearning').getByRole('link',{name:'My Learning',exact:true}).click();const card=page.locator('.elearning-course-card').filter({has:page.getByRole('heading',{name:course.name,exact:true})});await card.getByRole('link',{name:'Continue Learning',exact:true}).click();await expect(page.getByRole('button',{name:'Start Assessment',exact:true})).toBeVisible();console.log('Learner route:',page.url());
  expect((await api(learner)).blocks.map(b=>b.type)).toEqual(['text','audio','assessment','video']);safe(await api(learner+'/assessments/'+block.id));await expect(page.getByRole('button',{name:'Mark Complete',exact:true})).toBeDisabled();expect((await raw(learner+'/completion',null,'POST')).status()).toBe(403);
  await page.getByRole('button',{name:'Start Assessment',exact:true}).click();await expect(page.getByText('Question 1: Choose the correct answer')).toBeVisible();safe(await api(learner+'/assessments/'+block.id));
  let definition=await api(author+'/'+block.id);
  async function answer(wrong){
   for(const q of definition.questions.filter(q=>!q.archived_at)){
    const field=page.locator('fieldset').filter({has:page.getByText(new RegExp('^Question \\d+: '+q.prompt.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$'))});
    if(q.type==='multiple_choice')await field.getByLabel(wrong?'Other choice':'Correct choice',{exact:true}).check();else if(q.type==='true_false')await field.getByLabel(wrong?'False':'True',{exact:true}).check();else{const targets=q.config.prompts.map(p=>q.config.correct_pairs[p.id]);for(let i=0;i<targets.length;i++)await field.locator('select').nth(i).selectOption(targets[(i+(wrong?1:0))%targets.length]);}
   }
  }
  for(const kind of ['audio','video']){const player=page.locator(kind).first();await expect.poll(()=>player.evaluate(e=>e.readyState)).toBeGreaterThan(0);await player.evaluate(async e=>{try{await e.play();}catch(e){if(e.name!=='AbortError')throw e;}});await expect.poll(()=>player.evaluate(e=>e.currentTime)).toBeGreaterThan(0);await player.evaluate(e=>e.pause());}
  await answer(true);await page.getByRole('button',{name:'Submit Assessment',exact:true}).click();await expect(page.getByText('Score: 0% — Not Passed',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Mark Complete',exact:true})).toBeDisabled();safe(await api(learner+'/assessments/'+block.id));await page.screenshot({path:'/tmp/madar-assessment-failed.png',fullPage:true});
  await page.getByRole('button',{name:'Try Again',exact:true}).click();await expect(page.getByText('Question 1: Choose the correct answer')).toBeVisible();await answer(false);await page.getByRole('button',{name:'Submit Assessment',exact:true}).click();await expect(page.getByText('Score: 100% — Passed',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Mark Complete',exact:true})).toBeEnabled();safe(await api(learner+'/assessments/'+block.id));
  await page.getByRole('button',{name:'Mark Complete',exact:true}).click();await expect(page.locator('.elearning-player-progress')).toContainText('50%');await page.reload();await expect(page.getByText('Score: 100% — Passed',{exact:true})).toBeVisible();await expect(page.locator('.elearning-player-progress')).toContainText('50%');await expect(page.locator('.elearning-player-lesson-actions').getByRole('link',{name:/^Next /})).toBeVisible();await page.screenshot({path:'/tmp/madar-assessment-passed.png',fullPage:true});
  await page.locator('.elearning-player-lesson-actions').getByRole('link',{name:/^Next /}).click();await expect(page.getByRole('heading',{name:'Next lesson',exact:true})).toBeVisible();await page.getByRole('link',{name:course.name,exact:true}).click();await page.getByRole('link',{name:'Continue Learning',exact:true}).click();await expect(page.getByRole('heading',{name:'Next lesson',exact:true})).toBeVisible();
  const report=await api(`/elearning/courses/${course.id}/progress`);const result=report.enrollments.find(e=>e.user_id===fixtures.user_id).assessment_results[0];expect(result.attempts).toBe(2);expect(result.best_score).toBe(100);expect(result.passed).toBe(true);
  await page.locator('#dashboard-sidebar-elearning').getByRole('link',{name:'Courses',exact:true}).click();await page.locator('.elearning-course-card').filter({has:page.getByRole('heading',{name:course.name,exact:true})}).getByRole('link',{name:'Manage',exact:true}).click();await page.getByRole('link',{name:'Progress',exact:true}).click();await page.getByRole('button',{name:/view progress/i}).first().click();await expect(page.getByRole('dialog')).toContainText('Practice Check');await expect(page.getByRole('dialog')).toContainText('Attempts: 2');console.log('Admin report route:',page.url());await page.screenshot({path:'/tmp/madar-assessment-admin-results.png',fullPage:true});
  const rtl=await context.newPage();await rtl.addInitScript(()=>localStorage.setItem('madar.language','ar'));await rtl.setViewportSize({width:390,height:844});await rtl.goto(origin+`/my-learning/courses/${course.id}/lessons/${lessons[0].id}`);await expect(rtl.locator('.elearning-player')).toHaveAttribute('dir','rtl');await expect(rtl.locator('.assessment-runtime')).toContainText('100%');expect(await rtl.locator('.elearning-player').evaluate(e=>e.scrollWidth>e.clientWidth+1)).toBe(false);await rtl.getByRole('button',{name:'المحاولة مجددًا',exact:true}).click();await expect(rtl.locator('fieldset')).toHaveCount(4);await expect(rtl.locator('fieldset select')).toHaveCount(4);for(const audio of await rtl.locator('fieldset audio').all()){await expect.poll(()=>audio.evaluate(e=>e.readyState)).toBeGreaterThan(0);await audio.evaluate(async e=>{try{await e.play();}catch(error){if(error.name!=='AbortError')throw error;}});await expect.poll(()=>audio.evaluate(e=>e.currentTime)).toBeGreaterThan(0);await audio.evaluate(e=>e.pause());}expect(await rtl.locator('.elearning-player').evaluate(e=>e.scrollWidth>e.clientWidth+1)).toBe(false);await rtl.screenshot({path:'/tmp/madar-assessment-rtl-mobile.png',fullPage:true});await rtl.close();
  expect(errors).toEqual([]);console.log('PASS: normal admin/learner flow; four question types; preview; edit/duplicate/reorder/delete; fail→pass→explicit complete→50% report; refresh; no answer keys; audio/video playback; mobile RTL. Existing authorized media used; no upload override.');
 }catch(error){console.log('Page',page.url(),await page.locator('[role=alert]').allTextContents());await page.screenshot({path:'/tmp/madar-assessment-error.png',fullPage:true});throw error;}
 finally{try{if(course){const latest=(await api('/elearning/courses/'+course.id)).course;await api('/elearning/courses/'+course.id,{expected_revision:latest.revision,expected_structure_revision:latest.structure_revision,confirmation_name:course.name,confirmed:true},'DELETE');}if(settings)await api('/elearning/settings',settings,'PUT');}finally{await browser.close();}console.log('Temporary course/content/enrollment/attempts removed; original settings restored.');}
})().catch(e=>{console.error(e.stack);process.exitCode=1});
