// Local only: native API --local-db, local test account, Vite on 127.0.0.1:5173.
// Fixture JSON supplies user_id and tenant_id; no uploads or production calls.
const{chromium,expect}=require('../frontend/node_modules/@playwright/test');
const fixtures=require(process.env.MADAR_PLACEMENT_MEDIA_FIXTURES || '/tmp/madar-player-media.json');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();const origin='http://127.0.0.1:5173';let course,group,settings,sections,lessons=[],sectionPlacement,finalPlacement;const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('madar.language','en'));
 async function raw(path,data,method='GET'){const cookies=await context.cookies();return context.request.fetch(origin+'/api'+path,{method,headers:{Origin:origin,'X-CSRF-Token':cookies.find(c=>c.name==='madar_csrf_token')?.value||''},...(data?{data}:{})});}
 async function api(path,data,method='GET'){const r=await raw(path,data,method);if(!r.ok())throw Error(method+' '+path+' '+r.status()+' '+await r.text());return r.json();}
 const learner=()=>`/elearning/my-learning/courses/${course.id}`;
 try{
  await page.goto(origin+'/dashboard');await expect(page.getByRole('button',{name:'E-Learning',exact:true})).toBeVisible();settings=(await api('/elearning/settings')).settings;await api('/elearning/settings',{...settings,sequential_progression:true},'PUT');
  course=(await api('/elearning/courses',{name:'English Communication — Placement Verification '+Date.now(),status:'published',access_type:'private'},'POST')).course;
  let structure={revision:1};for(const name of ['Section 1','Section 2'])structure=await api(`/elearning/courses/${course.id}/structure/commands`,{action:'create_section',expected_revision:structure.revision,payload:{name,status:'published'}},'POST');sections=structure.sections;
  for(let s=0;s<2;s++)for(let l=1;l<=2;l++)structure=await api(`/elearning/courses/${course.id}/structure/commands`,{action:'create_lesson',expected_revision:structure.revision,payload:{section_id:sections[s].id,name:`Section ${s+1} Lesson ${l}`,status:'published'}},'POST');sections=structure.sections;lessons=sections.flatMap(s=>s.lessons);
  group=(await api('/elearning/groups',{name:'Placement Verification '+Date.now(),status:'active'},'POST')).item;
  await api(`/elearning/relationships/group/${group.id}/commands`,{action:'add_members',user_ids:[fixtures.user_id]},'POST');await api(`/elearning/relationships/group/${group.id}/commands`,{action:'assign_course',target_id:course.id},'POST');
  await page.getByRole('button',{name:'E-Learning',exact:true}).click();await page.locator('#dashboard-sidebar-elearning').getByRole('link',{name:'Courses',exact:true}).click();await page.locator('.elearning-course-card').filter({has:page.getByRole('heading',{name:course.name,exact:true})}).getByRole('link',{name:'Manage',exact:true}).click();await page.getByRole('link',{name:'Structure',exact:true}).click();await page.locator('.elearning-section-card').first().getByRole('button',{name:/Assessments/}).click();
  async function build(title){
   await page.getByRole('button',{name:'+ Add Assessment',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('heading',{name:'Assessment Builder',exact:true})).toBeVisible();await dialog.getByLabel('Assessment Title',{exact:true}).fill(title);await dialog.getByLabel('Maximum Attempts',{exact:true}).fill('3');await dialog.getByLabel(/Required for .* Completion/).check();await dialog.getByRole('button',{name:'True / False',exact:true}).click();await dialog.getByLabel('Question',{exact:true}).fill('This statement is true.');await dialog.getByRole('button',{name:'Save',exact:true}).click();await dialog.getByRole('combobox',{name:'Status',exact:true}).selectOption('published');await dialog.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.assessment-placement-card').getByRole('heading',{name:title,exact:true})).toBeVisible();
  }
  await build('Section 1 Check');sectionPlacement=(await api(`/elearning/courses/${course.id}/assessments?section_id=${sections[0].id}`)).placements[0];console.log('Admin section route:',page.url());await page.screenshot({path:'/tmp/madar-placement-section-admin.png',fullPage:true});await page.getByRole('link',{name:'Assessments',exact:true}).click();await build('Course Final Check');finalPlacement=(await api(`/elearning/courses/${course.id}/assessments`)).placements[0];await page.reload();await expect(page.locator('.assessment-placement-card')).toContainText('Course Final Check');console.log('Admin course assessment route:',page.url());await page.screenshot({path:'/tmp/madar-placement-course-admin.png',fullPage:true});
  expect((await raw(learner()+`/assessments/${sectionPlacement.id}/attempts`,{},'POST')).status()).toBe(403);expect((await raw(learner()+`/assessments/${finalPlacement.id}`,null,'GET')).status()).toBe(403);expect((await raw(learner()+`/lessons/${lessons[2].id}`)).status()).toBe(403);
  await page.locator('#dashboard-sidebar-elearning').getByRole('link',{name:'My Learning',exact:true}).click();await page.locator('.elearning-course-card').filter({has:page.getByRole('heading',{name:course.name,exact:true})}).getByRole('link',{name:'Continue Learning',exact:true}).click();
  for(let i=0;i<2;i++){await expect(page.getByRole('heading',{name:lessons[i].name,exact:true})).toBeVisible();await page.getByRole('button',{name:'Mark Complete',exact:true}).click();if(i===0)await page.locator('.elearning-player-lesson-actions').getByRole('link',{name:/^Next /}).click();}
  let snapshot=await api(learner());expect(snapshot.sections[0].completion.completed).toBe(false);expect(snapshot.sections[1].lessons.every(l=>l.locked)).toBe(true);await page.getByRole('link',{name:'Section 1 Check',exact:true}).click();await expect(page.getByRole('button',{name:'Start Assessment',exact:true})).toBeVisible();console.log('Learner section assessment route:',page.url());
  async function answer(passed){await page.getByLabel(passed?'True':'False',{exact:true}).check();await page.getByRole('button',{name:'Submit Assessment',exact:true}).click();await expect(page.getByText(passed?'Score: 100% — Passed':'Score: 0% — Not Passed',{exact:true})).toBeVisible();}
  await page.getByRole('button',{name:'Start Assessment',exact:true}).click();await answer(false);snapshot=await api(learner());expect(snapshot.sections[0].completion.completed).toBe(false);expect(snapshot.sections[1].lessons[0].locked).toBe(true);await page.getByRole('button',{name:'Try Again',exact:true}).click();await answer(true);snapshot=await api(learner());expect(snapshot.sections[0].completion.completed).toBe(true);expect(snapshot.sections[1].lessons[0].locked).toBe(false);await page.screenshot({path:'/tmp/madar-placement-section-passed.png',fullPage:true});
  await page.getByRole('link',{name:lessons[2].name,exact:true}).click();await page.getByRole('button',{name:'Mark Complete',exact:true}).click();await page.locator('.elearning-player-lesson-actions').getByRole('link',{name:/^Next /}).click();await page.getByRole('button',{name:'Mark Complete',exact:true}).click();await expect(page.locator('.elearning-player-progress')).toContainText('100%');await expect(page.getByText('Course Not Completed',{exact:true})).toBeVisible();snapshot=await api(learner());expect(snapshot.progress.completion.completed).toBe(false);expect(snapshot.progress.progress_status).toBe('active');await page.screenshot({path:'/tmp/madar-placement-100-incomplete.png',fullPage:true});
  await page.getByRole('link',{name:'Course Final Check',exact:true}).click();await page.getByRole('button',{name:'Start Assessment',exact:true}).click();await answer(false);expect((await api(learner())).progress.completion.completed).toBe(false);await page.getByRole('button',{name:'Try Again',exact:true}).click();await answer(true);await expect(page.getByText(/^Course Completed/)).toBeVisible();console.log('Learner final route:',page.url());snapshot=await api(learner());expect(snapshot.progress.completion.completed).toBe(true);const completedAt=snapshot.progress.completion.completed_at,completionId=snapshot.progress.completion.completion_id;expect(completedAt).toBeTruthy();await page.reload();await expect(page.getByText(/^Course Completed/)).toBeVisible();expect((await api(learner())).progress.completion.completed_at).toBe(completedAt);await page.screenshot({path:'/tmp/madar-placement-formal-completed.png',fullPage:true});
  const report=await api(`/elearning/courses/${course.id}/progress`),record=report.enrollments.find(e=>e.user_id===fixtures.user_id);expect(record.access_sources.map(g=>g.type)).toEqual(['group']);expect(record.assessment_results.find(a=>a.placement_type==='section').passed).toBe(true);expect(record.assessment_results.find(a=>a.placement_type==='course').passed).toBe(true);
  await page.locator('#dashboard-sidebar-elearning').getByRole('link',{name:'Courses',exact:true}).click();await page.locator('.elearning-course-card').filter({has:page.getByRole('heading',{name:course.name,exact:true})}).getByRole('link',{name:'Manage',exact:true}).click();await page.getByRole('link',{name:'Progress',exact:true}).click();await page.getByRole('button',{name:/view progress/i}).first().click();await expect(page.getByRole('dialog')).toContainText('Section 1 Check');await expect(page.getByRole('dialog')).toContainText('Course Final Check');await expect(page.getByRole('dialog')).toContainText('Course Completed');await page.screenshot({path:'/tmp/madar-placement-progress.png',fullPage:true});
  await api(`/elearning/courses/${course.id}/enrollments/${record.id}/status`,{action:'suspend',expected_status:'active',confirmed:true},'POST');expect((await raw(learner()+`/assessments/${finalPlacement.id}`)).status()).toBe(404);await api(`/elearning/courses/${course.id}/enrollments/${record.id}/status`,{action:'reactivate',expected_status:'suspended',confirmed:false},'POST');expect((await api(learner())).progress.completion.completion_id).toBe(completionId);
  const rtl=await context.newPage();await rtl.addInitScript(()=>localStorage.setItem('madar.language','ar'));await rtl.setViewportSize({width:390,height:844});await rtl.goto(origin+`/my-learning/courses/${course.id}/assessments/${finalPlacement.id}`);await expect(rtl.locator('.elearning-player')).toHaveAttribute('dir','rtl');await expect(rtl.locator('.assessment-runtime')).toContainText('100%');expect(await rtl.locator('.elearning-player').evaluate(e=>e.scrollWidth>e.clientWidth+1)).toBe(false);await rtl.screenshot({path:'/tmp/madar-placement-rtl-mobile.png',fullPage:true});await rtl.close();expect(errors).toEqual([]);console.log('PASS: Section/Course shared builders; Group-only access; locked URL denial; section fail→retry→pass→next section; 100% lesson progress remains incomplete; final fail→pass→formal timestamp; refresh; admin results; suspension; Arabic mobile RTL.');
 }catch(e){console.log('Page',page.url(),await page.locator('[role=alert]').allTextContents());await page.screenshot({path:'/tmp/madar-placement-error.png',fullPage:true});throw e;}
 finally{try{if(course){const latest=(await api('/elearning/courses/'+course.id)).course;await api('/elearning/courses/'+course.id,{expected_revision:latest.revision,expected_structure_revision:latest.structure_revision,confirmation_name:course.name,confirmed:true},'DELETE');}if(group){await api(`/elearning/groups/${group.id}/archive`,{expected_revision:group.revision},'POST');}if(settings)await api('/elearning/settings',settings,'PUT');}finally{await browser.close();}console.log('Temporary course, placements, completion evidence and attempts cleaned; settings restored.');}
})().catch(e=>{console.error(e.stack);process.exitCode=1});
