import { useEffect, useState } from "react";
import { Link, NavLink, useParams } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { Search } from "lucide-react";
import { fetchRelationships, changeRelationship, fetchRelationshipCandidates } from "../../services/elearningRelationships";
import { useELearningTerminology } from "../../hooks/useELearningTerminology";
import ELearningSkeleton, { ELearningProgressSkeleton } from "./ELearningSkeleton";
import ELearningDialog from "./ELearningDialog";
import LoadingBar from "../common/LoadingBar";

function AssignmentPicker({ kind, title, existing, onSave, onClose, busy, multiple, saveError }) {
 const { t } = useTranslation("dashboard");
 const [query, setQuery] = useState(""); const [items, setItems] = useState([]); const [selected, setSelected] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [more, setMore] = useState(false); const [attempt, setAttempt] = useState(0);
 useEffect(() => { let active = true; const timer = setTimeout(() => { fetchRelationshipCandidates(kind, query).then((data) => { if (active) { setItems(data.items); setMore(data.has_more); } }).catch(() => { if (active) setError(true); }).finally(() => { if (active) setLoading(false); }); }, 200); return () => { active = false; clearTimeout(timer); }; }, [kind, query, attempt]);
 async function loadMore() { setLoading(true); try { const data = await fetchRelationshipCandidates(kind, query, items.length); setItems((current) => [...current, ...data.items]); setMore(data.has_more); } catch { setError(true); } finally { setLoading(false); } }
 return <ELearningDialog title={title} busy={busy} onClose={onClose} closeLabel={t("elearning.courses.close")}><div className="elearning-enroll-form">
  <label className="ecommerce-search"><Search size={18} aria-hidden="true" /><input type="search" aria-label={t("elearning.assignments.search")} placeholder={t("elearning.assignments.search")} value={query} maxLength={120} disabled={busy} onChange={(e) => { setQuery(e.target.value); setSelected([]); setLoading(true); setError(false); }} /></label>
  {(error || saveError) && <p role="alert">{t("elearning.assignments.error")}<button onClick={() => { setError(false); setLoading(true); setAttempt((value) => value + 1); }}>{t("elearning.retry")}</button></p>}
  {loading && <LoadingBar mode="inline" label={t("elearning.loading")} />}
  <fieldset className="elearning-enroll-selection" disabled={busy || loading}><legend>{title}</legend>{items.map((item) => <label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} disabled={existing.includes(item.id) || (!selected.includes(item.id) && selected.length >= (multiple ? 100 : 1))} onChange={(e) => setSelected((current) => e.target.checked ? [...current, item.id] : current.filter((id) => id !== item.id))} /><span><strong>{item.name}</strong>{item.email && <small>{item.email}</small>}</span>{existing.includes(item.id) && <small>{t("elearning.assignments.assigned")}</small>}</label>)}{!items.length && !loading && <p>{t("elearning.assignments.emptyCandidates")}</p>}</fieldset>
  {more && <button className="ecommerce-secondary-button" disabled={loading || busy} onClick={loadMore}>{t("elearning.courses.loadMore")}</button>}
  <footer><button className="ecommerce-secondary-button" disabled={busy} onClick={onClose}>{t("elearning.courses.cancel")}</button><button className="ecommerce-primary-button" disabled={busy || loading || !selected.length} onClick={() => onSave(selected)}>{t("elearning.courses.save")}</button></footer>
 </div></ELearningDialog>;
}

export default function ELearningRelationshipsPage({ kind, course, selectedTab }) {
 const params = useParams(); const id = course?.id || params.itemId; const tab = selectedTab || params.tab || "overview";
 return <RelationshipWorkspace key={`${kind}:${id}`} kind={kind} id={id} tab={tab} embedded={!!course} />;
}

function RelationshipWorkspace({ kind, id, tab, embedded }) {
 const { t, i18n } = useTranslation("dashboard"); const { labels } = useELearningTerminology();
 const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [reload, setReload] = useState(0); const [picker, setPicker] = useState(null); const [confirmation, setConfirmation] = useState(null); const [query, setQuery] = useState(""); const [offset, setOffset] = useState(0); const [saved, setSaved] = useState(false);
 useEffect(() => { let active = true; const timer = setTimeout(() => { fetchRelationships(kind, id, query, offset).then((result) => { if (active) setData(result); }).catch((failure) => { if (active) setError(failure.status === 404 ? "unavailable" : "error"); }).finally(() => { if (active) setLoading(false); }); }, query ? 200 : 0); return () => { active = false; clearTimeout(timer); }; }, [kind, id, reload, query, offset]);
 async function run(command) { setBusy(true); setError(""); setSaved(false); try { const result = await changeRelationship(kind, id, command); setData(result); setPicker(null); setConfirmation(null); setSaved(true); if (query || offset) { setQuery(""); setOffset(0); } } catch { setError("error"); } finally { setBusy(false); } }
 const available = data && !["archived"].includes(data.entity.status);
 const tabs = kind === "group" ? ["overview", "members", "courses", "instructors"] : ["overview", "courses", "groups"];
 const base = `/e-learning/${kind === "group" ? "groups" : "instructors"}/${id}`;
 const section = (name, rows, candidate, action, remove) => <section className="ecommerce-list-card elearning-assignment-section"><header className="elearning-structure-header"><h2>{t("elearning.assignments.assignedLabels", { labels: labels.plural[name] })}</h2><button className="ecommerce-primary-button" disabled={busy || loading || !available} onClick={() => setPicker({ kind: candidate, action, title: t("elearning.assignments.assignLabel", { label: labels[name] }), existing: rows.map((row) => row.id) })}>{t("elearning.assignments.assignLabel", { label: labels[name] })}</button></header>{!rows.length && <p>{t("elearning.assignments.emptyAssigned")}</p>}{rows.map((row) => <div className="elearning-assignment-row" key={row.id}><div><Link to={`/e-learning/${candidate}/${row.id}`}>{row.name}</Link>{row.email && <p>{row.email}</p>}{row.learner_count !== undefined && <p>{t("elearning.assignments.groupProgress", { count: row.learner_count, average: row.average_progress, completed: row.completed_count })} <Link to={`/e-learning/courses/${row.id}/progress`}>{t("elearning.progress.view")}</Link></p>}{row.member_count !== undefined && <p>{t("elearning.assignments.membersCount", { count: row.member_count })}</p>}</div><button className="ecommerce-secondary-button" disabled={busy} onClick={() => setConfirmation({ action: remove, target_id: row.id, name: row.name })}>{t("elearning.assignments.removeLabel", { label: labels[name] })}</button></div>)}</section>;
 const content = <>
  {error && !confirmation && <p role="alert" className="elearning-feedback is-error">{t(`elearning.assignments.${error}`)} <button className="ecommerce-secondary-button" disabled={busy} onClick={() => { setError(""); setLoading(true); setReload((value) => value + 1); }}>{t("elearning.retry")}</button></p>}
  {saved && <p role="status" className="elearning-feedback">{t("elearning.assignments.saved")}</p>}
  {loading && data && <LoadingBar mode="inline" label={t("elearning.loading")} />}
  {data && <>
   {!embedded && <><Link className="ecommerce-secondary-button elearning-back-link" to={`/e-learning/${kind === "group" ? "groups" : "instructors"}`}>{t("elearning.assignments.back")}</Link><nav className="elearning-course-tabs">{tabs.map((value) => <NavLink className="ecommerce-secondary-button" key={value} to={`${base}/${value}`}>{t(value === "overview" ? "elearning.courses.tabs.overview" : `elearning.assignments.tabs.${value}`, { labels: labels.plural[value === "members" ? "group" : value.replace(/s$/, "")] })}</NavLink>)}</nav></>}
   {tab === "overview" && <section className="ecommerce-list-card elearning-course-overview"><h2>{data.entity.name}</h2><p>{data.entity.description}</p><span className={`elearning-course-status is-${data.entity.status}`}>{t(`elearning.directory.statuses.${data.entity.status}`)}</span><dl className="elearning-course-counts">{kind === "group" && <div><dt>{t("elearning.assignments.members")}</dt><dd>{data.member_count}</dd></div>}<div><dt>{labels.plural.course}</dt><dd>{data.courses.length}</dd></div><div><dt>{kind === "group" ? labels.plural.instructor : labels.plural.group}</dt><dd>{kind === "group" ? data.instructors.length : data.groups.length}</dd></div></dl>{kind === "instructor" && <><p>{data.entity.email}</p><p>{data.entity.user_id ? `${data.entity.user_name} (${data.entity.user_email})` : t("elearning.assignments.noLinkedUser")}</p><button className="ecommerce-secondary-button" disabled={busy || !available} onClick={() => setPicker({ kind: "users", action: "link_user", title: t("elearning.assignments.linkUser"), existing: [] })}>{t("elearning.assignments.linkUser")}</button></>}</section>}
   {kind === "group" && tab === "members" && <section className="ecommerce-list-card elearning-assignment-section"><header className="elearning-structure-header"><h2>{t("elearning.assignments.groupMembers", { label: labels.group })}</h2><button className="ecommerce-primary-button" disabled={busy || !available} onClick={() => setPicker({ kind: "users", action: "add_members", title: t("elearning.assignments.addMembers", { label: labels.group }), existing: data.members.map((member) => member.id) })}>{t("elearning.assignments.addMembers", { label: labels.group })}</button></header><input type="search" aria-label={t("elearning.assignments.searchMembers")} placeholder={t("elearning.assignments.searchMembers")} value={query} maxLength={120} onChange={(e) => { setQuery(e.target.value); setOffset(0); setLoading(true); }} />{!data.members.length && <p>{t("elearning.assignments.emptyMembers")}</p>}{data.members.map((member) => <div className="elearning-assignment-row" key={member.id}><div><strong>{member.name}</strong><p>{member.email}</p>{member.membership_status !== "active" && <span>{t("elearning.assignments.inactiveMember")}</span>}</div><button className="ecommerce-secondary-button" disabled={busy} onClick={() => setConfirmation({ action: "remove_member", user_ids: [member.id], name: member.name })}>{t("elearning.assignments.removeMember")}</button></div>)}<div className="elearning-content-toolbar">{offset > 0 && <button className="ecommerce-secondary-button" disabled={loading} onClick={() => { setOffset((current) => Math.max(current - 50, 0)); setLoading(true); }}>{t("elearning.assignments.previous")}</button>}{data.members_has_more && <button className="ecommerce-secondary-button" disabled={loading} onClick={() => { setOffset((current) => current + 50); setLoading(true); }}>{t("elearning.courses.loadMore")}</button>}</div></section>}
   {tab === "courses" && section("course", data.courses, "courses", "assign_course", "remove_course")}
   {tab === "groups" && section("group", data.groups, "groups", "assign_group", "remove_group")}
   {tab === "instructors" && section("instructor", data.instructors, "instructors", "assign_instructor", "remove_instructor")}
  </>}
  {picker && <AssignmentPicker {...picker} multiple={picker.action === "add_members"} saveError={error} busy={busy} onClose={() => setPicker(null)} onSave={(ids) => run(picker.kind === "users" ? { action: picker.action, user_ids: ids } : { action: picker.action, target_id: ids[0] })} />}
  {confirmation && <ELearningDialog title={t("elearning.assignments.confirmTitle", { name: confirmation.name })} closeLabel={t("elearning.courses.close")} busy={busy} onClose={() => setConfirmation(null)}>{error && <p role="alert">{t("elearning.assignments.error")}</p>}<p>{t(kind === "instructor" || confirmation.action === "remove_instructor" ? "elearning.assignments.instructorConfirm" : "elearning.assignments.confirmHelp")}</p><footer><button className="ecommerce-secondary-button" disabled={busy} onClick={() => setConfirmation(null)}>{t("elearning.courses.cancel")}</button><button className="ecommerce-primary-button" disabled={busy} onClick={() => { run({ action: confirmation.action, target_id: confirmation.target_id, user_ids: confirmation.user_ids, confirmed: true }); }}>{t("elearning.assignments.confirmRemove")}</button></footer></ELearningDialog>}
 </>;
 if (!data && loading) return embedded ? <ELearningProgressSkeleton label={t("elearning.loading")} /> : <ELearningSkeleton variant={kind === "group" ? "groups" : "instructors"} label={t("elearning.loading")} lang={i18n.language} direction={i18n.dir()} />;
 return embedded ? <div className="elearning-relationships">{content}</div> : <main className="ecommerce-page elearning-management" dir={i18n.dir()}><header className="ecommerce-page-header app-page-intro"><div><h1>{t(`elearning.navigation.${kind === "group" ? "groups" : "instructors"}`)}</h1><p>{data?.entity.name}</p></div></header>{content}</main>;
}
