import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useTranslation } from "react-i18next";
import ELearningSkeleton from "./ELearningSkeleton";
import { useELearningTerminology } from "../../hooks/useELearningTerminology";
import { uploadCourseCover } from "../../services/elearningCourses";
import { fetchCertificates, saveCertificateTemplate, configureCertificate, backfillCertificates, revokeCertificate, fetchCredential, downloadCredential, CERTIFICATE_VARIABLES, validatePlaceholders } from "../../services/elearningCredentials";
import "../../styles/admin/dashboard/elearning-certificates.css";

const date = (value, lang) => new Date(value).toLocaleDateString(lang);
function useCertificates(load, keys) {
  const [state, setState] = useState({ loading: true });
  const [revision, refresh] = useState(0);
  useEffect(() => {
    let active = true;
    load().then(data => { if (active) setState({ data }); }).catch(error => { if (active) setState({ error }); });
    return () => { active = false; };
    // Request identities are supplied by callers.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [...keys, revision]);
  return { ...state, update: data => setState({ data }), refresh: () => { setState({ loading: true }); refresh(x => x+1); } };
}
function Loading() { const { t, i18n } = useTranslation("dashboard"); return <ELearningSkeleton direction={i18n.dir()} lang={i18n.language} label={t("elearning.certificates.loading")} />; }
function Failure({ retry }) { const { t } = useTranslation("dashboard"); return <p role="alert">{t("elearning.certificates.error")} {retry && <button className="ecommerce-secondary-button" onClick={retry}>{t("elearning.retry")}</button>}</p>; }
function Dialog({ title, children, close }) {
  const ref = useRef(null);
  useEffect(() => { ref.current?.showModal(); }, []);
  return <dialog ref={ref} className="elearning-certificate-dialog" onCancel={close}><h2>{title}</h2>{children}</dialog>;
}
function Download({ id, course }) {
  const { t } = useTranslation("dashboard"); const [busy, setBusy] = useState(false); const [error, setError] = useState(false);
  return <><button className="ecommerce-secondary-button" disabled={busy} onClick={async () => { setBusy(true); setError(false); try { await downloadCredential(id, course); } catch { setError(true); } finally { setBusy(false); } }}>{t(`elearning.certificates.${busy ? "preparing" : "download"}`)}</button>{error && <Failure />}</>;
}
export function MyCertificates() {
  const { t, i18n } = useTranslation("dashboard"); const { labels } = useELearningTerminology();
  const state = useCertificates(() => fetchCertificates(), []);
  if (state.loading) return <Loading />;
  return <section><header className="app-page-intro"><h1>{t("elearning.certificates.myCertificates")}</h1><Link to="/my-learning">{t("elearning.player.myLearning")}</Link></header>{state.error ? <Failure retry={state.refresh} /> : !state.data.credentials.length ? <div className="ecommerce-list-card ecommerce-empty-state"><h2>{t("elearning.certificates.empty")}</h2><p>{t("elearning.certificates.emptyHelp", { course: labels.course })}</p></div> : <div className="elearning-certificate-grid">{state.data.credentials.map(row => <article className="ecommerce-list-card" key={row.id}><h2>{row.snapshot.course_name}</h2><p>{row.credential_number}</p><p className="elearning-course-status">{t(`elearning.certificates.${row.status}`)}</p><p>{t("elearning.certificates.completionDate")}: {date(row.completed_at, i18n.language)}</p><p>{t("elearning.certificates.issueDate")}: {date(row.issued_at, i18n.language)}</p><div className="elearning-content-toolbar"><Link className="ecommerce-primary-button" to={`/my-learning/certificates/${row.id}`}>{t("elearning.certificates.view")}</Link><Download id={row.id} /></div></article>)}</div>}</section>;
}
export function CredentialView({ id: suppliedId, course, onClose }) {
  const { credentialId } = useParams(); const id = suppliedId || credentialId;
  const { t, i18n } = useTranslation("dashboard"); const state = useCertificates(() => fetchCredential(id, course), [id, course]);
  if (state.loading) return <Loading />;
  if (state.error) return <Failure retry={state.refresh} />;
  const row = state.data; const design = row.design;
  return <section className="elearning-credential-view"><div className="elearning-content-toolbar">{onClose ? <button className="ecommerce-secondary-button" onClick={onClose}>{t("elearning.certificates.close")}</button> : <Link to="/my-learning/certificates">{t("elearning.certificates.myCertificates")}</Link>}<Download id={id} course={course} /><a href={row.verification_url} target="_blank" rel="noreferrer">{t("elearning.certificates.verify")}</a></div><article className="elearning-certificate-document" dir={i18n.dir()}>
    {design.logo_image && <img className="elearning-certificate-logo" src={`data:image/png;base64,${design.logo_image}`} alt={design.issuer_name} />}<p>{design.issuer_name}</p><h1>{design.title}</h1>{design.subtitle && <p>{design.subtitle}</p>}<h2>{row.learner_name}</h2><h3>{row.course_name}</h3><p className="elearning-certificate-body">{design.body}</p><p>{t("elearning.certificates.completionDate")}: {date(row.completed_at, i18n.language)} · {t("elearning.certificates.issueDate")}: {date(row.issued_at, i18n.language)}</p>{design.signature_image && <img className="elearning-certificate-signature" src={`data:image/png;base64,${design.signature_image}`} alt={design.signer_name} />}<p>{design.signer_name} {design.signer_title}</p><p>{row.credential_number}</p><strong className={`elearning-credential-status is-${row.status}`}>{t(`elearning.certificates.${row.status}`)}</strong></article></section>;
}
const fields = ["name", "title", "subtitle", "body", "issuer_name", "signer_name", "signer_title"];
function TemplateForm({ value, branding, close, saved }) {
  const { t } = useTranslation("dashboard");
  const [form, setForm] = useState(value || { status: "active", design: { name: "", title: t("elearning.certificates.defaultTitle"), subtitle: "", body: "{{learner_name}} — {{course_name}}", issuer_name: branding?.issuer_name || "", signer_name: "", signer_title: "", logo_url: branding?.logo_url || "", signature_url: "" } });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const edit = (key, text) => setForm(current => ({ ...current, design: { ...current.design, [key]: text } }));
  const submit = async event => { event.preventDefault(); const variable = validatePlaceholders(form.design); if (variable) { setError(t("elearning.certificates.unknownVariable", { variable })); return; } setBusy(true); setError(""); try { const data = await saveCertificateTemplate(form); saved(data); } catch (failure) { setError(typeof failure.detail === "string" ? failure.detail : t("elearning.certificates.error")); } finally { setBusy(false); } };
  const upload = async (kind, event) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); try { const data = await uploadCourseCover(file); edit(kind + "_url", data.asset_url); } catch { setError(t("elearning.certificates.imageError")); } finally { setBusy(false); } };
  return <Dialog title={t("elearning.certificates.template")} close={close}><form onSubmit={submit} className="elearning-certificate-form">{fields.map(key => <label key={key}>{t(`elearning.certificates.fields.${key}`)}{key === "body" ? <textarea aria-label={t(`elearning.certificates.fields.${key}`)} rows={4} maxLength={1200} value={form.design[key]} onChange={event => edit(key, event.target.value)} /> : <input required={["name", "title", "issuer_name"].includes(key)} maxLength={key === "name" || key.startsWith("signer") ? 120 : 200} value={form.design[key]} onChange={event => edit(key, event.target.value)} />}</label>)}<p>{t("elearning.certificates.variables")} {CERTIFICATE_VARIABLES.map(key => `{{${key}}}`).join(" · ")}</p>{["logo", "signature"].map(kind => <label key={kind}>{t(`elearning.certificates.${kind}`)}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={event => upload(kind, event)} />{form.design[kind + "_url"] && <span>{t("elearning.certificates.imageSelected")}</span>}</label>)}<label>{t("elearning.certificates.status")}<select value={form.status} onChange={event => setForm(current => ({ ...current, status: event.target.value }))}><option value="active">{t("elearning.certificates.active")}</option><option value="archived">{t("elearning.certificates.archived")}</option></select></label>{error && <p role="alert">{error}</p>}<div className="elearning-content-toolbar"><button className="ecommerce-primary-button" disabled={busy}>{t("elearning.certificates.save")}</button><button type="button" className="ecommerce-secondary-button" disabled={busy} onClick={close}>{t("elearning.certificates.cancel")}</button></div></form></Dialog>;
}
export default function CourseCertificates({ course }) {
  const { t, i18n } = useTranslation("dashboard"); const { labels } = useELearningTerminology(); const state = useCertificates(() => fetchCertificates(course.id), [course.id]);
  const [editing, setEditing] = useState(null); const [configuration, setConfiguration] = useState(null); const [confirmation, setConfirmation] = useState(null); const [reason, setReason] = useState(""); const [view, setView] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(false);
  const execute = async action => { setBusy(true); setError(false); try { state.update(await action()); setConfiguration(null); setConfirmation(null); setReason(""); } catch { setError(true); } finally { setBusy(false); } };
  if (state.loading) return <Loading />;
  if (state.error) return <Failure retry={state.refresh} />;
  const data = state.data; const config = configuration || data.configuration;
  return <section className="elearning-course-certificates"><h2>{t("elearning.certificates.courseCertificate", { course: labels.course })}</h2><form className="ecommerce-list-card elearning-certificate-form elearning-certificate-settings" onSubmit={event => { event.preventDefault(); execute(() => configureCertificate(course.id, { enabled: config.enabled, template_id: config.template_id, title_override: config.title_override || "", issuer_override: config.issuer_override || "" })); }}><label className="elearning-certificate-toggle"><input type="checkbox" disabled={busy} checked={config.enabled} onChange={event => setConfiguration({ ...config, enabled: event.target.checked })} />{t("elearning.certificates.enabled")}</label><label className="elearning-certificate-template-field">{t("elearning.certificates.template")}<select aria-label={t("elearning.certificates.template")} required={config.enabled} disabled={busy} value={config.template_id || ""} onChange={event => setConfiguration({ ...config, template_id: event.target.value || null })}><option value="">{t("elearning.certificates.selectTemplate")}</option>{data.templates.filter(row => row.status === "active" || row.id === config.template_id).map(row => <option key={row.id} value={row.id} disabled={row.status === "archived"}>{row.design.name}</option>)}</select></label>{["title_override", "issuer_override"].map(key => <label key={key}>{t(`elearning.certificates.${key}`)}<input disabled={busy} maxLength={200} value={config[key] || ""} onChange={event => setConfiguration({ ...config, [key]: event.target.value })} /></label>)}<p className="elearning-certificate-settings-help">{t("elearning.certificates.prospective")}</p><footer className="elearning-certificate-settings-actions"><button type="submit" className="ecommerce-primary-button" disabled={busy}>{t("elearning.certificates.save")}</button></footer></form>
    <section className="ecommerce-list-card"><h3>{t("elearning.certificates.templates")}</h3><button className="ecommerce-secondary-button" onClick={() => setEditing({})}>{t("elearning.certificates.newTemplate")}</button>{data.templates.map(row => <div className="elearning-certificate-template-row" key={row.id}><span>{row.design.name} · {t(`elearning.certificates.${row.status}`)}</span><button className="ecommerce-secondary-button" onClick={() => setEditing(row)}>{t("elearning.certificates.edit")}</button></div>)}</section>
    <section className="ecommerce-list-card"><h3>{t("elearning.certificates.issued")}: {data.counts.total}</h3><p>{t("elearning.certificates.active")}: {data.counts.active} · {t("elearning.certificates.revoked")}: {data.counts.revoked}</p><button className="ecommerce-secondary-button" disabled={!data.configuration.enabled || busy} onClick={() => setConfirmation({ backfill: true })}>{t("elearning.certificates.backfill")}</button>{!data.credentials.length && <p>{t("elearning.certificates.noneIssued")}</p>}<div className="elearning-certificate-grid">{data.credentials.map(row => <article key={row.id}><h4>{row.snapshot.learner_name}</h4><p>{row.credential_number}</p><p>{t("elearning.certificates.completionDate")}: {date(row.completed_at, i18n.language)}</p><p>{t("elearning.certificates.issueDate")}: {date(row.issued_at, i18n.language)}</p><strong>{t(`elearning.certificates.${row.status}`)}</strong><div className="elearning-content-toolbar"><button className="ecommerce-secondary-button" onClick={() => setView(row.id)}>{t("elearning.certificates.view")}</button><Download id={row.id} course={course.id} />{row.status === "active" && <button className="ecommerce-secondary-button" onClick={() => setConfirmation(row)}>{t("elearning.certificates.revoke")}</button>}</div></article>)}</div></section>{error && <Failure />}
    {editing && <TemplateForm value={editing.id ? editing : null} branding={data.branding} close={() => setEditing(null)} saved={() => { setEditing(null); state.refresh(); }} />}
    {confirmation && <Dialog title={t(`elearning.certificates.${confirmation.backfill ? "backfill" : "revokeQuestion"}`)} close={() => { if (!busy) setConfirmation(null); }}><p>{t(`elearning.certificates.${confirmation.backfill ? "backfillHelp" : "revokeHelp"}`)}</p><form onSubmit={event => { event.preventDefault(); execute(() => confirmation.backfill ? backfillCertificates(course.id) : revokeCertificate(course.id, confirmation.id, reason)); }}>{!confirmation.backfill && <label>{t("elearning.certificates.reason")}<textarea required maxLength={1000} value={reason} onChange={event => setReason(event.target.value)} /></label>}<div className="elearning-content-toolbar"><button className="ecommerce-primary-button" disabled={busy || (!confirmation.backfill && !reason.trim())}>{t("elearning.certificates.confirm")}</button><button type="button" className="ecommerce-secondary-button" disabled={busy} onClick={() => setConfirmation(null)}>{t("elearning.certificates.cancel")}</button></div>{error && <Failure />}</form></Dialog>}
    {view && <Dialog title={t("elearning.certificates.view")} close={() => setView(null)}><CredentialView id={view} course={course.id} onClose={() => setView(null)} /></Dialog>}
  </section>;
}
