const {chromium}=require('playwright');
const fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const f=JSON.parse(fs.readFileSync(process.env.MADAR_COMMERCIAL_FIXTURE || '/fixture.json','utf8'));
assert.equal(f.synthetic_only,true);assert.equal(f.base_url,'http://127.0.0.1:13001');assert.equal(f.api_url,'http://127.0.0.1:18002');
function totp(seed){let bits='';for(const c of seed.replace(/=+$/,''))bits+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c).toString(2).padStart(5,'0');const bytes=[];for(let i=0;i+8<=bits.length;i+=8)bytes.push(parseInt(bits.slice(i,i+8),2));const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=crypto.createHmac('sha1',Buffer.from(bytes)).update(b).digest();return String((h.readUInt32BE(h[h.length-1]&15)&0x7fffffff)%1000000).padStart(6,'0');}
(async()=>{
const report={synthetic_only:true,checks:[],external_requests_blocked:0,console_errors:[]};let step='launch';let activePage;
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
async function session(identity){const c=await browser.newContext();await c.route('**/*',r=>{const u=new URL(r.request().url());if(['http:','https:'].includes(u.protocol)&&![f.base_url,f.api_url].includes(u.origin)){report.external_requests_blocked++;return r.abort();}return r.continue();});const page=await c.newPage();activePage=page;page.setDefaultTimeout(15000);page.on('pageerror',e=>report.console_errors.push(e.name));page.on('console',async m=>{if(m.type()==='error'){for(const arg of m.args()){const v=await arg.evaluate(x=>x instanceof Error?{name:x.name,message:x.message}:null).catch(()=>null);if(v)report.console_errors.push(v);}}});await page.goto(f.base_url+'/login');await page.locator('input[name=email]').waitFor();await page.locator('input[name=email]').fill(identity.email);await page.locator('input[name=password]').fill(identity.password);const loginPromise=page.waitForResponse(r=>r.url()===f.api_url+'/auth/login');await page.locator('button[type=submit]').click();const login=await loginPromise;assert.equal(login.status(),200,'login status');return {c,page,login};}
async function navigate(page,path){await page.evaluate(path=>{history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'));},path);}
async function api(page,path,init={}){return page.evaluate(async ({url,init})=>{const {apiFetch,readApiResponse}=await import('/src/utils/apiClient.js');const r=await apiFetch(url,init);return {status:r.status,data:await readApiResponse(r)};},{url:f.api_url+path,init});}
try{
step='member-login';const member=await session(f.member);const p=member.page;await p.waitForURL('**/dashboard');report.checks.push('browser-password-login');
for(const plan of ['forms','website','business','business_plus']){
 step='plan-'+plan;await navigate(p,'/dashboard');const select=p.getByRole('combobox',{name:'Workspace',exact:true});await select.waitFor();await select.selectOption(String(f.plans[plan]));await p.waitForFunction(t=>document.querySelector('[aria-label="Workspace"]')?.value===String(t),f.plans[plan]);
 let state;for(let i=0;i<20;i++){state=await api(p,'/billing/entitlements');if(state.data?.entitlements?.tenant_id===f.plans[plan])break;await p.waitForTimeout(100);}assert.equal(state.status,200);assert.equal(state.data.entitlements.plan_id,plan);const caps=state.data.entitlements.capabilities;assert.equal(caps.includes('ecommerce_management'),['business','business_plus'].includes(plan));assert.equal(caps.includes('reservations'),plan!=='forms');
 const calls=[];const track=r=>{if(r.url().startsWith(f.api_url+'/ecommerce/'))calls.push(r.url());};p.on('request',track);await navigate(p,'/ecommerce/products');
 if(['forms','website'].includes(plan)){await p.getByRole('heading',{name:'Plan access required'}).waitFor();assert.equal(calls.length,0,'restricted route must not fetch commerce');}else{await p.waitForTimeout(1000);assert.equal(await p.getByRole('heading',{name:'Plan access required'}).count(),0);}
 p.off('request',track);const direct=await api(p,'/ecommerce/catalog');assert.equal(direct.status,['business','business_plus'].includes(plan)?200:403);report.checks.push('tenant-switch-capabilities-'+plan,'direct-api-plan-'+plan);
}
step='member-admin-denied';assert.equal((await api(p,'/admin/commercial/review')).status,403);report.checks.push('tenant-owner-cannot-grant-plan');
step='member-refresh';assert.equal((await api(p,'/auth/refresh',{method:'POST'})).status,200);report.checks.push('real-refresh-session');
await member.c.close();
step='admin-login-mfa';const admin=await session(f.admin);const a=admin.page;const pending=await admin.login.json();assert.equal(pending.mfa_required,true);await a.locator('input[autocomplete="one-time-code"]').fill(totp(f.admin.totp_secret));await a.locator('button[type=submit]').click();await a.waitForURL('**/dashboard');report.checks.push('browser-admin-totp-aal2');
step='admin-commercial-review';await navigate(a,'/admin/commercial/'+f.plans.review);await a.getByRole('heading',{name:'Commercial access · Workspace '+f.plans.review}).waitFor();step='admin-select-plan';{const r=await api(a,'/admin/commercial/tenants/'+f.plans.review);report.commercial_api={status:r.status,keys:Object.keys(r.data||{}),history_keys:Object.keys(r.data?.history||{})};}report.catalog_status=(await api(a,'/billing/catalog')).status;step='admin-field-Plan';await a.getByLabel('Plan',{exact:true}).selectOption('business');step='admin-field-Actual amount (USD)';await a.getByLabel('Actual amount (USD)',{exact:true}).fill('25.00');const now=new Date();const end=new Date(now);end.setUTCMonth(end.getUTCMonth()+1);const local=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);step='admin-field-Valid from';await a.getByLabel('Valid from',{exact:true}).fill(local(now));step='admin-field-Paid through';await a.getByLabel('Paid through',{exact:true}).fill(local(end));step='admin-field-Receipt / reference';await a.getByLabel('Receipt / reference',{exact:true}).fill('SYNTHETIC-BROWSER-RECEIPT');step='admin-field-Reason / notes';await a.getByLabel('Reason / notes',{exact:true}).fill('Synthetic isolated browser manual payment proof');step='admin-field-Amount or period override reason (required for exceptions)';await a.getByLabel('Amount or period override reason (required for exceptions)',{exact:true}).fill('Synthetic browser amount/period review');step='admin-confirm-checkbox';await a.getByRole('checkbox').check();step='admin-submit';const commandPromise=a.waitForResponse(r=>r.url().endsWith('/manual-payments')&&r.request().method()==='POST');await a.getByRole('button',{name:'Record manual payment',exact:true}).click();const command=await commandPromise;report.manual_payment_status=command.status();assert.equal(command.status(),200);const original=await command.json();await a.getByRole('status').filter({hasText:'Commercial command recorded'}).waitFor();
step='admin-idempotent-browser-retry';const repeatedPromise=a.waitForResponse(r=>r.url().endsWith('/manual-payments')&&r.request().method()==='POST');await a.getByRole('button',{name:'Record manual payment',exact:true}).click();const repeated=await repeatedPromise;assert.equal(repeated.status(),200);assert.deepEqual(await repeated.json(),original);report.checks.push('browser-manual-cash-aal2-csrf-audit','browser-durable-command-replay');
step='admin-refresh-aal2';assert.equal((await api(a,'/auth/refresh',{method:'POST'})).status,200);assert.equal((await api(a,'/admin/commercial/review')).status,200);report.checks.push('refresh-retains-request-aal2');
step='logout';assert.equal((await api(a,'/auth/log_out',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,200);assert.equal((await api(a,'/admin/commercial/review')).status,401);report.checks.push('logout-revokes-admin-session');
assert.deepEqual(report.console_errors,[]);report.status='passed';await admin.c.close();
}catch(e){report.status='failed';if(activePage){report.path=new URL(activePage.url()).pathname;report.headings=await activePage.locator('h1').allTextContents();report.labels=await activePage.locator('label').allTextContents();report.alerts=await activePage.locator('[role=alert]').allTextContents();}report.failed_step=step;report.error_name=e.name;report.safe_assertion=e.name==='AssertionError'?e.message.split('\n')[0]:'operation failed';}
await browser.close();fs.writeFileSync(process.env.MADAR_COMMERCIAL_RESULT || '/results/flow-result.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));process.exitCode=report.status==='passed'?0:1;
})();
