export const formsTabContent = {
  en: {
    legacyFieldTypes: {
      money: { label: "Price or budget", group: "Number" },
      phone: { label: "Phone", group: "Contact" },
      radio: { label: "Radio buttons", group: "Choice" },
      yesNo: { label: "Yes or no", group: "Choice" },
      status: { label: "Status selector", group: "Workflow" },
    },
    toolbar: {
      undo: "Undo",
      redo: "Redo",
      bold: "Bold",
      italic: "Italic",
      underline: "Underline",
      bullets: "Bulleted list",
      numbers: "Numbered list",
      alignLeft: "Align left",
      alignCenter: "Align center",
      alignRight: "Align right",
      justify: "Justify",
      textStyle: "Text style",
      text: "Text",
      heading1: "H1",
      heading2: "H2",
      heading3: "H3",
      leftToRight: "Left-to-right",
      rightToLeft: "Right-to-left",
      textColor: "Text color",
      backgroundColor: "Background color",
      directionLtrShort: "LTR",
      directionRtlShort: "RTL",
      descriptionExampleFormatting: "Description and example formatting",
    },
    labels: {
      titlePage: "Title page",
      page: "Page",
      currentForm: "Current form",
      untitledForm: "Untitled form",
      templates: "Templates",
      chooseTemplate: "Choose a template",
      language: "Language",
      english: "English",
      arabic: "Arabic",
      addQuestion: "Add question",
      addPage: "Add page",
      formActions: "Form actions",
      formSettings: "Form settings",
      previewForm: "Preview form",
      placeForm: "Place form",
      deleteForm: "Delete form",
      pageLabel: "Page",
      saveSubmissionsTo: "Save submissions to",
      formSubmissionsOnly: "Form submissions only",
      addToPage: "Add to page",
      alreadyPlacedOn: "Already placed on",
      successMessage: "Success message",
      pageDescription: "Page description",
      formTitleFormatting: "Form title formatting",
      formDescriptionFormatting: "Form description formatting",
      untitledQuestion: "Untitled question",
      question: "Question",
      description: "Description",
      example: "Example",
      answerOptions: "Answer options",
      addOption: "Add option",
      insertOptionBelow: "Insert option below",
      deleteOption: "Delete option",
      from: "From",
      to: "To",
      lowLabel: "Low label",
      highLabel: "High label",
      maxRating: "Max rating",
      timeOverride: "Time override",
      required: "Required",
      moveQuestionUp: "Move question up",
      moveQuestionDown: "Move question down",
      duplicate: "Duplicate",
      deleteQuestion: "Delete question",
      addQuestionHere: "Add question here",
      quizOptions: "Quiz options",
      closeSettings: "Close settings",
      primaryLanguage: "Primary language",
      translations: "Translations",
      enableQuizMode: "Enable quiz mode",
      focusMode: "Focus mode",
      totalTimeLimit: "Total time limit (minutes)",
      timePerQuestion: "Time per question (seconds)",
      scoring: "Scoring",
      passingScore: "Passing score (%)",
      showResults: "Show results",
      allowRetakes: "Allow retakes",
      maxRetakes: "Max retakes",
      conditionalLogic: "Conditional logic",
      addRule: "Add rule",
      equals: "equals",
      answer: "Answer",
      show: "show",
      hide: "hide",
      deleteRule: "Delete rule",
      close: "Close",
      save: "Save",
      formControls: "Form controls",
    },
    messages: {
      createFirstFormTitle: "Create your first form",
      createFirstFormBody: "Start with a clean form, add questions, then place it on a page.",
      newForm: "New form",
      replaceTemplateConfirm: "Replace this form with the selected template?",
      addTranslations: "Add {language} translations",
      formDescriptionHelp: "Form description, shown to people filling it out",
      emptyPageTitle: "No questions on this page yet.",
      emptyPageBody: "Add a question from the side panel to start building this form.",
      deleteQuestionConfirm: "Delete this question?",
      settingsDescription: "Control language, success message, quiz mode, focus mode, scoring, and retakes.",
      primaryLanguageHelp: "Sets the default writing direction. Translations are entered manually.",
      translationsHelp: "Show translation fields throughout the form editor. Madar does not auto-translate these fields.",
      successMessageHelp: "Shown after submit in the primary language.",
      quizModeHelp: "Turns this form into a scored assessment with quiz-specific controls.",
      focusModeHelp: "Requires fullscreen while the quiz is active. Exiting fullscreen locks the attempt and prevents retakes.",
      totalTimeHelp: "Set the maximum time allowed for the full quiz. Use 0 for no limit.",
      questionTimeHelp: "Limit each question individually. Use 0 when questions should not be timed.",
      scoringHelp: "Choose whether answers are graded automatically, manually, or by completion.",
      passingScoreHelp: "Minimum score required to pass when scoring is enabled.",
      showResultsHelp: "Displays the respondent's result after submission.",
      allowRetakesHelp: "Lets respondents submit the same quiz again when allowed.",
      maxRetakesHelp: "Maximum number of additional attempts. Use 0 for unlimited retakes.",
      logicHelp: "If a question equals an answer, show or hide another question.",
      noLogicRules: "No logic rules yet.",
      deleteFormTitle: "Delete this form?",
      deleteFormMessage: "and its questions, translations, and workflows will be removed. Connected blocks will remain visibly disconnected until you explicitly reconnect or remove them. This cannot be undone.",
      deleteFormPageTitle: "Delete this form page?",
      deleteFormPageMessage: "and its questions will be removed from this form. This cannot be undone.",
      keepForm: "Keep form",
      keepPage: "Keep page",
      deletePage: "Delete page",
    },
    placeholders: {
      pageDescription: "Page description",
      untitledForm: "Untitled form",
      formDescription: "Add a short description or leave this empty",
      question: "Question",
      shownUnderQuestion: "Shown under the question",
      example: "Example answer or placeholder",
      option: "Option {number}",
      translateOption: "Translate option {number}",
      addTitle: "Add {language} title",
      addDescription: "Add {language} description",
      addQuestionText: "Add {language} question text",
      addExample: "Add {language} example",
      addSuccessMessage: "Add {language} success message",
    },
    counts: {
      questions: "questions",
      pages: "pages",
      responses: "responses",
      quiz: "Quiz",
      form: "Form",
    },
    suffixes: {
      titleTranslation: "title translation",
      descriptionTranslation: "description translation",
      questionTranslation: "question translation",
      exampleTranslation: "example translation",
      optionTranslation: "option {number} translation",
      successMessageTranslation: "success message translation",
    },
    scoringOptions: {
      automatic: "Automatic",
      manual: "Manual review",
      completion: "Completion only",
    },
  },
  ar: {},
};

export function getFormsTabContent(lang = "en") {
  return formsTabContent[lang] && Object.keys(formsTabContent[lang]).length
    ? formsTabContent[lang]
    : formsTabContent.en;
}
