const responsesContentEn = {
  kicker: "Responses",
  title: "Form submissions",
  subtitle: "Review submitted form data, filter responses, and inspect saved fields.",
  settingsKicker: "Response settings",
  responseTools: "Response views and controls",
  responseViews: "Submission type",
  completedTab: "Completed",
  incompleteTab: "Incomplete",
  settingsTab: "Settings",
  draftSettingsTitle: "Save and resume",
  draftSettingsText: "Control whether people can save an unfinished form and return to it later.",
  allowResumeLater: "Allow Resume later",
  allowResumeLaterText: "Show the Resume later button on this form and save incomplete answers.",
  resumeSettingEnabled: "Resume later is enabled.",
  resumeSettingDisabled: "Resume later is disabled.",
  requiredFieldSetting: "Required fields",
  requiredFieldSettingText: "Checked only when the completed form is submitted.",
  draftExpirationSetting: "Draft expiration",
  draftExpirationSettingText: "Drafts do not expire automatically.",
  resumeDraft: "Resume and complete this form",
  resumeUnavailable: "Publish this form with a hosted address to create its resume link.",
  copy: "Copy data",
  copied: "Data copied.",
  printed: "Data printed to console.",
  openBuilder: "Open builder",
  forms: "Forms",
  chooseForm: "Choose form",
  form: "Form",
  submissions: "Answers",
  questions: "Fields in this form",
  completion: "Filled in",
  selectForm: "Choose a form to see its answers.",
  selectedForm: "Current form",
  savedOnly: "Saved in this project",
  savingTo: "Saved to",
  response: "response",
  responses: "responses",
  submission: "answer",
  submissionsLower: "answers",
  field: "field",
  fields: "fields",
  required: "Required fields",
  optional: "Optional fields",
  formsWithData: "Forms with answers",
  latest: "Newest answer",
  none: "None",
  status: "Status",
  reviewStatus: "Status",
  created: "Sent on",
  submittedBy: "Submitted by",
  guestSubmitter: "Guest",
  guestRole: "guest",
  score: "Score",
  newStatus: "New",
  emptyTitle: "No answers yet",
  emptyText:
    "When someone sends this form, their answers will show up here.",
  noForm: "No form selected",
  noFormText: "Create or choose a form first. Answers will appear here after people submit it.",
  loadingTitle: "Loading answers",
  loadingText: "Getting the latest answers for this form.",
  errorTitle: "Could not load answers",
  errorText: "Try again in a moment or confirm you still have access to this project.",
  forbidden: "You do not have access to these answers.",
  notFound: "This project, form, or answer list was not found.",
  refresh: "Refresh",
  reviewInExcel: "Open spreadsheet",
  spreadsheetTitle: "Response spreadsheet",
  spreadsheetSubtitle: "Read-only web preview",
  closeSpreadsheet: "Close",
  spreadsheetPopupBlocked: "Allow pop-ups to open the spreadsheet in a new tab.",

  refreshing: "Refreshing...",
  previous: "Previous",
  next: "Next",
  page: "Page",
  statusFilter: "Status",
  allStatuses: "All",
  filteredEmptyTitle: "No matching answers",
  filteredEmptyText: "No answers on this page match your search or filters.",
  updateStatusFailed: "Could not update the answer status.",
  searchData: "Find an answer",
  searchDataText: "Search by name, email, status, date, or any field answer.",
  search: "Search",
  searchPlaceholder: "Name, email, answer, status...",
  searchIn: "Search in",
  allFields: "All fields",
  clearSearch: "Clear search",
  assistantKicker: "Assistant",
  assistantTitle: "Response assistant",
  assistantText: "Ask about this form's submissions and filters.",
  assistantPlaceholder: "Example: summarize the current responses",
  assistantEmpty: "Load a form or collect responses to get an answer.",
  assistantAsk: "Ask",
  assistantNoResponses:
    "There are no submitted answers for this form yet. Once responses arrive, they will appear in the answer list and table.",
  match: "match",
  matches: "matches",
  submissionList: "Answers",
  submissionListText: "Choose an answer to review it.",
  submissionDetails: "Answer details",
  submissionDetailsText: "Read the selected answer field by field.",
  noAnswerPreview: "No answer preview yet",
  editRecord: "Edit",
  deleteRecord: "Delete",
  deletingRecord: "Deleting...",
  saveChanges: "Save changes",
  savingChanges: "Saving...",
  cancel: "Cancel",
  yes: "Yes",
  no: "No",
  recordUpdated: "Record updated.",
  recordUpdateFailed: "We could not update this record. Check the values and try again.",
  recordDeleted: "Record deleted.",
  recordDeleteFailed: "We could not delete this record. Refresh and try again.",
  deleteRecordConfirm: "Delete this record permanently? This cannot be undone.",
  invalidStructuredValue: "One of the edited values is not valid. Check numbers and structured values.",
  editRecordHelp: "Edit saved answers",
  deleteRecordHelp: "Delete this record",
  noDate: "No date",
  noSelectedSubmission: "No answer selected",
  noSelectedSubmissionText: "Choose an answer from the list to see its saved fields.",
};

export const responsesContent = {
  en: responsesContentEn,
  ar: responsesContentEn,
};

export function getResponsesContent(lang = "en") {
  return responsesContent[lang] || responsesContent.en;
}
