-- Tenant ID rule:
-- tenants.tenant_id is the main tenant ID.
-- users.tenant_id points to tenants.tenant_id.
-- website_settings.tenant_id points to the SAME tenants.tenant_id
-- through website_settings.user_id = users.id.

create table if not exists public.tenants (
  tenant_id integer generated by default as identity primary key,
  brand_name text not null default '',
  owner_name text not null default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.users
add column if not exists tenant_id integer;

alter table public.website_settings
add column if not exists tenant_id integer;

-- Create tenant rows for users that do not have tenant_id yet.
insert into public.tenants (brand_name, owner_name)
select
  coalesce(ws.brand, ''),
  trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, ''))
from public.users u
left join public.website_settings ws
  on ws.user_id = u.id
where u.tenant_id is null;

-- Give every user without tenant_id one tenant_id.
with tenant_matches as (
  select
    u.id as user_id,
    t.tenant_id,
    row_number() over (
      partition by u.id
      order by t.tenant_id
    ) as rn
  from public.users u
  join public.tenants t
    on t.owner_name = trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, ''))
  where u.tenant_id is null
)
update public.users u
set tenant_id = tm.tenant_id
from tenant_matches tm
where u.id = tm.user_id
  and tm.rn = 1;

-- Website settings must use the SAME tenant_id as its user.
update public.website_settings ws
set tenant_id = u.tenant_id
from public.users u
where ws.user_id = u.id;

-- Constraints
alter table public.users
alter column tenant_id set not null;

alter table public.users
drop constraint if exists users_tenant_id_unique;

alter table public.users
add constraint users_tenant_id_unique unique (tenant_id);

alter table public.users
drop constraint if exists users_tenant_id_fkey;

alter table public.users
add constraint users_tenant_id_fkey
foreign key (tenant_id)
references public.tenants(tenant_id)
on delete restrict;

alter table public.website_settings
alter column tenant_id set not null;

alter table public.website_settings
drop constraint if exists website_settings_tenant_id_fkey;

alter table public.website_settings
add constraint website_settings_tenant_id_fkey
foreign key (tenant_id)
references public.tenants(tenant_id)
on delete restrict;

notify pgrst, 'reload schema';