-- Tenant foundation for signup and future multi-user tenants.
-- users.tenant_id is the user's primary/current tenant, not a unique owner link.

alter table public.users
drop constraint if exists users_tenant_id_unique;

create table if not exists public.tenant_memberships (
  id bigint generated by default as identity primary key,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  auth_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member',
  status text not null default 'active',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  constraint tenant_memberships_role_check
    check (role in ('owner', 'admin', 'member')),
  constraint tenant_memberships_status_check
    check (status in ('active', 'invited', 'disabled')),
  constraint tenant_memberships_user_tenant_unique
    unique (user_id, tenant_id),
  constraint tenant_memberships_auth_tenant_unique
    unique (auth_id, tenant_id)
);

drop trigger if exists set_tenant_memberships_updated_at on public.tenant_memberships;

create trigger set_tenant_memberships_updated_at
before update on public.tenant_memberships
for each row
execute function public.set_updated_at();

insert into public.tenant_memberships (tenant_id, user_id, auth_id, role, status)
select u.tenant_id, u.id, u.auth_id, 'owner', 'active'
from public.users u
where u.tenant_id is not null
  and not exists (
    select 1
    from public.tenant_memberships tm
    where tm.user_id = u.id
      and tm.tenant_id = u.tenant_id
  );

create index if not exists tenant_memberships_tenant_id_idx
on public.tenant_memberships (tenant_id);

create index if not exists tenant_memberships_auth_id_idx
on public.tenant_memberships (auth_id);

grant select, insert, update, delete
on table public.tenants
to service_role;

grant usage, select
on sequence public.tenants_tenant_id_seq
to service_role;

grant select, insert, update, delete
on table public.tenant_memberships
to service_role;

grant usage, select
on sequence public.tenant_memberships_id_seq
to service_role;

grant select
on table public.tenants
to authenticated;

grant select
on table public.tenant_memberships
to authenticated;

alter table public.tenants enable row level security;
alter table public.tenant_memberships enable row level security;

drop policy if exists tenants_select_member on public.tenants;
drop policy if exists tenant_memberships_select_same_tenant on public.tenant_memberships;

create policy tenants_select_member
on public.tenants
for select
to authenticated
using (
  exists (
    select 1
    from public.tenant_memberships tm
    where tm.tenant_id = tenants.tenant_id
      and tm.auth_id = auth.uid()
      and tm.status = 'active'
  )
);

create policy tenant_memberships_select_same_tenant
on public.tenant_memberships
for select
to authenticated
using (auth_id = auth.uid());

notify pgrst, 'reload schema';
