-- Canonical commercial state, hosted addresses, operational usage, and AI tokens.
-- Backward compatible: legacy features remain authoritative until reviewed.

begin;

create table if not exists public.tenant_subscriptions (
  id bigint generated by default as identity primary key,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  plan_id text not null check (plan_id in ('forms','website','business','business_plus')),
  state text not null check (state in ('requested','pending_review','active','scheduled_change','past_due','suspended','canceled','expired','review_required')),
  catalog_version text not null,
  currency text not null default 'USD' check (currency = 'USD'),
  price_minor integer not null check (price_minor >= 0),
  billing_interval text not null default 'month' check (billing_interval = 'month'),
  period_start timestamptz,
  period_end timestamptz,
  source text not null default 'manual',
  legacy_feature_id bigint,
  migration_provenance jsonb not null default '{}'::jsonb,
  requested_by_user_id integer references public.users(id) on delete set null,
  activated_by_user_id integer references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tenant_subscriptions_one_active_idx
on public.tenant_subscriptions (tenant_id)
where state = 'active';

create index if not exists tenant_subscriptions_tenant_state_idx
on public.tenant_subscriptions (tenant_id, state, updated_at desc);

create table if not exists public.tenant_addons (
  id bigint generated by default as identity primary key,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  addon_id text not null check (addon_id in (
    'branded_madar_subdomain','additional_storage_5gb',
    'additional_workspace_seat','workspace_seat_pack_5',
    'ai_analytics_starter','ai_analytics_plus','ai_token_pack_750k',
    'google_drive_private','ocr','hosted_email_mailbox','custom_domain'
  )),
  quantity integer not null default 1 check (quantity > 0),
  state text not null check (state in ('requested','pending_review','active','scheduled_change','past_due','suspended','canceled','expired')),
  catalog_version text not null,
  price_minor integer check (price_minor is null or price_minor >= 0),
  currency text not null default 'USD' check (currency = 'USD'),
  billing_interval text not null check (billing_interval in ('month','one_time')),
  period_start timestamptz,
  period_end timestamptz,
  source text not null default 'manual',
  idempotency_key text,
  assigned_by_user_id integer references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tenant_addons_active_recurring_idx
on public.tenant_addons (tenant_id, addon_id)
where state = 'active' and billing_interval = 'month';

create unique index if not exists tenant_addons_one_active_ai_package_idx
on public.tenant_addons (tenant_id)
where state = 'active'
  and billing_interval = 'month'
  and addon_id in ('ai_analytics_starter','ai_analytics_plus');

create unique index if not exists tenant_addons_idempotency_idx
on public.tenant_addons (tenant_id, idempotency_key)
where idempotency_key is not null;

create index if not exists tenant_addons_tenant_state_idx
on public.tenant_addons (tenant_id, state, addon_id);

create table if not exists public.billing_addon_requests (
  id bigint generated by default as identity primary key,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  addon_id text not null,
  quantity integer not null default 1 check (quantity > 0),
  state text not null default 'pending_review' check (state in ('requested','pending_review','approved','declined','canceled')),
  catalog_version text not null,
  idempotency_key text not null,
  requested_by_user_id integer not null references public.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, idempotency_key)
);

create table if not exists public.legacy_billing_migration_reviews (
  tenant_id integer primary key references public.tenants(tenant_id) on delete cascade,
  legacy_records jsonb not null default '[]'::jsonb,
  active_legacy_feature_id bigint,
  active_legacy_record jsonb,
  recommended_plan_id text,
  migration_state text not null default 'review_required' check (migration_state in ('mapped','review_required','resolved')),
  reason text not null,
  resolved_subscription_id bigint references public.tenant_subscriptions(id) on delete set null,
  reviewed_by_user_id integer references public.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.website_settings
  add column if not exists standard_path_slug text,
  add column if not exists legacy_subdomain_routing_preserved boolean not null default false,
  add column if not exists branded_subdomain_commercial_status text not null default 'not_applicable',
  add column if not exists branded_subdomain_reviewed_at timestamptz,
  add column if not exists branded_subdomain_reviewed_by_user_id integer references public.users(id) on delete set null,
  add column if not exists branded_subdomain_review_reason text;

alter table public.website_settings
  drop constraint if exists website_settings_branded_subdomain_commercial_status_check;
alter table public.website_settings
  add constraint website_settings_branded_subdomain_commercial_status_check check (
    branded_subdomain_commercial_status in (
      'not_applicable','pending_review','grandfathered','removed'
    )
  );

create table if not exists public.hosted_address_migration_reviews (
  id bigint generated by default as identity primary key,
  website_settings_id integer not null references public.website_settings(id) on delete cascade,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  original_subdomain text,
  original_standard_path_slug text,
  normalized_standard_path_slug text not null,
  material_change boolean not null default false,
  collision_resolved boolean not null default false,
  legacy_routing_preserved boolean not null default false,
  commercial_review_state text not null check (
    commercial_review_state in ('not_applicable','pending_review','grandfathered','removed')
  ),
  publication_state text,
  review_reason text not null,
  resolved_by_user_id integer references public.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (website_settings_id)
);

create or replace function public.normalize_website_standard_path_slug(
  p_value text,
  p_tenant_id integer
) returns text
language plpgsql
immutable
set search_path = public
as $$
declare
  v_slug text;
begin
  v_slug := lower(trim(coalesce(p_value, '')));
  v_slug := regexp_replace(v_slug, '[^a-z0-9]+', '-', 'g');
  v_slug := trim(both '-' from v_slug);
  v_slug := left(v_slug, 63);
  v_slug := trim(both '-' from v_slug);

  if v_slug = '' or v_slug in (
    'api','admin','auth','billing','dashboard','forms','health','login','logout',
    'pricing','privacy-policy','public','signup','site','static',
    'terms-and-conditions','www'
  ) then
    v_slug := 'site-' || p_tenant_id::text;
  end if;

  return v_slug;
end;
$$;

-- Build all assignments before touching the table. This avoids transient
-- uniqueness failures and makes collision resolution stable by tenant id.
create temporary table website_standard_path_slug_map (
  website_settings_id integer primary key,
  tenant_id integer not null,
  original_subdomain text,
  original_standard_path_slug text,
  normalized_standard_path_slug text not null unique,
  material_change boolean not null,
  collision_resolved boolean not null
) on commit drop;

do $$
declare
  settings_row record;
  v_source text;
  v_base text;
  v_candidate text;
  v_suffix text;
  v_collision_index integer;
  v_force_suffix boolean;
  v_had_collision boolean;
begin
  for settings_row in
    select id, tenant_id, subdomain, standard_path_slug
    from public.website_settings
    order by tenant_id, id
  loop
    v_source := coalesce(
      nullif(trim(settings_row.standard_path_slug), ''),
      nullif(trim(settings_row.subdomain), ''),
      ''
    );
    v_base := public.normalize_website_standard_path_slug(
      v_source,
      settings_row.tenant_id
    );
    v_candidate := v_base;
    v_force_suffix := false;
    v_had_collision := false;
    v_collision_index := 0;

    -- A legacy identifier must not take another tenant's deterministic
    -- site-<tenant_id> fallback, even if that fallback row is processed later.
    if v_candidate ~ '^site-[0-9]+$'
      and v_candidate <> 'site-' || settings_row.tenant_id::text
      and exists (
        select 1
        from public.website_settings fallback_owner
        where 'site-' || fallback_owner.tenant_id::text = v_candidate
      )
    then
      v_force_suffix := true;
    end if;

    while v_force_suffix or exists (
      select 1
      from website_standard_path_slug_map assigned
      where lower(assigned.normalized_standard_path_slug) = lower(v_candidate)
    ) loop
      v_had_collision := true;
      v_force_suffix := false;
      v_collision_index := v_collision_index + 1;
      v_suffix := '-' || settings_row.tenant_id::text
        || case when v_collision_index > 1 then '-' || v_collision_index::text else '' end;
      v_candidate := trim(both '-' from left(v_base, 63 - length(v_suffix))) || v_suffix;
    end loop;

    insert into website_standard_path_slug_map (
      website_settings_id,
      tenant_id,
      original_subdomain,
      original_standard_path_slug,
      normalized_standard_path_slug,
      material_change,
      collision_resolved
    ) values (
      settings_row.id,
      settings_row.tenant_id,
      settings_row.subdomain,
      settings_row.standard_path_slug,
      v_candidate,
      v_candidate is distinct from nullif(lower(trim(v_source)), ''),
      v_had_collision
    );
  end loop;
end
$$;

update public.website_settings settings
set
  standard_path_slug = mapping.normalized_standard_path_slug,
  legacy_subdomain_routing_preserved = (
    nullif(trim(mapping.original_subdomain), '') is not null
  ),
  branded_subdomain_commercial_status = case
    when nullif(trim(mapping.original_subdomain), '') is not null
      and settings.branded_subdomain_commercial_status = 'not_applicable'
      then 'pending_review'
    else settings.branded_subdomain_commercial_status
  end
from website_standard_path_slug_map mapping
where settings.id = mapping.website_settings_id;

insert into public.hosted_address_migration_reviews (
  website_settings_id,
  tenant_id,
  original_subdomain,
  original_standard_path_slug,
  normalized_standard_path_slug,
  material_change,
  collision_resolved,
  legacy_routing_preserved,
  commercial_review_state,
  publication_state,
  review_reason
)
select
  mapping.website_settings_id,
  mapping.tenant_id,
  mapping.original_subdomain,
  mapping.original_standard_path_slug,
  mapping.normalized_standard_path_slug,
  mapping.material_change,
  mapping.collision_resolved,
  nullif(trim(mapping.original_subdomain), '') is not null,
  settings.branded_subdomain_commercial_status,
  coalesce(project.status, 'unpublished'),
  case
    when mapping.collision_resolved then 'Normalized identifier collision resolved deterministically'
    when mapping.material_change then 'Legacy identifier normalized for the standard hosted path'
    when nullif(trim(mapping.original_subdomain), '') is not null then 'Legacy branded route retained pending commercial review'
    else 'Deterministic standard hosted path assigned'
  end
from website_standard_path_slug_map mapping
join public.website_settings settings on settings.id = mapping.website_settings_id
left join public.builder_projects project on project.id = settings.published_project_id
on conflict (website_settings_id) do nothing;

alter table public.website_settings
  alter column standard_path_slug set not null;

alter table public.website_settings
  drop constraint if exists website_settings_standard_path_slug_check;

alter table public.website_settings
  add constraint website_settings_standard_path_slug_check check (
    standard_path_slug ~ '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$'
    and standard_path_slug not in (
      'api','admin','auth','billing','dashboard','forms','health','login','logout',
      'pricing','privacy-policy','public','signup','site','static','terms-and-conditions',
      'www'
    )
  ) not valid;

alter table public.website_settings
  validate constraint website_settings_standard_path_slug_check;

create unique index if not exists website_settings_standard_path_slug_unique_idx
on public.website_settings (lower(standard_path_slug));

create or replace function public.set_website_standard_path_slug()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.standard_path_slug := public.normalize_website_standard_path_slug(
    coalesce(
      nullif(trim(new.standard_path_slug), ''),
      nullif(trim(new.subdomain), '')
    ),
    new.tenant_id
  );
  return new;
end;
$$;

drop trigger if exists set_website_standard_path_slug on public.website_settings;
create trigger set_website_standard_path_slug
before insert or update of standard_path_slug, tenant_id
on public.website_settings
for each row execute function public.set_website_standard_path_slug();

create table if not exists public.commercial_usage_monthly (
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  period_key text not null check (period_key ~ '^[0-9]{4}-[0-9]{2}$'),
  forms_created bigint not null default 0 check (forms_created >= 0),
  form_submissions bigint not null default 0 check (form_submissions >= 0),
  reservation_requests bigint not null default 0 check (reservation_requests >= 0),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, period_key)
);

create table if not exists public.ai_token_model_multipliers (
  version text not null,
  provider text not null,
  model_pattern text not null,
  input_multiplier_micros integer not null check (input_multiplier_micros >= 0),
  cached_input_multiplier_micros integer not null check (cached_input_multiplier_micros >= 0),
  output_multiplier_micros integer not null check (output_multiplier_micros >= 0),
  active boolean not null default true,
  effective_at timestamptz not null default now(),
  primary key (version, provider, model_pattern)
);

insert into public.ai_token_model_multipliers (
  version, provider, model_pattern,
  input_multiplier_micros, cached_input_multiplier_micros, output_multiplier_micros
) values
  ('v1','gemini','gemini-2.5-flash',1000000,250000,2000000),
  ('v1','mock','mock',1000000,1000000,1000000),
  ('v1','*','*',1000000,1000000,2000000)
on conflict (version, provider, model_pattern) do nothing;

create table if not exists public.ai_token_allocations (
  id bigint generated by default as identity primary key,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  period_key text not null check (period_key ~ '^[0-9]{4}-[0-9]{2}$'),
  allocation_type text not null check (allocation_type in ('monthly_package','token_pack','admin_adjustment','migration')),
  product_id text,
  standard_tokens bigint not null check (standard_tokens > 0),
  state text not null default 'active' check (state in ('active','revoked','expired')),
  idempotency_key text not null,
  assigned_by_user_id integer references public.users(id) on delete set null,
  reason text,
  created_at timestamptz not null default now(),
  unique (tenant_id, idempotency_key)
);

create index if not exists ai_token_allocations_tenant_period_idx
on public.ai_token_allocations (tenant_id, period_key, state);

create unique index if not exists ai_token_allocations_one_monthly_package_idx
on public.ai_token_allocations (tenant_id, period_key)
where allocation_type='monthly_package' and state='active';

create table if not exists public.ai_token_reservations (
  request_id text primary key,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  user_id integer not null references public.users(id) on delete restrict,
  period_key text not null check (period_key ~ '^[0-9]{4}-[0-9]{2}$'),
  operation_type text not null,
  reserved_standard_tokens bigint not null check (reserved_standard_tokens > 0),
  finalized_standard_tokens bigint not null default 0 check (finalized_standard_tokens >= 0),
  status text not null default 'reserved' check (status in ('reserved','finalized','released','expired')),
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  finalized_at timestamptz
);

create index if not exists ai_token_reservations_tenant_period_idx
on public.ai_token_reservations (tenant_id, period_key, status, expires_at);

create table if not exists public.ai_token_ledger (
  id bigint generated by default as identity primary key,
  request_id text not null unique references public.ai_token_reservations(request_id) on delete restrict,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  user_id integer not null references public.users(id) on delete restrict,
  period_key text not null check (period_key ~ '^[0-9]{4}-[0-9]{2}$'),
  provider text not null,
  model text not null,
  multiplier_version text not null,
  input_tokens bigint not null default 0 check (input_tokens >= 0),
  cached_input_tokens bigint not null default 0 check (cached_input_tokens >= 0),
  output_tokens bigint not null default 0 check (output_tokens >= 0),
  total_provider_tokens bigint not null default 0 check (total_provider_tokens >= 0),
  standard_tokens bigint not null default 0 check (standard_tokens >= 0),
  covered_standard_tokens bigint not null default 0 check (covered_standard_tokens >= 0),
  reservation_applied_tokens bigint not null default 0 check (reservation_applied_tokens >= 0),
  additional_applied_tokens bigint not null default 0 check (additional_applied_tokens >= 0),
  deficit_standard_tokens bigint not null default 0 check (deficit_standard_tokens >= 0),
  operation_type text not null,
  request_status text not null check (request_status in ('succeeded','failed','timeout','provider_error')),
  usage_source text not null check (usage_source in ('provider','server_estimate','provider_partial')),
  estimated boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists ai_token_ledger_tenant_period_idx
on public.ai_token_ledger (tenant_id, period_key, created_at);

create or replace function public.increment_commercial_usage(
  p_tenant_id integer,
  p_period_key text,
  p_metric text,
  p_delta integer default 1
) returns table (
  forms_created bigint,
  form_submissions bigint,
  reservation_requests bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_delta integer := greatest(coalesce(p_delta, 0), 0);
begin
  if p_metric not in ('forms_created','form_submissions','reservation_requests') then
    raise exception using errcode='P0001', message='commercial_usage_metric_invalid';
  end if;

  insert into public.commercial_usage_monthly (tenant_id, period_key)
  values (p_tenant_id, p_period_key)
  on conflict (tenant_id, period_key) do nothing;

  if p_metric = 'forms_created' then
    update public.commercial_usage_monthly set forms_created = forms_created + v_delta, updated_at = now()
    where tenant_id = p_tenant_id and period_key = p_period_key;
  elsif p_metric = 'form_submissions' then
    update public.commercial_usage_monthly set form_submissions = form_submissions + v_delta, updated_at = now()
    where tenant_id = p_tenant_id and period_key = p_period_key;
  else
    update public.commercial_usage_monthly set reservation_requests = reservation_requests + v_delta, updated_at = now()
    where tenant_id = p_tenant_id and period_key = p_period_key;
  end if;

  return query select u.forms_created, u.form_submissions, u.reservation_requests
  from public.commercial_usage_monthly u
  where u.tenant_id = p_tenant_id and u.period_key = p_period_key;
end;
$$;

create or replace function public.ensure_ai_monthly_allocation(
  p_tenant_id integer,
  p_period_key text,
  p_product_id text,
  p_standard_tokens bigint,
  p_idempotency_key text,
  p_reason text
) returns setof public.ai_token_allocations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing public.ai_token_allocations%rowtype;
  v_created public.ai_token_allocations%rowtype;
begin
  if p_product_id not in ('ai_analytics_starter','ai_analytics_plus')
    or p_standard_tokens <= 0
    or p_period_key !~ '^[0-9]{4}-[0-9]{2}$'
  then
    raise exception using errcode='P0001',message='ai_monthly_allocation_invalid';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_tenant_id::text || ':' || p_period_key,0)
  );
  if not exists (
    select 1
    from public.tenant_addons addon
    where addon.tenant_id=p_tenant_id
      and addon.addon_id=p_product_id
      and addon.state='active'
      and addon.billing_interval='month'
  ) then
    raise exception using errcode='P0001',message='ai_monthly_package_not_active';
  end if;
  select * into v_existing
  from public.ai_token_allocations
  where tenant_id=p_tenant_id and idempotency_key=p_idempotency_key
  limit 1;
  if found then
    if v_existing.product_id<>p_product_id
      or v_existing.period_key<>p_period_key
      or v_existing.standard_tokens<>p_standard_tokens
      or v_existing.allocation_type<>'monthly_package'
    then
      raise exception using errcode='P0001',message='ai_monthly_allocation_idempotency_conflict';
    end if;
    if v_existing.state<>'active' then
      update public.ai_token_allocations
      set state='revoked'
      where tenant_id=p_tenant_id
        and period_key=p_period_key
        and allocation_type='monthly_package'
        and state='active'
        and id<>v_existing.id;
      update public.ai_token_allocations
      set state='active'
      where id=v_existing.id
      returning * into v_existing;
    end if;
    return next v_existing;
    return;
  end if;

  update public.ai_token_allocations
  set state='revoked'
  where tenant_id=p_tenant_id
    and period_key=p_period_key
    and allocation_type='monthly_package'
    and state='active';

  insert into public.ai_token_allocations (
    tenant_id,period_key,allocation_type,product_id,standard_tokens,state,
    idempotency_key,reason
  ) values (
    p_tenant_id,p_period_key,'monthly_package',p_product_id,p_standard_tokens,
    'active',p_idempotency_key,p_reason
  ) returning * into v_created;
  return next v_created;
end;
$$;

create or replace function public.reserve_ai_standard_tokens(
  p_tenant_id integer,
  p_user_id integer,
  p_period_key text,
  p_request_id text,
  p_operation_type text,
  p_reserved_tokens bigint,
  p_expires_at timestamptz
) returns table (
  accepted boolean,
  request_id text,
  allocated_tokens bigint,
  used_tokens bigint,
  reserved_tokens bigint,
  remaining_tokens bigint,
  reservation_status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_allocated bigint;
  v_used bigint;
  v_reserved bigint;
  v_existing public.ai_token_reservations%rowtype;
begin
  if p_reserved_tokens <= 0
    or length(trim(p_request_id)) < 8
    or p_expires_at <= now()
    or p_expires_at > now() + interval '1 hour'
  then
    raise exception using errcode='P0001', message='ai_token_reservation_invalid';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_tenant_id::text || ':' || p_period_key, 0));

  select * into v_existing from public.ai_token_reservations where ai_token_reservations.request_id = p_request_id;
  if found then
    if v_existing.tenant_id <> p_tenant_id or v_existing.user_id <> p_user_id
      or v_existing.period_key <> p_period_key or v_existing.operation_type <> p_operation_type then
      raise exception using errcode='P0001', message='ai_token_idempotency_conflict';
    end if;
    if v_existing.status='reserved' and v_existing.expires_at <= now() then
      update public.ai_token_reservations
      set status='expired'
      where ai_token_reservations.request_id=p_request_id
        and status='reserved';
      v_existing.status := 'expired';
    end if;
    select coalesce(sum(standard_tokens),0) into v_allocated
      from public.ai_token_allocations where tenant_id=p_tenant_id and period_key=p_period_key and state='active';
    select coalesce(sum(standard_tokens),0) into v_used
      from public.ai_token_ledger where tenant_id=p_tenant_id and period_key=p_period_key;
    select coalesce(sum(reserved_standard_tokens),0) into v_reserved
      from public.ai_token_reservations
      where tenant_id=p_tenant_id and period_key=p_period_key and status='reserved' and expires_at > now();
    return query select (
        v_existing.status = 'reserved' and v_existing.expires_at > now()
      ), v_existing.request_id,
      v_allocated, v_used, v_reserved, greatest(v_allocated-v_used-v_reserved,0),
      v_existing.status;
    return;
  end if;

  update public.ai_token_reservations set status='expired'
  where tenant_id=p_tenant_id and period_key=p_period_key and status='reserved' and expires_at <= now();

  select coalesce(sum(standard_tokens),0) into v_allocated
    from public.ai_token_allocations where tenant_id=p_tenant_id and period_key=p_period_key and state='active';
  select coalesce(sum(standard_tokens),0) into v_used
    from public.ai_token_ledger where tenant_id=p_tenant_id and period_key=p_period_key;
  select coalesce(sum(reserved_standard_tokens),0) into v_reserved
    from public.ai_token_reservations
    where tenant_id=p_tenant_id and period_key=p_period_key and status='reserved' and expires_at > now();

  if v_allocated-v_used-v_reserved < p_reserved_tokens then
    return query select false, p_request_id, v_allocated, v_used, v_reserved,
      greatest(v_allocated-v_used-v_reserved,0), 'rejected'::text;
    return;
  end if;

  insert into public.ai_token_reservations (
    request_id,tenant_id,user_id,period_key,operation_type,reserved_standard_tokens,expires_at
  ) values (
    p_request_id,p_tenant_id,p_user_id,p_period_key,p_operation_type,p_reserved_tokens,p_expires_at
  );
  v_reserved := v_reserved + p_reserved_tokens;
  return query select true,p_request_id,v_allocated,v_used,v_reserved,
    greatest(v_allocated-v_used-v_reserved,0),'reserved'::text;
end;
$$;

create or replace function public.finalize_ai_standard_tokens(
  p_request_id text,
  p_provider text,
  p_model text,
  p_multiplier_version text,
  p_input_tokens bigint,
  p_cached_input_tokens bigint,
  p_output_tokens bigint,
  p_total_provider_tokens bigint,
  p_standard_tokens bigint,
  p_request_status text,
  p_usage_source text,
  p_estimated boolean
) returns table (
  standard_tokens bigint,
  covered_standard_tokens bigint,
  reservation_applied_tokens bigint,
  additional_applied_tokens bigint,
  deficit_standard_tokens bigint,
  remaining_tokens bigint,
  reservation_status text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reservation public.ai_token_reservations%rowtype;
  v_existing public.ai_token_ledger%rowtype;
  v_allocated bigint;
  v_used bigint;
  v_other_reserved bigint;
  v_available_for_request bigint;
  v_covered bigint;
  v_reservation_applied bigint;
  v_additional_applied bigint;
  v_deficit bigint;
begin
  -- Read the tenant/period before locking, then use the same namespace as
  -- reservation. Re-read the row FOR UPDATE after the advisory lock so reserve
  -- and finalize operations cannot overspend concurrently or deadlock.
  select * into v_reservation
  from public.ai_token_reservations
  where request_id=p_request_id;
  if not found then raise exception using errcode='P0001', message='ai_token_reservation_missing'; end if;

  perform pg_advisory_xact_lock(
    hashtextextended(v_reservation.tenant_id::text || ':' || v_reservation.period_key, 0)
  );
  select * into v_reservation
  from public.ai_token_reservations
  where request_id=p_request_id
  for update;

  select * into v_existing
  from public.ai_token_ledger
  where request_id=p_request_id;
  if found then
    return query select
      v_existing.standard_tokens,
      v_existing.covered_standard_tokens,
      v_existing.reservation_applied_tokens,
      v_existing.additional_applied_tokens,
      v_existing.deficit_standard_tokens,
      greatest((
        select coalesce(sum(allocation.standard_tokens),0)
        from public.ai_token_allocations allocation
        where allocation.tenant_id=v_existing.tenant_id
          and allocation.period_key=v_existing.period_key
          and allocation.state='active'
      ) - (
        select coalesce(sum(ledger.standard_tokens),0)
        from public.ai_token_ledger ledger
        where ledger.tenant_id=v_existing.tenant_id
          and ledger.period_key=v_existing.period_key
      ) - (
        select coalesce(sum(reservation.reserved_standard_tokens),0)
        from public.ai_token_reservations reservation
        where reservation.tenant_id=v_existing.tenant_id
          and reservation.period_key=v_existing.period_key
          and reservation.status='reserved'
          and reservation.expires_at > now()
      ),0)::bigint,
      'finalized'::text;
    return;
  end if;

  -- Finalization is service-role-only and may record a provider call after an
  -- expiry or explicit release. This preserves incurred usage; it does not
  -- restore or create spendable capacity.
  if v_reservation.status not in ('reserved','released','expired') then
    raise exception using errcode='P0001', message='ai_token_reservation_not_finalizable';
  end if;
  if least(p_input_tokens,p_cached_input_tokens,p_output_tokens,p_total_provider_tokens,p_standard_tokens) < 0 then
    raise exception using errcode='P0001', message='ai_token_finalization_invalid';
  end if;

  update public.ai_token_reservations
  set status='expired'
  where tenant_id=v_reservation.tenant_id
    and period_key=v_reservation.period_key
    and request_id<>p_request_id
    and status='reserved'
    and expires_at <= now();

  select coalesce(sum(allocation.standard_tokens),0) into v_allocated
  from public.ai_token_allocations allocation
  where allocation.tenant_id=v_reservation.tenant_id
    and allocation.period_key=v_reservation.period_key
    and allocation.state='active';

  select coalesce(sum(ledger.standard_tokens),0) into v_used
  from public.ai_token_ledger ledger
  where ledger.tenant_id=v_reservation.tenant_id
    and ledger.period_key=v_reservation.period_key;

  select coalesce(sum(reservation.reserved_standard_tokens),0) into v_other_reserved
  from public.ai_token_reservations reservation
  where reservation.tenant_id=v_reservation.tenant_id
    and reservation.period_key=v_reservation.period_key
    and reservation.request_id<>p_request_id
    and reservation.status='reserved'
    and reservation.expires_at > now();

  v_available_for_request := greatest(v_allocated-v_used-v_other_reserved,0);
  v_covered := least(p_standard_tokens,v_available_for_request);
  v_reservation_applied := least(
    v_covered,
    v_reservation.reserved_standard_tokens
  );
  v_additional_applied := greatest(v_covered-v_reservation_applied,0);
  v_deficit := greatest(p_standard_tokens-v_covered,0);

  insert into public.ai_token_ledger (
    request_id,tenant_id,user_id,period_key,provider,model,multiplier_version,
    input_tokens,cached_input_tokens,output_tokens,total_provider_tokens,standard_tokens,
    covered_standard_tokens,reservation_applied_tokens,additional_applied_tokens,
    deficit_standard_tokens,
    operation_type,request_status,usage_source,estimated
  ) values (
    p_request_id,v_reservation.tenant_id,v_reservation.user_id,v_reservation.period_key,
    p_provider,p_model,p_multiplier_version,p_input_tokens,p_cached_input_tokens,p_output_tokens,
    p_total_provider_tokens,p_standard_tokens,v_covered,v_reservation_applied,
    v_additional_applied,v_deficit,v_reservation.operation_type,p_request_status,
    p_usage_source,p_estimated
  );

  update public.ai_token_reservations
  set status='finalized',finalized_standard_tokens=p_standard_tokens,finalized_at=now()
  where request_id=p_request_id;

  return query select
    p_standard_tokens,
    v_covered,
    v_reservation_applied,
    v_additional_applied,
    v_deficit,
    greatest(v_allocated-v_used-v_covered-v_other_reserved,0),
    'finalized'::text;
end;
$$;

create or replace function public.release_ai_standard_tokens(p_request_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reservation public.ai_token_reservations%rowtype;
begin
  select * into v_reservation
  from public.ai_token_reservations
  where request_id=p_request_id;
  if not found then return false; end if;
  perform pg_advisory_xact_lock(
    hashtextextended(v_reservation.tenant_id::text || ':' || v_reservation.period_key, 0)
  );
  update public.ai_token_reservations set status='released',finalized_at=now()
  where request_id=p_request_id and status='reserved';
  return found;
end;
$$;

create or replace function public.assign_commercial_subscription(
  p_tenant_id integer,
  p_plan_id text,
  p_state text,
  p_catalog_version text,
  p_price_minor integer,
  p_admin_user_id integer,
  p_reason text,
  p_idempotency_key text
) returns setof public.tenant_subscriptions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing public.tenant_subscriptions%rowtype;
  v_created public.tenant_subscriptions%rowtype;
begin
  perform pg_advisory_xact_lock(hashtextextended('commercial-plan:' || p_tenant_id::text, 0));
  select * into v_existing from public.tenant_subscriptions
  where tenant_id=p_tenant_id
    and migration_provenance->>'idempotency_key'=p_idempotency_key
  limit 1;
  if found then return next v_existing; return; end if;

  if p_state='active' then
    update public.tenant_subscriptions
    set state='scheduled_change',updated_at=now(),
      migration_provenance=migration_provenance || jsonb_build_object('replaced_by',p_idempotency_key)
    where tenant_id=p_tenant_id and state='active';
  end if;

  insert into public.tenant_subscriptions (
    tenant_id,plan_id,state,catalog_version,currency,price_minor,billing_interval,
    source,activated_by_user_id,migration_provenance,updated_at
  ) values (
    p_tenant_id,p_plan_id,p_state,p_catalog_version,'USD',p_price_minor,'month',
    'admin',p_admin_user_id,jsonb_build_object(
      'idempotency_key',p_idempotency_key,'reason',p_reason,'assigned_at',now()
    ),now()
  ) returning * into v_created;
  return next v_created;
end;
$$;

create or replace function public.assign_commercial_addon(
  p_tenant_id integer,
  p_addon_id text,
  p_quantity integer,
  p_state text,
  p_catalog_version text,
  p_price_minor integer,
  p_billing_interval text,
  p_admin_user_id integer,
  p_reason text,
  p_idempotency_key text
) returns setof public.tenant_addons
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing public.tenant_addons%rowtype;
  v_created public.tenant_addons%rowtype;
  v_lock_group text;
begin
  v_lock_group := case
    when p_addon_id in ('ai_analytics_starter','ai_analytics_plus')
      then 'ai-analytics-package'
    else p_addon_id
  end;
  perform pg_advisory_xact_lock(
    hashtextextended(
      'commercial-addon:' || p_tenant_id::text || ':' || v_lock_group,
      0
    )
  );
  select * into v_existing from public.tenant_addons
  where tenant_id=p_tenant_id and idempotency_key=p_idempotency_key limit 1;
  if found then
    if v_existing.addon_id<>p_addon_id or v_existing.quantity<>p_quantity or v_existing.state<>p_state then
      raise exception using errcode='P0001',message='commercial_addon_idempotency_conflict';
    end if;
    return next v_existing; return;
  end if;

  if p_state='active' and p_billing_interval='month' then
    update public.tenant_addons set state='scheduled_change',updated_at=now()
    where tenant_id=p_tenant_id and addon_id=p_addon_id and state='active' and billing_interval='month';
    if p_addon_id in ('ai_analytics_starter','ai_analytics_plus') then
      update public.tenant_addons set state='scheduled_change',updated_at=now()
      where tenant_id=p_tenant_id and addon_id in ('ai_analytics_starter','ai_analytics_plus')
        and addon_id<>p_addon_id and state='active';
    end if;
  end if;

  insert into public.tenant_addons (
    tenant_id,addon_id,quantity,state,catalog_version,price_minor,currency,
    billing_interval,source,idempotency_key,assigned_by_user_id,updated_at
  ) values (
    p_tenant_id,p_addon_id,p_quantity,p_state,p_catalog_version,p_price_minor,'USD',
    p_billing_interval,'admin',p_idempotency_key,p_admin_user_id,now()
  ) returning * into v_created;
  return next v_created;
end;
$$;

alter table public.tenant_subscriptions enable row level security;
alter table public.tenant_addons enable row level security;
alter table public.billing_addon_requests enable row level security;
alter table public.legacy_billing_migration_reviews enable row level security;
alter table public.hosted_address_migration_reviews enable row level security;
alter table public.commercial_usage_monthly enable row level security;
alter table public.ai_token_model_multipliers enable row level security;
alter table public.ai_token_allocations enable row level security;
alter table public.ai_token_reservations enable row level security;
alter table public.ai_token_ledger enable row level security;

revoke all on table public.tenant_subscriptions, public.tenant_addons,
  public.billing_addon_requests, public.legacy_billing_migration_reviews,
  public.hosted_address_migration_reviews,
  public.commercial_usage_monthly, public.ai_token_model_multipliers,
  public.ai_token_allocations, public.ai_token_reservations, public.ai_token_ledger
from anon, authenticated;

grant select, insert, update, delete on table public.tenant_subscriptions, public.tenant_addons,
  public.billing_addon_requests, public.legacy_billing_migration_reviews,
  public.hosted_address_migration_reviews,
  public.commercial_usage_monthly, public.ai_token_model_multipliers,
  public.ai_token_allocations, public.ai_token_reservations, public.ai_token_ledger
to service_role;

grant usage, select on sequence
  public.tenant_subscriptions_id_seq,
  public.tenant_addons_id_seq,
  public.billing_addon_requests_id_seq,
  public.hosted_address_migration_reviews_id_seq,
  public.ai_token_allocations_id_seq,
  public.ai_token_ledger_id_seq
to service_role;

revoke all on function public.increment_commercial_usage(integer,text,text,integer) from public, anon, authenticated;
revoke all on function public.ensure_ai_monthly_allocation(integer,text,text,bigint,text,text) from public, anon, authenticated;
revoke all on function public.reserve_ai_standard_tokens(integer,integer,text,text,text,bigint,timestamptz) from public, anon, authenticated;
revoke all on function public.finalize_ai_standard_tokens(text,text,text,text,bigint,bigint,bigint,bigint,bigint,text,text,boolean) from public, anon, authenticated;
revoke all on function public.release_ai_standard_tokens(text) from public, anon, authenticated;
revoke all on function public.assign_commercial_subscription(integer,text,text,text,integer,integer,text,text) from public, anon, authenticated;
revoke all on function public.assign_commercial_addon(integer,text,integer,text,text,integer,text,integer,text,text) from public, anon, authenticated;
grant execute on function public.increment_commercial_usage(integer,text,text,integer) to service_role;
grant execute on function public.ensure_ai_monthly_allocation(integer,text,text,bigint,text,text) to service_role;
grant execute on function public.reserve_ai_standard_tokens(integer,integer,text,text,text,bigint,timestamptz) to service_role;
grant execute on function public.finalize_ai_standard_tokens(text,text,text,text,bigint,bigint,bigint,bigint,bigint,text,text,boolean) to service_role;
grant execute on function public.release_ai_standard_tokens(text) to service_role;
grant execute on function public.assign_commercial_subscription(integer,text,text,text,integer,integer,text,text) to service_role;
grant execute on function public.assign_commercial_addon(integer,text,integer,text,text,integer,text,integer,text,text) to service_role;

with legacy_summary as (
  select
    f.tenant_id,
    jsonb_agg(jsonb_build_object(
      'feature_id',f.id,'subscription_type',f.subscription_type,'plan',f.plan,
      'builder_type',f.builder_type,'payment_status',f.payment_status,
      'updated_at',f.updated_at
    ) order by f.updated_at desc, f.id desc) as legacy_records,
    count(*) filter (where lower(trim(f.payment_status))='active') as active_count,
    min(f.id) filter (where lower(trim(f.payment_status))='active') as single_active_id
  from public.features f
  group by f.tenant_id
),
active_record as (
  select
    summary.tenant_id,
    summary.legacy_records,
    summary.active_count,
    case when summary.active_count=1 then active_feature.id else null end as active_feature_id,
    case when summary.active_count=1 then jsonb_build_object(
      'feature_id',active_feature.id,
      'subscription_type',active_feature.subscription_type,
      'plan',active_feature.plan,
      'builder_type',active_feature.builder_type,
      'payment_status',active_feature.payment_status,
      'updated_at',active_feature.updated_at
    ) else null end as active_feature,
    case
      when summary.active_count<>1 then null
      when lower(trim(active_feature.plan))='complete' then 'business_plus'
      when lower(trim(active_feature.plan))='cms_plus' then 'business'
      when lower(trim(active_feature.plan))='cms' then 'website'
      when lower(trim(active_feature.plan))='forms_data' then 'forms'
      when lower(trim(active_feature.subscription_type))='individual_builder'
        and lower(trim(coalesce(active_feature.builder_type,'')))='reservation'
        then 'business_plus'
      when lower(trim(active_feature.subscription_type))='individual_builder'
        and lower(trim(coalesce(active_feature.builder_type,'')))='website'
        then 'website'
      when lower(trim(active_feature.subscription_type))='individual_builder'
        and lower(trim(coalesce(active_feature.builder_type,''))) in ('forms','data')
        then 'forms'
      else null
    end as recommended_plan_id
  from legacy_summary summary
  left join public.features active_feature
    on active_feature.id=summary.single_active_id
    and summary.active_count=1
)
insert into public.legacy_billing_migration_reviews (
  tenant_id,
  legacy_records,
  active_legacy_feature_id,
  active_legacy_record,
  recommended_plan_id,
  migration_state,
  reason
)
select
  record.tenant_id,
  record.legacy_records,
  record.active_feature_id,
  record.active_feature,
  record.recommended_plan_id,
  case
    when record.active_count=1 and record.recommended_plan_id is not null
      then 'mapped'
    else 'review_required'
  end,
  case
    when record.active_count=0 then 'No active legacy billing record; no canonical mapping recommended'
    when record.active_count>1 then 'Multiple active legacy billing records require review'
    when record.recommended_plan_id is null then 'Unknown or ambiguous active legacy label requires review'
    else 'Recommendation derived solely from the exact active legacy billing record'
  end
from active_record record
on conflict (tenant_id) do nothing;

notify pgrst, 'reload schema';
commit;

-- Rollback note: application rollback may leave these additive tables/columns in
-- place safely. Do not drop them until all token reservations are finalized and
-- canonical subscription/add-on history has been exported.
