begin;

create table if not exists public.workspace_screen_time_daily (
  id bigint generated by default as identity primary key,
  tenant_id integer not null references public.tenants(tenant_id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  activity_date date not null,
  active_seconds integer not null default 0
    check (active_seconds >= 0 and active_seconds <= 86400),
  last_recorded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (tenant_id, user_id, activity_date)
);

create index if not exists workspace_screen_time_tenant_date_idx
  on public.workspace_screen_time_daily (tenant_id, activity_date desc);

alter table public.workspace_screen_time_daily enable row level security;
revoke all on table public.workspace_screen_time_daily from anon, authenticated;
grant all on table public.workspace_screen_time_daily to service_role;
grant usage, select on sequence public.workspace_screen_time_daily_id_seq to service_role;

create or replace function public.record_workspace_screen_time(
  p_tenant_id integer,
  p_user_id integer,
  p_activity_date date,
  p_active_seconds integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_seconds integer;
begin
  safe_seconds := greatest(1, least(coalesce(p_active_seconds, 0), 60));

  if not exists (
    select 1
    from public.users u
    where u.id = p_user_id
      and (
        u.tenant_id = p_tenant_id
        or exists (
          select 1
          from public.tenant_memberships tm
          where tm.tenant_id = p_tenant_id
            and tm.user_id = p_user_id
            and tm.status = 'active'
        )
        or exists (
          select 1
          from public.tenant_site_memberships tsm
          where tsm.tenant_id = p_tenant_id
            and tsm.user_id = p_user_id
            and tsm.status = 'active'
        )
      )
  ) then
    raise exception 'screen_time_user_tenant_mismatch';
  end if;

  insert into public.workspace_screen_time_daily (
    tenant_id, user_id, activity_date, active_seconds, last_recorded_at
  )
  values (
    p_tenant_id, p_user_id, p_activity_date, safe_seconds, now()
  )
  on conflict (tenant_id, user_id, activity_date)
  do update set
    active_seconds = least(
      86400,
      public.workspace_screen_time_daily.active_seconds + excluded.active_seconds
    ),
    last_recorded_at = now();
end;
$$;

revoke all on function public.record_workspace_screen_time(integer,integer,date,integer)
  from public, anon, authenticated;
grant execute on function public.record_workspace_screen_time(integer,integer,date,integer)
  to service_role;

do $$
declare
  v_schema_version public.application_schema_state.schema_version%TYPE;
begin
  select schema_version
  into v_schema_version
  from public.application_schema_state
  where contract_key = 'core'
  for update;

  if v_schema_version is null then
    raise exception using
      errcode = 'P0001',
      message = 'migration_092_schema_state_missing';
  end if;

  if v_schema_version <> 91 then
    raise exception using
      errcode = 'P0001',
      message = format(
        'migration_092_expected_schema_91_got_%s',
        v_schema_version
      );
  end if;

  update public.application_schema_state
  set schema_version = 92,
      applied_at = now()
  where contract_key = 'core';
end;
$$;

notify pgrst, 'reload schema';
commit;
