export const settingsContent = {
  en: {
    eyebrow: "Workspace settings",
    title: "Profile and website settings",
    subtitle:
      "Keep your personal details, brand, and public website information up to date.",

    profileTitle: "Your profile",
    profileDescription:
      "This information helps personalize your workspace and customer-facing pages.",
    uploadProfilePhoto: "Upload photo",
    firstName: "First name",
    lastName: "Last name",
    email: "Email",
    emailChangeUnavailable:
      "Your verified login email cannot be edited here. A secure email-change flow is coming soon.",
    phoneNumber: "Phone number",
    saveProfile: "Save profile",
    changePassword: "Change password",
    saving: "Saving...",

    websiteTitle: "Website details",
    websiteDescription:
      "Set the name, contact details, and logo visitors see on your website.",
    websiteLogoAlt: "Website logo",
    uploadLogo: "Upload logo",
    uploadingLogo: "Uploading...",
    logoUploadUnavailable:
      "Image uploads are not available yet. Use a secure HTTPS image URL for now.",
    subdomainName: "Standard hosted-address name",
    logoUrl: "Logo file",
    brandName: "Brand name",
    footerName: "Footer name",
    contactEmail: "Contact email",
    contactPhone: "Contact phone",
    websiteDescriptionLabel: "Website description",
    saveWebsite: "Save website details",

    accountSaved: "Account settings saved.",
    avatarUploaded: "Profile photo updated.",
    logoUploaded: "Logo uploaded.",
    websiteSaved: "Website settings saved.",
    accountError: "Could not update account settings.",
    avatarUploadError: "Could not upload profile photo.",
    logoUploadError: "Could not upload logo.",
    invalidAvatarType: "Please upload a PNG, JPG, or WebP image.",
    invalidLogoType: "Please upload a PNG, JPG, or WebP image.",
    avatarTooLarge: "Profile photo must be 5MB or smaller.",
    logoTooLarge: "Logo image must be 5MB or smaller.",
    invalidLogoUrl:
      "Use an HTTPS image URL or managed internal path. Data, SVG, JavaScript, and HTTP URLs are not allowed.",
    sessionExpired: "Your session expired. Please log in again.",

    userAlt: "User",
    userFallback: "U",

    firstNameRequired: "First name is required.",
    lastNameRequired: "Last name is required.",
    emailRequired: "Email is required.",
    emailInvalid: "Please enter a valid email address.",
    subdomainRequired: "A standard hosted-address name is required.",
    brandRequired: "Brand name is required.",
    contactEmailInvalid: "Please enter a valid contact email.",
    fixErrors: "Please fix the highlighted fields.",
    closeNotification: "Close notification",
    devices: {
      tab: "Devices",
      devicesTitle: "Devices",
      devicesDescription: "Manage browsers and installed Madar apps linked to your account.",
      currentDevice: "Current device",
      installedApp: "Installed app",
      browser: "Browser",
      browserDevice: "Browser device",
      notificationsEnabled: "Notifications enabled",
      notificationsDisabled: "Notifications disabled",
      notificationsBlocked: "Notifications blocked",
      noActiveSubscription: "No active Push subscription",
      permissionBlockedGuidance: "Allow notifications in your browser settings to enable them here.",
      enableNotifications: "Enable notifications",
      disableNotifications: "Disable notifications",
      lastActive: "Last active",
      today: "Today",
      yesterday: "Yesterday",
      unknownLastActive: "Unknown",
      loading: "Loading devices...",
      loadError: "Could not load devices.",
      enableError: "Could not enable notifications.",
      disableError: "Could not disable notifications.",
      removeError: "Could not remove device.",
      deviceRemoved: "Device removed.",
      removeDevice: "Remove device",
      removeConfirmTitle: "Remove this device?",
      removeConfirmMessage: "It will stop receiving Madar notifications. This does not sign that browser out or delete account data.",
      cancel: "Cancel",
      installMadar: "Install Madar",
      installDescription: "Open Madar in its own app window from this device.",
      alreadyInstalled: "Madar is running as an installed app on this device.",
      iosInstallGuidance: "To install Madar, open the Share menu and choose Add to Home Screen.",
      installUnavailable: "Installation is available when supported by your browser.",
      platforms: {
        ios: "iPhone/iPad",
        android: "Android",
        windows: "Windows",
        macos: "macOS",
        linux: "Linux",
        chromeos: "ChromeOS",
        unknown: "Browser device",
      },
      pushErrors: {
        permission_denied: "Notifications are blocked in browser settings.",
        ios_home_screen_required: "Add Madar to your Home Screen before enabling notifications.",
        secure_context_required: "Notifications require a secure connection.",
        server_not_configured: "Push notifications are not configured.",
        unsupported: "This browser does not support Push notifications.",
        android_browser_unsupported: "This Android browser does not support Push notifications.",
        installation_unavailable: "This device could not be registered. Please try again.",
      },
    },
  },

  ar: {
    eyebrow: "إعدادات مساحة العمل",
    title: "إعدادات الملف الشخصي والموقع",
    subtitle: "حدّث بياناتك الشخصية وهوية العلامة ومعلومات الموقع العامة.",

    profileTitle: "ملفك الشخصي",
    profileDescription:
      "تساعد هذه المعلومات في تخصيص مساحة عملك وصفحاتك أمام العملاء.",
    uploadProfilePhoto: "رفع صورة",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    email: "البريد الإلكتروني",
    emailChangeUnavailable:
      "لا يمكن تعديل بريد تسجيل الدخول الموثق من هنا. ستتوفر آلية آمنة لتغيير البريد قريباً.",
    phoneNumber: "رقم الهاتف",
    saveProfile: "حفظ الملف الشخصي",
    changePassword: "تغيير كلمة المرور",
    saving: "جارٍ الحفظ...",

    websiteTitle: "تفاصيل الموقع",
    websiteDescription:
      "حدد الاسم وبيانات التواصل والشعار الذي يراه زوار موقعك.",
    websiteLogoAlt: "شعار الموقع",
    uploadLogo: "رفع الملفات قريباً",
    uploadingLogo: "جارٍ الرفع...",
    logoUploadUnavailable:
      "رفع الصور غير متاح حالياً. استخدم رابط صورة HTTPS آمناً في الوقت الحالي.",
    subdomainName: "اسم عنوان الاستضافة القياسي",
    logoUrl: "ملف الشعار",
    brandName: "اسم العلامة",
    footerName: "اسم التذييل",
    contactEmail: "بريد التواصل",
    contactPhone: "هاتف التواصل",
    websiteDescriptionLabel: "وصف الموقع",
    saveWebsite: "حفظ تفاصيل الموقع",

    accountSaved: "تم حفظ إعدادات الملف الشخصي.",
    avatarUploaded: "تم تحديث صورة الملف الشخصي.",
    logoUploaded: "تم رفع الشعار.",
    websiteSaved: "تم حفظ تفاصيل الموقع.",
    accountError: "تعذر حفظ إعدادات الملف الشخصي.",
    avatarUploadError: "تعذر رفع صورة الملف الشخصي.",
    logoUploadError: "تعذر رفع الشعار.",
    invalidAvatarType: "يرجى رفع صورة بصيغة PNG أو JPG أو WebP.",
    invalidLogoType: "يرجى رفع صورة بصيغة PNG أو JPG أو WebP.",
    avatarTooLarge: "يجب ألا يتجاوز حجم صورة الملف الشخصي 5MB.",
    logoTooLarge: "يجب ألا يتجاوز حجم الشعار 5MB.",
    invalidLogoUrl:
      "استخدم رابط صورة HTTPS أو مساراً داخلياً مُداراً. روابط data و SVG و JavaScript و HTTP غير مسموحة.",
    sessionExpired: "انتهت جلستك. يرجى تسجيل الدخول مرة أخرى.",

    userAlt: "المستخدم",
    userFallback: "م",

    firstNameRequired: "الاسم الأول مطلوب.",
    lastNameRequired: "اسم العائلة مطلوب.",
    emailRequired: "البريد الإلكتروني مطلوب.",
    emailInvalid: "يرجى إدخال بريد إلكتروني صحيح.",
    subdomainRequired: "اسم عنوان الاستضافة القياسي مطلوب.",
    brandRequired: "اسم العلامة مطلوب.",
    contactEmailInvalid: "يرجى إدخال بريد تواصل صحيح.",
    fixErrors: "يرجى تصحيح الحقول المحددة.",
    closeNotification: "إغلاق الإشعار",
    devices: {
      tab: "الأجهزة",
      devicesTitle: "الأجهزة",
      devicesDescription: "أدر المتصفحات وتطبيقات مدار المثبتة والمرتبطة بحسابك.",
      currentDevice: "الجهاز الحالي",
      installedApp: "تطبيق مثبت",
      browser: "متصفح",
      browserDevice: "جهاز متصفح",
      notificationsEnabled: "الإشعارات مفعّلة",
      notificationsDisabled: "الإشعارات معطّلة",
      notificationsBlocked: "الإشعارات محظورة",
      noActiveSubscription: "لا يوجد اشتراك إشعارات نشط",
      permissionBlockedGuidance: "اسمح بالإشعارات من إعدادات المتصفح لتفعيلها هنا.",
      enableNotifications: "تفعيل الإشعارات",
      disableNotifications: "تعطيل الإشعارات",
      lastActive: "آخر نشاط",
      today: "اليوم",
      yesterday: "أمس",
      unknownLastActive: "غير معروف",
      loading: "جارٍ تحميل الأجهزة...",
      loadError: "تعذر تحميل الأجهزة.",
      enableError: "تعذر تفعيل الإشعارات.",
      disableError: "تعذر تعطيل الإشعارات.",
      removeError: "تعذر إزالة الجهاز.",
      deviceRemoved: "تمت إزالة الجهاز.",
      removeDevice: "إزالة الجهاز",
      removeConfirmTitle: "هل تريد إزالة هذا الجهاز؟",
      removeConfirmMessage: "سيتوقف عن تلقي إشعارات مدار. لن يؤدي ذلك إلى تسجيل خروج المتصفح أو حذف بيانات الحساب.",
      cancel: "إلغاء",
      installMadar: "تثبيت مدار",
      installDescription: "افتح مدار في نافذة تطبيق مستقلة على هذا الجهاز.",
      alreadyInstalled: "يعمل مدار كتطبيق مثبت على هذا الجهاز.",
      iosInstallGuidance: "لتثبيت مدار، افتح قائمة المشاركة واختر إضافة إلى الشاشة الرئيسية.",
      installUnavailable: "يتوفر التثبيت عندما يدعمه متصفحك.",
      platforms: {
        ios: "iPhone/iPad",
        android: "Android",
        windows: "Windows",
        macos: "macOS",
        linux: "Linux",
        chromeos: "ChromeOS",
        unknown: "جهاز متصفح",
      },
      pushErrors: {
        permission_denied: "الإشعارات محظورة في إعدادات المتصفح.",
        ios_home_screen_required: "أضف مدار إلى الشاشة الرئيسية قبل تفعيل الإشعارات.",
        secure_context_required: "تتطلب الإشعارات اتصالاً آمناً.",
        server_not_configured: "إشعارات Push غير مهيأة.",
        unsupported: "هذا المتصفح لا يدعم إشعارات Push.",
        android_browser_unsupported: "متصفح Android هذا لا يدعم إشعارات Push.",
        installation_unavailable: "تعذر تسجيل هذا الجهاز. حاول مرة أخرى.",
      },
    },
  },
};

export const getSettingsContent = (lang = "en") =>
  settingsContent[lang === "ar" ? "ar" : "en"];
