export const tenantRuntimeContent = {
  en: {
    legacyFieldTypes: {
      money: { label: "Price or budget", group: "Number" },
      phone: { label: "Phone", group: "Contact" },
      radio: { label: "Radio buttons", group: "Choice" },
      yesNo: { label: "Yes or no", group: "Choice" },
      status: { label: "Status selector", group: "Workflow" },
    },
    placeholders: {
      generic: [
        "",
        "Short answer",
        "Paragraph",
        "Email",
        "Phone number",
        "Website URL",
        "Number",
        "Money amount",
        "Date",
        "Time",
        "Dropdown",
        "Single choice",
        "Checkboxes",
        "Yes / No",
        "Linear scale",
        "Rating",
        "Status",
        "File upload",
      ],
      email: "name@company.com",
      phone: "+972 50 123 4567",
      website: "https://yourcompany.com",
      money: "Example: 7,500",
      number: "Example: 12",
      date: "Select a date",
      time: "Select a time",
      select: "Select an option",
      radio: "Choose one option",
      checkboxes: "Select all that apply",
      paragraph: "Briefly describe what you need...",
      name: "e.g. Sarah Haddad",
      fallback: "Type your answer",
    },
    errors: {
      requiredFallback: "A required field",
      requiredSuffix: "is required.",
      unknownFields: "This form changed after the page loaded. Refresh and try again.",
      unavailable: "This form is no longer available.",
      tooMany: "Too many submissions. Please wait and try again.",
      offline: "Network connection lost. Please try again.",
      generic: "Could not submit the form. Please try again.",
      fileTooLarge: "File is larger than {size}MB.",
    },
    runtime: {
      subdomain: "my-site",
      footerShopLinks: "Home\nSubmit Request\nReports",
      footerHelpLinks: "About Us\nPolicies\nContact",
      footerSocialLinks: "Facebook\nLinkedIn\nX\nInstagram",
      brand: "Madar",
      footerInitial: "M",
      noFormSelected: "No form selected.",
      formLanguage: "Form language",
      english: "English",
      arabic: "العربية",
      formProgress: "Form progress",
      previous: "Previous",
      next: "Next",
      pageCount: "Page {current} of {total}",
      sectionsCount: "{count} sections",
      submitting: "Submitting...",
      submit: "Submit",
      successMessage: "Thank you. Your response has been submitted.",
      fileStorageNote: "File storage will attach after backend storage is connected.",
      yes: "Yes",
      no: "No",
      embed: "Embed",
      createAccount: "Create account",
      login: "Log in",
      createAccountSubtitle: "Create your account.",
      loginSubtitle: "Access your account.",
      fullName: "Full name",
      yourName: "Your name",
      emailAddress: "Email address",
      emailPlaceholder: "name@example.com",
      password: "Password",
      passwordPlaceholder: "Enter password",
      confirmPassword: "Confirm password",
      confirmPasswordPlaceholder: "Confirm password",
      noPublishedTitle: "No published site found",
      noPublishedBody: "Save the project in Page Builder, then publish the site again.",
      defaultDescription: "An adaptive business management platform for creating and managing digital systems.",
      links: "Links",
      contact: "Contact",
      languageIcon: "◉",
      defaultLanguageLabel: "AR",
      email: "info@madar.com",
      phone: "+972599203857",
      copyright: "©",
      rights: "All rights reserved.",
      poweredBy: "Powered by Madar",
      draftPreview: "Draft preview",
      backToBuilder: "Back to builder",
      logoAlt: "{brand} logo",
      metricLabel: "Metric",
      metricFallbackValue: "0",
      metricCountLabel: "Metric {number}",
    },
  },
  ar: {
    errors: {
      requiredFallback: "هذا الحقل",
      requiredSuffix: "مطلوب.",
      fileTooLarge: "حجم الملف أكبر من {size}MB.",
    },
    runtime: {
      arabic: "العربية",
      previous: "السابق",
      next: "التالي",
      pageCount: "صفحة {current} من {total}",
      submitting: "جار الإرسال...",
      submit: "إرسال",
      fileStorageNote: "سيتم حفظ الملف بعد ربط تخزين الملفات في الخلفية.",
      yes: "نعم",
      no: "لا",
    },
  },
};

const mergeContent = (lang) => ({
  ...tenantRuntimeContent.en,
  ...(tenantRuntimeContent[lang] || {}),
  errors: {
    ...tenantRuntimeContent.en.errors,
    ...(tenantRuntimeContent[lang]?.errors || {}),
  },
  runtime: {
    ...tenantRuntimeContent.en.runtime,
    ...(tenantRuntimeContent[lang]?.runtime || {}),
  },
});

export function getTenantRuntimeContent(lang = "en") {
  return mergeContent(lang);
}
