export const pricingContent = {
  en: {
    eyebrow: "Plans and pricing",
    title: "Choose the Madar plan that fits your work",
    subtitle: "Forms, websites, data tools, and reservations with clear monthly pricing.",
    manualActivation: "Plans are manually reviewed and activated. Requesting a plan does not charge you.",
    activationTitle: "Request now, pay after approval",
    plansTitle: "Compare plans",
    plansIntro: "Every plan includes the essentials below. Move up when you need websites, deeper analytics, or reservations.",
    planLabel: "Monthly plan",
    recommended: "Recommended",
    includedTitle: "What is included",
    goodToKnow: "Good to know",
    loading: "Loading current plans...",
    catalogError: "Current pricing is temporarily unavailable.",
    requestError: "Could not save your plan request.",
    requestSaved: "Your plan request was saved for manual review. No payment was taken.",
    requestPlan: "Request this plan",
    saving: "Saving...",
    perMonth: "/month",
    hostedStorage: "Madar-hosted storage",
    oneOperator: "1 workspace operator",
    addonsTitle: "Optional add-ons",
    addonsLabel: "Extend your plan",
    availableAddons: "Available now",
    availableNow: "Available",
    upcomingAddons: "Coming next",
    comingSoon: "Coming soon",
    back: "Back",
    fairUse: "Forms, submissions, and reservation requests are not billed by count. Fair-use, anti-abuse, security, payload, rate, and platform-stability controls still apply.",
    addressNote: "Website plans include one standard madarportal.com/site/business-name address. A branded business-name.madarportal.com subdomain is $5/month.",
    exclusions: "Customer-owned custom domains and hosted business email are not currently available. AI analytics is an optional token-based add-on.",
    plans: {
      forms: {
        name: "Forms",
        summary: "Capture unlimited responses and turn them into clear, actionable insights.",
      },
      website: {
        name: "Website",
        summary: "Launch a polished website with forms, image uploads, reservations, and scheduling.",
      },
      business: {
        name: "Business",
        summary: "Grow with advanced analytics, data cleaning, charts, and export-ready insights.",
      },
      business_plus: {
        name: "Business Plus",
        summary: "Run reservations, schedules, and customer demand from one powerful workspace.",
      },
    },
    featureLabels: {
      unlimited_forms_submissions: "Unlimited forms and submissions",
      hosted_public_form_links: "Hosted public form links",
      response_management_overview: "Response management and overview",
      data_import_standard_analysis: "Data import and standard analysis",
      visual_page_builder: "Visual page builder",
      one_published_website: "1 published website",
      standard_hosted_address: "Standard hosted address",
      image_uploads_response_management: "Image uploads and response management",
      reservation_system: "Reservation builder, request management, calendar, and scheduling",
      everything_website: "Everything in Website",
      expanded_analytics: "Expanded analytics tools",
      data_cleaning: "Data cleaning",
      charts_data_exports: "Charts and data exports",
      cv_reranker: "AI-powered CV reranker",
      everything_business: "Everything in Business",
      unlimited_reservation_requests: "Unlimited reservation requests",
      reservation_management_analytics: "Advanced reservation analytics",
      internal_calendar: "Calendar and scheduling",
      priority_support: "Priority support designation",
    },
    addons: {},
  },
  ar: {
    eyebrow: "الخطط والأسعار",
    title: "اختر خطة مدار المناسبة لعملك",
    subtitle: "نماذج ومواقع وأدوات بيانات وحجوزات بأسعار شهرية واضحة.",
    manualActivation: "تتم مراجعة الخطط وتفعيلها يدوياً. طلب الخطة لا يؤدي إلى تحصيل أي مبلغ.",
    activationTitle: "اطلب الآن وادفع بعد الموافقة",
    plansTitle: "قارن بين الخطط",
    plansIntro: "تتضمن كل خطة الأساسيات الموضحة أدناه. اختر خطة أعلى عندما تحتاج إلى موقع أو تحليلات أوسع أو حجوزات.",
    planLabel: "خطة شهرية",
    recommended: "موصى بها",
    includedTitle: "المزايا المشمولة",
    goodToKnow: "معلومات مهمة",
    loading: "جارٍ تحميل الخطط الحالية...",
    catalogError: "الأسعار الحالية غير متاحة مؤقتاً.",
    requestError: "تعذر حفظ طلب الخطة.",
    requestSaved: "تم حفظ طلب خطتك للمراجعة اليدوية. لم يتم تحصيل أي مبلغ.",
    requestPlan: "طلب هذه الخطة",
    saving: "جارٍ الحفظ...",
    perMonth: "/شهرياً",
    hostedStorage: "تخزين مستضاف لدى مدار",
    oneOperator: "مشغّل واحد لمساحة العمل",
    addonsTitle: "إضافات اختيارية",
    addonsLabel: "وسّع خطتك",
    availableAddons: "متاحة الآن",
    availableNow: "متاحة",
    upcomingAddons: "قريباً على المنصة",
    comingSoon: "قريباً",
    back: "رجوع",
    fairUse: "لا تتم محاسبة النماذج أو الردود أو طلبات الحجز حسب العدد. تبقى ضوابط الاستخدام العادل ومكافحة الإساءة والأمان ومعدلات الطلبات سارية.",
    addressNote: "تشمل خطط المواقع عنواناً قياسياً على madarportal.com/site/business-name. النطاق الفرعي business-name.madarportal.com متاح مقابل 5 دولارات شهرياً.",
    exclusions: "النطاقات المملوكة للعملاء والبريد التجاري المستضاف غير متاحة حالياً. تحليلات الذكاء الاصطناعي إضافة اختيارية تعتمد على الرموز.",
    plans: {
      forms: {
        name: "النماذج",
        summary: "اجمع ردوداً غير محدودة وحوّلها إلى رؤى واضحة قابلة للتنفيذ.",
      },
      website: {
        name: "الموقع",
        summary: "أطلق موقعاً احترافياً مع النماذج ورفع الصور والحجوزات وجدولة المواعيد.",
      },
      business: {
        name: "الأعمال",
        summary: "نمِّ أعمالك بتحليلات متقدمة وتنظيف البيانات والمخططات والرؤى الجاهزة للتصدير.",
      },
      business_plus: {
        name: "الأعمال بلس",
        summary: "أدر الحجوزات والمواعيد وطلبات العملاء من مساحة عمل قوية واحدة.",
      },
    },
    featureLabels: {
      unlimited_forms_submissions: "نماذج وردود غير محدودة",
      hosted_public_form_links: "روابط نماذج عامة مستضافة",
      response_management_overview: "إدارة الردود ونظرة عامة",
      data_import_standard_analysis: "استيراد البيانات والتحليل القياسي",
      visual_page_builder: "منشئ صفحات مرئي",
      one_published_website: "موقع منشور واحد",
      standard_hosted_address: "عنوان استضافة قياسي",
      image_uploads_response_management: "رفع الصور وإدارة الردود",
      reservation_system: "منشئ الحجوزات وإدارة الطلبات والتقويم وجدولة المواعيد",
      everything_website: "كل ما في خطة الموقع",
      expanded_analytics: "أدوات تحليل موسعة",
      data_cleaning: "تنظيف البيانات",
      charts_data_exports: "رسوم بيانية وتصدير البيانات",
      cv_reranker: "إعادة ترتيب السير الذاتية بالذكاء الاصطناعي",
      everything_business: "كل ما في خطة الأعمال",
      unlimited_reservation_requests: "طلبات حجز غير محدودة",
      reservation_management_analytics: "تحليلات حجوزات متقدمة",
      internal_calendar: "التقويم وجدولة المواعيد",
      priority_support: "تصنيف دعم ذو أولوية",
    },
    addons: {},
  },
};

export const getPricingContent = (lang = "en") =>
  pricingContent[lang === "ar" ? "ar" : "en"];
