export const uiText = {
  en: {
    kicker: "Data workspace",
    title: "Data workspace",
    subtitle:
      "Review collected records, clean fields, create charts, and prepare reports from one workspace.",
    working: "Working...",
    saveDataframes: "Save dataframes",
    saveDataframesTitle: "Save dataframes",
    saveDataframesHint: "Save both the original and cleaned dataframe.",
    flowIssueTitle: "Action needed",
    continue: "Continue",
    back: "Back",
    optional: "Optional",
    source: "Source",
    review: "Review",
    prepare: "Prepare",
    visualization: "Charts",
    report: "Report",
    assistant: "Question",
    sourceTitle: "Choose your data source",
    sourceSubtitle:
      "Start with one source. More tools appear after the dataset is loaded.",
    forms: "Website responses",
    upload: "Spreadsheet upload",
    external: "External link",
    fromWebsite: "Use collected form responses",
    fromWebsiteHint: "Convert submitted website form responses into a dataset.",
    form: "Form",
    responses: "responses",
    importResponses: "Import responses",
    viewResponses: "View responses",
    uploadTitle: "Upload a spreadsheet",
    uploadHint: "CSV, XLS, and XLSX files are supported.",
    chooseFile: "Choose file or drop it here",
    readyToLoad: "Ready to load",
    loadFile: "Load file",
    externalTitle: "Connect public data",
    externalHint: "Use CSV, Excel, JSON API, or a published Google Sheet.",
    dataLink: "Data link",
    sheetsNote:
      "Google Sheets must be shared publicly or published to the web.",
    loadLink: "Load link",
    datasetReady: "Dataset ready",
    noDataset: "No dataset loaded yet",
    noDatasetHint:
      "Choose a data source first to unlock review, preparation, and reporting.",
    rows: "Rows",
    columns: "Columns",
    preview: "Preview",
    searchRows: "Search preview rows...",
    noRows: "No matching rows",
    noRowsHint: "Try a different search term.",
    first: "First",
    previous: "Previous",
    next: "Next",
    last: "Last",
    pageOf: (page, total) => `Page ${page} of ${total}`,
    showingRows: (start, end, total) => `Showing ${start}-${end} of ${total}`,
    firstColumns: "First 8",
    allColumns: "All",
    stepsLabel: "Data analysis steps",
    reviewTitle: "Review data",
    reviewSubtitle: "Check the dataset before cleaning or reporting.",
    overview: "Data summary",
    statistics: "Number checks",
    missing: "Empty answers",
    quality: "Answer list",
    reviewOverviewHint: "See what is in your data.",
    reviewStatisticsHint: "See totals, averages, smallest, and largest numbers.",
    reviewMissingHint: "Find answers that were left blank.",
    reviewQualityHint: "See each question and the answers people gave.",
    inspectionWaiting: "Choose a review action to show the result here.",
    itemCount: (count) => `${count} item${count === 1 ? "" : "s"}`,
    fieldsChecked: "Fields checked",
    fieldsWithGaps: "Fields with gaps",
    columnsReviewed: "Columns reviewed for empty answers.",
    noMissingAnswers: "No missing answers found.",
    reviewBeforeReporting: "Review these before reporting.",
    whatThisMeans: "What this means",
    allFieldsComplete: "All checked fields are complete.",
    fieldsHaveEmptyAnswers: (count) => `${count} field${count === 1 ? "" : "s"} have empty answers.`,
    field: "Field",
    bestUse: "Best use",
    filledAnswers: "Filled answers",
    emptyAnswers: "Empty answers",
    emptyPercent: "Empty %",
    uniqueValues: "Unique values",
    differentAnswers: "Different answers",
    examples: "Examples",
    status: "Status",
    complete: "Complete",
    needsAttention: "Needs attention",
    rowsAnalyzed: "Rows analyzed",
    responsesIncluded: "Responses included in this check.",
    numberFields: "Number fields",
    numberFieldsHint: "Fields where averages and totals apply.",
    textFields: "Text fields",
    textFieldsHint: "Fields summarized by common answers.",
    numericStatsHint: "Number fields include averages, totals, lowest, and highest values.",
    noNumericStatsHint: "No number fields were detected, so this dataset is summarized by common answers instead of averages.",
    categoryStatsHint: "Text and choice fields show the most common answer and example values.",
    noCategoryStatsHint: "No text or choice fields were detected.",
    numberSummaries: "Number summaries",
    answerSummaries: "Answer summaries",
    quantitativeSummaries: "Number summary",
    qualitativeValues: "Answer choices",
    qualitativeFields: "Answer fields",
    qualitativeFieldsHint: "Fields with text, dates, categories, statuses, or choices.",
    qualitativeAuditHint: "Use this view to see the answer fields and the values people used in them.",
    qualitativeValuesHint: "Each card shows one field, how complete it is, and its unique values.",
    noQualitativeValuesHint: "No answer fields were found in this dataset.",
    noValues: "No values",
    type: "Type",
    numberType: "Number",
    textChoiceType: "Text or choice",
    average: "Average",
    middle: "Middle",
    lowest: "Lowest",
    highest: "Highest",
    total: "Total",
    mostCommon: "Most common",
    rowsLoadedHint: "Records loaded from the source.",
    fields: "Fields",
    fieldsAvailableHint: "Columns available for reporting.",
    datasetShape: (rows, columns) => `The dataset has ${rows} row${Number(rows) === 1 ? "" : "s"} and ${columns} fields.`,
    confirmExpectedFields: "Use this view to confirm the expected fields were imported before building a report.",
    fieldGuide: "Field guide",
    qualityScore: "Quality score",
    qualityScoreHint: "Based on missing answers and duplicates.",
    completeAnswers: "Complete answers",
    completeAnswersHint: "How much of the dataset is filled.",
    duplicateRows: "Duplicate rows",
    duplicateRowsHint: "Repeated records found.",
    recommendedNextSteps: "Recommended next steps",
    actionReviewMissing: "Review or fill empty answers before reporting.",
    actionRemoveDuplicates: "Remove duplicate rows before reporting.",
    actionCheckMixedFormats: "Check columns that may have mixed formats.",
    actionNoCleanupNeeded: "No major cleanup needed before reporting.",
    readyForReporting: "Ready for reporting",
    readyToUse: "Ready to use",
    needsReview: "Needs review",
    check: "Check",
    emptyCells: "Empty cells",
    rowsChecked: "Rows checked",
    fieldsCheckedShort: "Fields checked",
    fieldQuality: "Field quality",
    typeLabels: {
      boolean: "Yes / no",
      number: "Number",
      money: "Money",
      date: "Date",
      multi_choice: "Multiple choice",
      category: "Category",
      text: "Text",
    },
    prepareTitle: "Clean up your data",
    prepareSubtitle: "Pick only the fixes you want. You can continue without changing anything.",
    selected: "selected",
    basicCleaning: "Recommended fixes",
    advancedCleaning: "Advanced options",
    trimText: "Fix extra spaces",
    trimTextHint: "Removes spaces before and after text answers.",
    lowercaseText: "Group similar text answers",
    lowercaseTextHint: "Turns text into lowercase so answers like Yes and yes match.",
    removeDuplicates: "Remove repeated rows",
    removeDuplicatesHint: "Deletes rows that are exactly the same.",
    removeMissingRows: "Remove incomplete rows",
    removeMissingRowsHint: "Deletes rows with missing answers. Use only if every answer is required.",
    fillMissing: "Fill blank cells",
    fillMissingHint: "Choose one column and decide what should replace empty cells.",
    setupFillRule: "Set fill rule",
    removeFillRule: "Remove rule",
    fillColumn: "Choose a column",
    fillWith: "Fill blanks with",
    mostCommonValue: "Most common value",
    fillAverage: "Average",
    median: "Median",
    previousValue: "Previous value",
    nextValue: "Next value",
    customValue: "Custom value",
    changeColumnType: "Fix a column type",
    changeColumnTypeHint: "Use this if a number, date, or yes/no field was read incorrectly.",
    convertColumn: "Choose a column",
    convertTo: "Read it as",
    number: "Number",
    date: "Date",
    text: "Text",
    category: "Category",
    yesNo: "Yes / no",
    renameColumn: "Rename a column",
    renameColumnHint: "Give a column a clearer name for the report.",
    newName: "New column name",
    excludeColumns: "Remove selected columns",
    excludeColumnsHint: "Choose columns you do not want in the cleaned data.",
    confirmDropColumns: "Remove selected columns",
    dropColumnsConfirmed: "Columns will be removed",
    confirmDropColumnsHint: "This only changes the cleaned copy used for analysis. Your original upload stays the same.",
    labellingCard: "Make answers usable in charts",
    labellingCardHint: "Use this when text answers need to become number fields.",
    encodeColumns: "Label answer columns",
    encodeColumnsHint: "Use this when charts or analysis need text answers as numbers.",
    columnsToEncode: "Choose answer columns",
    encodingMethod: "Choose how labels are created",
    oneHotEncoding: "Create a yes/no column for each answer",
    oneHotEncodingHint: "Best for answer choices. Example: Red creates a Red yes/no column, Blue creates a Blue yes/no column.",
    labelEncoding: "Create one number column",
    labelEncodingHint: "Best when one answer should become one code. Example: Red, Blue, Green become 1, 2, 3.",
    reportTitle: "Create report",
    reportSubtitle:
      "Choose a report type, map the required fields, then create the report.",
    reportGroup: "Report category",
    reportType: "Report type",
    runReport: "Create report",
    readyToGenerate: "Ready to create",
    generateReportHint: "Create the report after choosing the report type and required fields.",
    customizeReport: "Customize report",
    customizeReportHint: "Choose what appears in the final report view.",
    reportDisplayTitle: "Report title",
    includeSummary: "Summary",
    includeKpis: "KPIs",
    includeInsights: "Insights",
    includeTables: "Tables",
    includeCharts: "Charts",
    includeWarnings: "Warnings",
    reportCanvas: "Report canvas",
    reportWaiting: "Create a report to display results here.",
    loadDataBeforeReview: "Load data before reviewing it.",
    loadDataBeforeAnalysis: "Load data before creating a report.",
    generateMetricsFirst: "Create metrics after cleaning your data before opening Charts or Report.",
    missingRequiredFields: (fields) => `Please choose the required fields first: ${fields.join(", ")}.`,
    chooseFileFirst: "Choose a file first.",
    pasteLinkFirst: "Paste a public data link or API URL first.",
    createFormFirst: "Create a form before importing collected data.",
    emptyForm: "This form has no submitted responses yet.",
    writeQuestionFirst: "Write a question first.",
    selectColumn: "Select column",
    selectedColumn: "Selected column",
    selectedColumns: "Selected columns",
    noGrouping: "No grouping",
    loadDataToChooseColumns: "Load data to choose columns.",
    askAssistant: "Data question",
    assistantSubtitle:
      "Ask a focused question about summaries, missing values, totals, correlations, or useful fields.",
    assistantPlaceholder: "Example: What is the average cost by department?",
    ask: "Ask",
    assistantWaiting: "Type a question after loading data.",
    summary: "Summary",
    insights: "Insights",
    kpis: "KPIs",
    tables: "Tables",
    warnings: "Warnings",
    charts: "Charts",
    metadata: "Metadata",
    result: "Result",
    noResult: "No result yet",
    yes: "Yes",
    no: "No",
  },
  ar: {
    kicker: "مساحة البيانات",
    title: "إنشاء تقرير واضح",
    subtitle:
      "حمّل البيانات، راجعها، جهزها، ثم أنشئ تقريرا مركزا من مساحة عمل موجهة.",
    working: "جار العمل...",
    flowIssueTitle: "تنبيه مهم",
    continue: "متابعة",
    back: "رجوع",
    optional: "اختياري",
    source: "المصدر",
    review: "المراجعة",
    prepare: "التجهيز",
    visualization: "التصور",
    report: "التقرير",
    assistant: "المساعد",
    sourceTitle: "اختر مصدر البيانات",
    sourceSubtitle:
      "ابدأ بمصدر واحد. تظهر الأدوات الأخرى بعد تحميل البيانات.",
    forms: "ردود الموقع",
    upload: "رفع جدول",
    external: "رابط خارجي",
    fromWebsite: "استخدم ردود النماذج",
    fromWebsiteHint: "حوّل ردود نماذج الموقع إلى مجموعة بيانات.",
    form: "النموذج",
    responses: "ردود",
    importResponses: "استيراد الردود",
    viewResponses: "عرض الردود",
    uploadTitle: "رفع جدول بيانات",
    uploadHint: "يدعم ملفات CSV و XLS و XLSX.",
    chooseFile: "اختر ملفا أو اسحبه هنا",
    readyToLoad: "جاهز للتحميل",
    loadFile: "تحميل الملف",
    externalTitle: "ربط بيانات عامة",
    externalHint: "استخدم CSV أو Excel أو JSON API أو Google Sheet منشورا.",
    dataLink: "رابط البيانات",
    sheetsNote: "يجب أن يكون Google Sheet مشتركا للعامة أو منشورا على الويب.",
    loadLink: "تحميل الرابط",
    datasetReady: "البيانات جاهزة",
    noDataset: "لم يتم تحميل بيانات بعد",
    noDatasetHint: "اختر مصدر بيانات أولا لفتح المراجعة والتجهيز والتقارير.",
    rows: "الصفوف",
    columns: "الأعمدة",
    preview: "معاينة",
    searchRows: "ابحث في الصفوف...",
    noRows: "لا توجد صفوف مطابقة",
    noRowsHint: "جرب كلمة بحث مختلفة.",
    first: "الأول",
    previous: "السابق",
    next: "التالي",
    last: "الأخير",
    pageOf: (page, total) => `الصفحة ${page} من ${total}`,
    showingRows: (start, end, total) => `عرض ${start}-${end} من ${total}`,
    firstColumns: "أول 8",
    allColumns: "الكل",
    stepsLabel: "خطوات تحليل البيانات",
    reviewTitle: "راجع البيانات",
    reviewSubtitle: "شغّل فحوصات سريعة قبل تجهيز التقرير.",
    overview: "نظرة عامة",
    statistics: "الإحصاءات",
    missing: "القيم المفقودة",
    quality: "الجودة",
    reviewOverviewHint: "افهم محتوى مجموعة البيانات.",
    reviewStatisticsHint: "اعرض الإجماليات والإجابات الشائعة والملخصات الرقمية.",
    reviewMissingHint: "ابحث عن الإجابات الفارغة التي قد تؤثر على التقرير.",
    reviewQualityHint: "تحقق من الجاهزية والتكرار ونصائح التنظيف.",
    inspectionWaiting: "اختر إجراء مراجعة لعرض النتيجة هنا.",
    itemCount: (count) => `${count} عنصر`,
    fieldsChecked: "الحقول التي تم فحصها",
    fieldsWithGaps: "حقول بها نقص",
    columnsReviewed: "تمت مراجعة الأعمدة بحثا عن إجابات فارغة.",
    noMissingAnswers: "لم يتم العثور على إجابات مفقودة.",
    reviewBeforeReporting: "راجع هذه الحقول قبل إنشاء التقرير.",
    whatThisMeans: "ماذا يعني ذلك",
    allFieldsComplete: "كل الحقول التي تم فحصها مكتملة.",
    fieldsHaveEmptyAnswers: (count) => `${count} حقول تحتوي على إجابات فارغة.`,
    field: "الحقل",
    bestUse: "أفضل استخدام",
    filledAnswers: "إجابات مكتملة",
    emptyAnswers: "إجابات فارغة",
    emptyPercent: "نسبة الفراغ",
    differentAnswers: "إجابات مختلفة",
    examples: "أمثلة",
    status: "الحالة",
    complete: "مكتمل",
    needsAttention: "يحتاج مراجعة",
    rowsAnalyzed: "الصفوف التي تم تحليلها",
    responsesIncluded: "الردود المشمولة في هذا الفحص.",
    numberFields: "حقول رقمية",
    numberFieldsHint: "حقول يمكن حساب المتوسطات والإجماليات لها.",
    textFields: "حقول نصية",
    textFieldsHint: "حقول يتم تلخيصها حسب الإجابات الشائعة.",
    numericStatsHint: "الحقول الرقمية تعرض المتوسطات والإجماليات وأقل وأعلى قيمة.",
    noNumericStatsHint: "لم يتم اكتشاف حقول رقمية، لذلك يتم تلخيص البيانات حسب الإجابات الشائعة بدلا من المتوسطات.",
    categoryStatsHint: "حقول النص والاختيار تعرض الإجابة الأكثر شيوعا وأمثلة من القيم.",
    noCategoryStatsHint: "لم يتم اكتشاف حقول نصية أو اختيارية.",
    numberSummaries: "ملخصات رقمية",
    answerSummaries: "ملخصات الإجابات",
    type: "النوع",
    numberType: "رقم",
    textChoiceType: "نص أو اختيار",
    average: "المتوسط",
    middle: "الوسيط",
    lowest: "الأدنى",
    highest: "الأعلى",
    total: "الإجمالي",
    mostCommon: "الأكثر شيوعا",
    rowsLoadedHint: "السجلات التي تم تحميلها من المصدر.",
    fields: "الحقول",
    fieldsAvailableHint: "الأعمدة المتاحة للتقارير.",
    datasetShape: (rows, columns) => `تحتوي مجموعة البيانات على ${rows} صف و ${columns} حقل.`,
    confirmExpectedFields: "استخدم هذه النظرة للتأكد من استيراد الحقول المتوقعة قبل بناء التقرير.",
    fieldGuide: "دليل الحقول",
    qualityScore: "درجة الجودة",
    qualityScoreHint: "محسوبة بناء على الإجابات الفارغة والصفوف المكررة.",
    completeAnswers: "الإجابات المكتملة",
    completeAnswersHint: "مدى اكتمال البيانات.",
    duplicateRows: "صفوف مكررة",
    duplicateRowsHint: "السجلات المتكررة التي تم العثور عليها.",
    recommendedNextSteps: "الخطوات المقترحة",
    actionReviewMissing: "راجع الإجابات الفارغة أو املأها قبل إنشاء التقرير.",
    actionRemoveDuplicates: "أزل الصفوف المكررة قبل إنشاء التقرير.",
    actionCheckMixedFormats: "راجع الأعمدة التي قد تحتوي على تنسيقات مختلطة.",
    actionNoCleanupNeeded: "لا توجد حاجة لتنظيف كبير قبل إنشاء التقرير.",
    readyForReporting: "جاهز للتقرير",
    readyToUse: "جاهز للاستخدام",
    needsReview: "يحتاج مراجعة",
    check: "الفحص",
    emptyCells: "خلايا فارغة",
    rowsChecked: "صفوف تم فحصها",
    fieldsCheckedShort: "حقول تم فحصها",
    fieldQuality: "جودة الحقول",
    typeLabels: {
      boolean: "نعم / لا",
      number: "رقم",
      money: "مبلغ مالي",
      date: "تاريخ",
      multi_choice: "اختيار متعدد",
      category: "تصنيف",
      text: "نص",
    },
    prepareTitle: "جهّز البيانات",
    prepareSubtitle: "طبّق خطوات التنظيف التي تحتاجها فقط.",
    basicCleaning: "تنظيف أساسي",
    advancedCleaning: "تنظيف متقدم",
    trimText: "تنظيف المسافات في أعمدة النص",
    lowercaseText: "توحيد النص إلى أحرف صغيرة",
    removeDuplicates: "إزالة الصفوف المكررة",
    removeMissingRows: "إزالة الصفوف ذات الإجابات الفارغة",
    fillMissing: "تعبئة القيم المفقودة",
    fillColumn: "العمود المراد تعبئته",
    fillWith: "التعبئة باستخدام",
    mostCommonValue: "القيمة الأكثر تكرارا",
    fillAverage: "المتوسط",
    median: "الوسيط",
    previousValue: "القيمة السابقة",
    nextValue: "القيمة التالية",
    customValue: "قيمة مخصصة",
    convertColumn: "تحويل عمود",
    convertTo: "تحويل إلى",
    number: "رقم",
    date: "تاريخ",
    text: "نص",
    category: "تصنيف",
    yesNo: "نعم / لا",
    renameColumn: "إعادة تسمية عمود",
    newName: "الاسم الجديد",
    removeOutliersFrom: "إزالة القيم الشاذة من",
    excludeColumns: "استبعاد أعمدة",
    reportTitle: "بناء التقرير",
    reportSubtitle:
      "اختر نوع تقرير واحدا، اربط الحقول المطلوبة، ثم أنشئ التقرير.",
    reportGroup: "تصنيف التقرير",
    reportType: "نوع التقرير",
    runReport: "إنشاء التقرير",
    readyToGenerate: "جاهز للإنشاء",
    generateReportHint: "أنشئ التقرير بعد اختيار نوع التقرير والحقول المطلوبة.",
    customizeReport: "تخصيص التقرير",
    customizeReportHint: "اختر ما يظهر في عرض التقرير النهائي.",
    reportDisplayTitle: "عنوان التقرير",
    includeSummary: "الملخص",
    includeKpis: "المؤشرات",
    includeInsights: "الرؤى",
    includeTables: "الجداول",
    includeCharts: "الرسوم",
    includeWarnings: "التنبيهات",
    reportCanvas: "لوحة التقرير",
    reportWaiting: "أنشئ تقريرا لعرض النتائج هنا.",
    loadDataBeforeReview: "حمّل البيانات قبل مراجعتها.",
    loadDataBeforeAnalysis: "حمّل البيانات قبل إنشاء التقرير.",
    missingRequiredFields: (fields) => `يرجى اختيار الحقول المطلوبة أولا: ${fields.join("، ")}.`,
    chooseFileFirst: "اختر ملفا أولا.",
    pasteLinkFirst: "الصق رابط بيانات عام أو رابط API أولا.",
    createFormFirst: "أنشئ نموذجا قبل استيراد البيانات.",
    emptyForm: "لا توجد ردود مرسلة لهذا النموذج بعد.",
    writeQuestionFirst: "اكتب السؤال أولا.",
    selectColumn: "اختر عمودا",
    selectedColumn: "العمود المختار",
    selectedColumns: "الأعمدة المختارة",
    noGrouping: "بدون تجميع",
    loadDataToChooseColumns: "حمّل البيانات لاختيار الأعمدة.",
    askAssistant: "اسأل مساعد البيانات",
    assistantSubtitle:
      "استخدم قواعد محلية للملخصات والقيم المفقودة والمتوسطات والمجاميع والارتباطات واقتراحات الأعمدة.",
    assistantPlaceholder: "مثال: ما متوسط التكلفة حسب القسم؟",
    ask: "اسأل",
    assistantWaiting: "اكتب سؤالا بعد تحميل البيانات.",
    summary: "الملخص",
    insights: "الرؤى",
    kpis: "المؤشرات",
    tables: "الجداول",
    warnings: "التنبيهات",
    charts: "الرسوم",
    metadata: "البيانات الوصفية",
    result: "النتيجة",
    noResult: "لا توجد نتيجة بعد",
    yes: "نعم",
    no: "لا",
  },
};
