ANALYSIS_CATALOG = {
    "finance": {
        "label": "Finance",
        "description": "Revenue, cost, budget, donor funding, and transaction reports.",
        "reports": [
            {"id": "profit_loss_summary", "label": "Profit and loss summary", "fields": {"revenue_column": "money", "cost_column": "money"}, "chart": "kpi"},
            {"id": "add_profit_column", "label": "Add profit column", "fields": {"revenue_column": "money", "cost_column": "money", "profit_column": "text"}, "chart": "table"},
            {"id": "budget_vs_actual", "label": "Budget vs actual", "fields": {"budget_column": "money", "actual_column": "money", "group_column": "category?"}, "chart": "bar"},
            {"id": "expense_summary", "label": "Expense summary", "fields": {"expense_column": "money", "category_column": "category?"}, "chart": "bar"},
            {"id": "revenue_by_group", "label": "Revenue by group", "fields": {"revenue_column": "money", "group_column": "category"}, "chart": "bar"},
            {"id": "monthly_summary", "label": "Monthly summary", "fields": {"date_column": "date", "value_columns": "number[]"}, "chart": "line"},
            {"id": "daily_summary", "label": "Daily summary", "fields": {"date_column": "date", "value_columns": "number[]"}, "chart": "line"},
            {"id": "cash_flow_summary", "label": "Cash flow summary", "fields": {"inflow_column": "money", "outflow_column": "money"}, "chart": "kpi"},
            {"id": "top_expenses", "label": "Top expenses", "fields": {"expense_column": "money", "rows": "number?"}, "chart": "table"},
            {"id": "financial_ratios", "label": "Financial ratios", "fields": {"revenue_column": "money", "cost_column": "money", "expense_column": "money?"}, "chart": "kpi"},
            {"id": "detect_negative_values", "label": "Negative value check", "fields": {"columns": "number[]"}, "chart": "table"},
            {"id": "transaction_summary", "label": "Transaction summary", "fields": {"amount_column": "money", "transaction_id_column": "text?"}, "chart": "kpi"},
            {"id": "cost_per_beneficiary", "label": "Cost per beneficiary", "fields": {"cost_column": "money", "beneficiary_column": "number", "group_column": "category?"}, "chart": "bar"},
            {"id": "donor_funding_summary", "label": "Donor funding summary", "fields": {"donor_column": "category", "amount_column": "money"}, "chart": "bar"},
        ],
    },
    "meal": {
        "label": "Operations",
        "description": "Department, item, quantity, price, and revenue analysis.",
        "reports": [
            {"id": "department_summary", "label": "Department summary", "fields": {"department_column": "category", "numeric_columns": "number[]"}, "chart": "bar"},
            {"id": "top_meals", "label": "Top items", "fields": {"meal_column": "category", "value_column": "number", "rows": "number?"}, "chart": "bar"},
            {"id": "average_price_by_department", "label": "Average price by department", "fields": {"department_column": "category", "price_column": "money"}, "chart": "bar"},
            {"id": "meal_counts", "label": "Item counts", "fields": {"column": "category"}, "chart": "bar"},
            {"id": "revenue_by_meal", "label": "Revenue by item", "fields": {"meal_column": "category", "revenue_column": "money"}, "chart": "bar"},
            {"id": "quantity_by_department", "label": "Quantity by department", "fields": {"department_column": "category", "quantity_column": "number"}, "chart": "bar"},
        ],
    },
    "hr": {
        "label": "Human resources",
        "description": "Workforce, compensation, department, and attendance analysis.",
        "reports": [
            {"id": "workforce_summary", "label": "Workforce summary", "fields": {"department_column": "category?"}, "chart": "bar"},
            {"id": "compensation_summary", "label": "Compensation summary", "fields": {"salary_column": "money", "department_column": "category?"}, "chart": "kpi"},
            {"id": "attendance_summary", "label": "Attendance summary", "fields": {"attended_days_column": "number", "working_days_column": "number", "department_column": "category?"}, "chart": "kpi"},
        ],
    },
    "ngo_meal": {
        "label": "Program monitoring",
        "description": "Progress, beneficiaries, activities, surveys, cases, and feedback.",
        "reports": [
            {"id": "indicator_progress", "label": "Indicator progress", "fields": {"indicator_column": "category", "actual_column": "number", "target_column": "number", "group_column": "category?"}, "chart": "bar"},
            {"id": "target_achievement", "label": "Target achievement", "fields": {"actual_column": "number", "target_column": "number"}, "chart": "kpi"},
            {"id": "beneficiary_summary", "label": "Beneficiary summary", "fields": {"beneficiary_column": "number", "group_columns": "category[]?"}, "chart": "bar"},
            {"id": "disaggregation_summary", "label": "Disaggregation summary", "fields": {"value_column": "number", "disaggregation_columns": "category[]"}, "chart": "bar"},
            {"id": "baseline_endline_change", "label": "Baseline to endline change", "fields": {"group_column": "category", "baseline_column": "number", "endline_column": "number"}, "chart": "bar"},
            {"id": "activity_completion_rate", "label": "Activity completion rate", "fields": {"completed_column": "number", "planned_column": "number", "group_column": "category?"}, "chart": "bar"},
            {"id": "survey_question_summary", "label": "Survey question summary", "fields": {"question_column": "category", "response_column": "category"}, "chart": "bar"},
            {"id": "location_summary", "label": "Location summary", "fields": {"location_column": "category", "value_columns": "number[]"}, "chart": "bar"},
            {"id": "partner_summary", "label": "Partner summary", "fields": {"partner_column": "category", "value_columns": "number[]"}, "chart": "bar"},
            {"id": "vulnerability_summary", "label": "Vulnerability summary", "fields": {"vulnerability_column": "category", "beneficiary_column": "number"}, "chart": "bar"},
            {"id": "complaint_feedback_summary", "label": "Complaint and feedback summary", "fields": {"channel_column": "category", "status_column": "category"}, "chart": "bar"},
            {"id": "case_status_summary", "label": "Case status summary", "fields": {"status_column": "category", "group_column": "category?"}, "chart": "bar"},
            {"id": "attendance_rate", "label": "Attendance rate", "fields": {"attended_column": "number", "registered_column": "number", "group_column": "category?"}, "chart": "bar"},
        ],
    },
    "forms": {
        "label": "Forms",
        "description": "Generic form response quality, completion, distribution, and rating reports.",
        "reports": [
            {"id": "response_overview", "label": "Response overview", "fields": {"date_column": "date?", "status_column": "category?"}, "chart": "line"},
            {"id": "question_distribution", "label": "Question distribution", "fields": {"question_column": "category", "rows": "number?"}, "chart": "bar"},
            {"id": "numeric_question_summary", "label": "Column statistics", "fields": {"numeric_columns": "number[]"}, "chart": "table"},
            {"id": "rating_summary", "label": "Rating summary", "fields": {"rating_column": "number", "max_rating": "number?", "group_column": "category?"}, "chart": "bar"},
            {"id": "multi_select_summary", "label": "Multi-select summary", "fields": {"column": "multi_choice", "separator": "text?"}, "chart": "bar"},
            {"id": "column_suggestions", "label": "Column suggestions", "fields": {}, "chart": "table"},
        ],
    },
    "assisted": {
        "label": "Assisted",
        "description": "Offline custom indicators and statistical questions for future chatbot-assisted analysis.",
        "reports": [
            {"id": "offline_question", "label": "Offline question", "fields": {"question": "text"}, "chart": "table"},
            {"id": "custom_metric", "label": "Custom metric", "fields": {"operation": "text", "value_column": "number?", "numerator_column": "number?", "denominator_column": "number?", "group_column": "category?"}, "chart": "auto"},
        ],
    },
}
