create table if not exists public.tenants (
  tenant_id integer generated by default as identity primary key,
  brand_name text not null default '',
  owner_name text not null default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table public.users
add column if not exists tenant_id integer;

insert into public.tenants (brand_name, owner_name)
select
  '',
  trim(coalesce(first_name, '') || ' ' || coalesce(last_name, ''))
from public.users
where tenant_id is null
returning tenant_id;

with new_tenants as (
  select
    u.id as user_id,
    t.tenant_id
  from public.users u
  join public.tenants t
    on t.owner_name = trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, ''))
  where u.tenant_id is null
)
update public.users u
set tenant_id = nt.tenant_id
from new_tenants nt
where u.id = nt.user_id;

alter table public.users
alter column tenant_id set not null;

alter table public.users
drop constraint if exists users_tenant_id_unique;

alter table public.users
add constraint users_tenant_id_unique unique (tenant_id);

alter table public.users
drop constraint if exists users_tenant_id_fkey;

alter table public.users
add constraint users_tenant_id_fkey
foreign key (tenant_id)
references public.tenants(tenant_id)
on delete restrict;

alter table public.website_settings
add column if not exists tenant_id integer;

alter table public.website_settings
drop constraint if exists website_settings_tenant_id_unique;

alter table public.website_settings
add constraint website_settings_tenant_id_unique unique (tenant_id);

alter table public.website_settings
drop constraint if exists website_settings_tenant_id_fkey;

alter table public.website_settings
add constraint website_settings_tenant_id_fkey
foreign key (tenant_id)
references public.tenants(tenant_id)
on delete set null;

notify pgrst, 'reload schema';