import { afterEach, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import App from "./App";
import { useEffect } from "react";
const mocks = vi.hoisted(() => ({ weekly: vi.fn(() => 0), register: vi.fn(async () => ({})), push: vi.fn(async () => {}), notifications: vi.fn() }));
vi.mock("react-i18next", async original => ({ ...(await original()), useTranslation: () => ({ t: key => key, i18n: { language: "en", changeLanguage: vi.fn(), on: vi.fn(), off: vi.fn() } }) }));
vi.mock("./routes/routePreload", () => ({ useRoutePreloading: () => {}, clearRoutePreloadedData: () => {} }));
vi.mock("./hooks/useWeeklyScreenTime", () => ({ default: mocks.weekly }));
vi.mock("./pwa/installation", () => ({ getInstallationId: () => "unit", registerInstallation: mocks.register }));
vi.mock("./pwa/pwaContext", () => ({ isMadarPwaHost: () => true }));
vi.mock("./services/notificationsApi", () => ({ reconcileBrowserPushLifecycle: mocks.push }));
vi.mock("./utils/scheduleIdleWork", () => ({ scheduleIdleWork: fn => { const timer = setTimeout(fn, 0); return () => clearTimeout(timer); } }));
vi.mock("./notifications/NotificationProvider", () => ({ NotificationProvider: ({ children }) => { useEffect(() => { mocks.notifications(); }, []); return children; } }));
vi.mock("./notifications/NotificationToastViewport", () => ({ default: () => null }));
vi.mock("./components/DashboardBuilder/CommerceActionToast", () => ({ default: () => null }));
vi.mock("./routes/UserWorkspaceRoutes", () => ({ default: ({ user, onUserUpdated }) => <button onClick={() => onUserUpdated({ ...user, user_type: "admin" })}>Switch synthetic account</button> }));
vi.mock("./routes/AdminRoutes", () => ({ default: () => <p>Platform shell</p> }));
vi.mock("./utils/apiClient", async original => ({ ...(await original()), apiFetch: vi.fn(async () => ({ ok: true, status: 200, json: async () => ({ logged_in: true, user: { id: 7, tenant_id: 42, account_kind: "platform", user_type: "user" } }) })) }));
afterEach(cleanup);
it("tenant services initialize for workspace users and stop at the platform-admin boundary", async () => {
  window.scrollTo = vi.fn(); render(<MemoryRouter initialEntries={["/dashboard"]}><App /></MemoryRouter>);
  await screen.findByRole("button", { name: "Switch synthetic account" });
  await waitFor(() => expect(mocks.register).toHaveBeenCalledOnce());
  expect(mocks.push).toHaveBeenCalledOnce(); expect(mocks.notifications).toHaveBeenCalledOnce();
  expect(mocks.weekly.mock.calls.at(-1)[0].user_type).toBe("user");
  fireEvent.click(screen.getByRole("button", { name: "Switch synthetic account" }));
  await screen.findByText("Platform shell");
  expect(mocks.weekly.mock.calls.at(-1)[0]).toBeNull();
  expect(mocks.register).toHaveBeenCalledOnce(); expect(mocks.push).toHaveBeenCalledOnce(); expect(mocks.notifications).toHaveBeenCalledOnce();
});
